### ISSUE TITLE
Fully implement WebGL 1.0

### ISSUE THREAD

**Issue by emilio** [servo/servo#10209]
This is intended to be a meta-bug.

Some of the remaining methods are blocked on https://github.com/servo/servo/issues/5014 (those that receive `ArrayBufferView` or `BufferDataSource` and have overrides), but some others can be implemented without problems.

I'll try to fill individual issues for each remaining methods, since some of them can be E-Easy.

<a name="general-info"></a>
### Spec

The WebGL 1.0 spec is [here](https://www.khronos.org/registry/webgl/specs/latest/1.0/).

### GLES 2.0 spec

WebGL is based on the GLES 2.0 spec, so the WebGL spec often leverages details to it. You can find a PDF version [here](https://www.khronos.org/registry/gles/specs/2.0/es_full_spec_2.0.25.pdf#nameddest=section-3.7).

#### DOM

The DOM side of the WebGL code can be found in the following files:

 * `components/script/dom/webglrenderingcontext.rs`
 * `components/script/dom/webglactiveinfo.rs` 
 * `components/script/dom/webglbuffer.rs` 
 * `components/script/dom/webglcontextevent.rs` 
 * `components/script/dom/webglframebuffer.rs ` 
 * `components/script/dom/webglobject.rs` 
 * `components/script/dom/webglprogram.rs` 
 * `components/script/dom/webglrenderbuffer.rs` 
 * `components/script/dom/webglrenderingcontext.rs` 
 * `components/script/dom/webglshader.rs` 
 * `components/script/dom/webglshaderprecisionformat.rs` 
 * `components/script/dom/webgltexture.rs` 
 * `components/script/dom/webgluniformlocation.rs`

#### WebGL thread

The WebGL thread is the thread that receives the WebGL messages from the DOM, and either executes it or dispatchs it to the WebRender backend.

You probably don't need to touch anything here, but in case you want to take a look, the file is:

 * `components/canvas/webgl_paint_thread.rs`

#### WebGL command definition, execution, and other types

The rest of the WebGL definitions and the command implementations are in [`webrender_traits`'s `webgl.rs` file](https://github.com/servo/webrender_traits/blob/master/src/webgl.rs), in order to be shared by both Servo and WebRender.

You'll want to take a look to the [`WebGLCommand` definition](https://github.com/servo/webrender_traits/blob/master/src/webgl.rs#L48) and to the [`apply` function](https://github.com/servo/webrender_traits/blob/master/src/webgl.rs#L195).

To work actively with it the best is to use a [Cargo override](http://doc.crates.io/guide.html#overriding-dependencies).

Note that `WebGLCommand` is [re-exported](https://github.com/servo/servo/blob/master/components/canvas_traits/lib.rs#L40-L41) from `canvas_traits` as `CanvasWebGLMessage` for legacy reasons (to avoid extra rebase pain while webrender hadn't merged yet).

## Pending implementations

- [ ] Implement copyTexImage2D
- [ ] Implement copyTexSubImage2D
- [ ] Implement detachShader
- [ ] Implement finish
- [ ] Implement flush 
- [ ] Implement framebufferRenderbuffer
- [ ] Implement framebufferTexture2D
- [ ] Implement generateMipmap
- [ ] Implement getActiveAttrib
- [ ] Implement getActiveUniform
- [ ] Implement getAttachedShaders
- [ ] Implement getFramebufferAttachmentParameter
- [ ] Implement getProgramInfoLog
- [ ] Implement getRenderbufferParameter
- [ ] Implement getTexParameter
- [ ] Implement getShaderPrecisionFormat
- [ ] Implement getUniform
- [ ] Implement getVertexAttrib
- [ ] Implement getVertexAttribOffset
- [ ] Implement isBuffer
- [ ] Implement isEnabled
- [ ] Implement isFramebuffer
- [ ] Implement isRenderBuffer
- [ ] Implement isShader
- [ ] Implement isTexture
- [ ] Implement readPixels
- [ ] Implement renderbufferStorage
- [ ] Implement sampleCoverage
- [ ] Implement stencilFunc
- [ ] Implement stencilFuncSeparate
- [ ] Implement stencilMask
- [ ] Implement stencilMaskSeparate
- [ ] Implement stencilOp
- [ ] Implement stencilOpSeparate
- [ ] Implement texSubImage2D
- [ ] Implement uniform1i
- [ ] Implement uniform1iv
- [ ] Implement uniform2f
- [ ] Implement uniform2fv
- [ ] Implement uniform2i
- [ ] Implement uniform2iv
- [ ] Implement uniform3f
- [ ] Implement uniform3fv
- [ ] Implement uniform3i
- [ ] Implement uniform3iv
- [ ] Implement uniform4i
- [ ] Implement uniform4iv
- [ ] Implement uniformMatrix2fv
- [ ] Implement uniformMatrix3fv
- [ ] Implement uniformMatrix4fv
- [ ] Implement validateProgram

## Other pending things

- [ ] Stop re-exporting `WebGLCommand` as `CanvasWebGLMessage`.
- [ ] Update our angle dependency
- [ ] Update our interpretation of the spec to match other browser engines (#8753)
- [ ] Re-check our validations when there are multiple `WebGLRenderingContext`s in the same page.

**Comment by emilio** [comment]
cc @dmarcos

**Comment by ConnorGBrewster** [comment]
I will be working on implementing generateMipmap

**Comment by ConnorGBrewster** [comment]
It looks like `generateMipmap` will require significant additions to `WebGLTexture`. Mainly, to check the requirements for the texture before generating mipmaps, there needs to be a way to get info about the texture such as width and height. It looks like Gecko has a `ImageInfo` class. Should I implement it similar to how Gecko has it implemented?

**Comment by emilio** [comment]
@ConnorGBrewster I opened https://github.com/servo/servo/issues/10226, let's discuss there :)

**Comment by saurvs** [comment]
I'd like to work on `getActiveUniform`

**Comment by emilio** [comment]
@saurvs I opened https://github.com/servo/servo/issues/10397 for you, feel free to ask any question you might have there :)

**Comment by autrilla** [comment]
I'd like to work on all of the remaining uniform methods, if that's okay

**Comment by emilio** [comment]
@autrilla They're yours! I've opened https://github.com/servo/servo/issues/10417 to keep track of them, feel free to leave any questions there :)

**Comment by KiChjang** [comment]
I'm looking at the stencil* functions.

**Comment by danlrobertson** [comment]
I'm taking a crack at `copyTex*` and `texSubImage2D`

**Comment by DDEFISHER** [comment]
Attempting 
```
Implement isShader
Implement isTexture
```

**Comment by daoshengmu** [comment]
I would like to help ```texSubImage2D```

**Comment by emilio** [comment]
@daoshengmu: sounds great!

@danlrobertson, are you still working on `texSubImage2D`?

**Comment by daoshengmu** [comment]
@danlrobertson Sorry for I didn't notice you are working on ```texSubImage2D```. I just want to help some implementation of WebGL. If you are still working on it, I can pick ```copyTexImage2D``` and ```copyTexSubImage2D``` @emilio

**Comment by danlrobertson** [comment]
@daoshengmu No problem! It's totally okay! It's my bad for taking so long to get a PR in, but alas life happens :smile:...

Are you okay with taking `texSubImage2D`? I already [implemented the necesary components](https://github.com/servo/webrender_traits/commit/67bcaeebf19bc6aab83bef817b8a24ea02cefaa5) in [wr_traits](https://github.com/servo/webrender_traits). I should have a PR in shortly for `copyTex*`, but I actually hadn't started on `texSubImage2D`. If you want `texSubImage2D`, go for it! I have no particular attachment to it. Just wanted to learn a bit about webgl code...

**Comment by daoshengmu** [comment]
@danlrobertson Sure. I will take ```texSubImage2D```. Thanks! 😄

**Comment by DDEFISHER** [comment]
If it's okay I am going to work on
` Implement isFramebuffer
Implement isRenderBuffer`

**Comment by ConnorGBrewster** [comment]
@DDEFISHER go for it! Mind opening an issue for those so I can assign you there?

**Comment by DDEFISHER** [comment]
I am going to also work on `isBuffer` also since it is similar to the other 2

**Comment by jdm** [comment]
Separate issues for individual APIs are E-easy material; not this one.

**Comment by ofekd** [comment]
Can anyone point to an E-Easy(ish) implementation I can work on? Thanks :)

**Comment by jdm** [comment]
@ofekd `isEnabled` might be a good choice, since `enable` and `disable` are already implemented!

**Comment by ofekd** [comment]
@jdm I'll take it

**Comment by anholt** [comment]
@ofekd isEnabled might be tricky as a new contributor, because you need to change things across modules.  Some of the testcases in `webgl-specific.html`, like the blending func or stencil func ones, should be really good starting points. `invalid-passed-params.html` likely also has good easy tasks.

**Comment by ofekd** [comment]
@anholt As long as it's not significantly complicated I don't mind having to work some more. I didn't start working on this yet, but it looks like I need to change:

```
webrender_traits/src/webgl.rs
servo/components/script/dom/webglrenderingcontext.rs
servo/components/script/dom/webidls/WebGLRenderingContext.webidl
```
Unless it somehow hinders other efforts, I would continue working on `isEnabled`

**Comment by MortimerGoro** [comment]
I'll be working on implementing validateProgram and getProgramInfoLog

**Comment by MortimerGoro** [comment]
I'll be working at uniformMatrix2fv, uniformMatrix3fv, uniformMatrix4fv and framebufferRenderbuffer, framebufferTexture2D, renderbufferStorage. 

I'm going to run more demanding webgl demos and measure perf on servo and I need those functions ;)

**Comment by anholt** [comment]
@MortimerGoro I've been working on FBO support (see a couple of recent merges, and https://github.com/anholt/servo/tree/webgl-fbo).  I also put together https://github.com/anholt/servo/tree/webgl-uniform-matrix-v for uniformmatrix, but the testing needs to get debugged.

**Comment by MortimerGoro** [comment]
@anholt awesome! do you need any help with the uniformmatrix testing?

**Comment by anholt** [comment]
@MortimerGoro just figuring out what's going on with the unreliable results.

**Comment by anholt** [comment]
I've opened #13639 for tracking FBO support.  Want to add that to framebufferRenderbuffer/framebufferTexture2D?

**Comment by jdm** [comment]
@shravan-achar might be interested in working on the remaining ones here.

**Comment by anholt** [comment]
It looks like misisng `toDataURL()` for WebGL is the cause of a whole lot of remaining testcase issues (like `asin_001_to_006.html`)

**Comment by nox** [comment]
Only 5 missing APIs now.

**Comment by marmistrz** [comment]
me, @taki-jaro, @mrowqa and @xanewok will work on this issue as a student project
cc @KiChjang

**Comment by mkollaro** [comment]
I plan to attempt glGetTexParameter.

**Comment by gootorov** [comment]
Working on `getFramebufferAttachmentParameter`.

**Comment by brainlessdeveloper** [comment]
I'd like to do `getRenderbufferParameter`

**Comment by atouchet** [comment]
This issue no longer seems to be keeping a record of edits anymore for some reason.
