### ISSUE TITLE
History API metabug

### ISSUE THREAD

**Issue by ConnorGBrewster** [servo/servo#10992]
This issue will keep track of everything needed to fully implement the History API

The `History` interface:
 - [ ] `ScrollRestoration` enum and attribute
 - [ ] `length` attribute
 - [ ] `go([ delta ])` method
 - [ ] `back()` method (#5670 #10956)
 - [ ] `forward()` method (#5670 #10956)
 - [ ] `pushState(data, title [, url ])` method
 - [ ] `replaceState(data, title [, url ])` method
 - [ ] traverse the history by a delta

Spec: https://html.spec.whatwg.org/multipage/browsers.html#the-history-interface

Task Source and Events
 - [ ] Fully implement `HistoryTraversalTaskSource`
 - [ ] `PopStateEvent`
 - [ ] `HashChangeEvent`
 - [ ] `PageTransitionEvent`

Specs: 
https://html.spec.whatwg.org/multipage/browsers.html#the-popstateevent-interface 
https://html.spec.whatwg.org/multipage/browsers.html#hashchangeevent 
https://html.spec.whatwg.org/multipage/browsers.html#pagetransitionevent

**Comment by ConnorGBrewster** [comment]
The `popState` and `replaceState` both take title as an argument, and this is stored in the session history. According to the spec https://html.spec.whatwg.org/multipage/browsers.html#dom-history-pushstate, it looks like we can decide whether or not the title shown in the UI will change to match the one from the active session entry. Neither Safari, Firefox, or Chrome update the title to reflect the title stored in the active session history entry. I assume we would follow this behavior, but I wanted to double check.

cc @jdm

**Comment by jdm** [comment]
I don't see a reason to deviate from that.

**Comment by ConnorGBrewster** [comment]
@jdm we will need to add a way to interleave all of the navigation events. See https://html.spec.whatwg.org/multipage/browsers.html#joint-session-history. Would having an extra frame designated for this in the constellation work?

**Comment by ConnorGBrewster** [comment]
@jdm it looks like we will need to interleave navigation events from all browsing contexts for the [`joint session history`](https://html.spec.whatwg.org/multipage/browsers.html#joint-session-history). This means that `Frame` itself will not be enough. I am trying to think of a way to store navigation events as they occur, do you have any ideas?

**Comment by jdm** [comment]
The constellation is the natural place to coordinate the concepts of the joint session history and the session history event loop. I'm not sure what storing navigation events entails, exactly.

**Comment by asajeffrey** [comment]
IRC conversation about session histories with multiple instances of the same pipeline id: http://logs.glob.uno/?c=mozilla%23servo&s=24+Feb+2017&e=24+Feb+2017#c619161

TL;DR: If you have document A which pushStates to B then again to C, then their shared Document is discarded, then the history is traversed to B, what happens? Our read of the spec is that A, B and C should all be reloaded to the same fresh document. This means that any session history entries with the same pipeline id must be contiguous.
