### ISSUE TITLE
Implement File API and related support

### ISSUE THREAD

**Issue by izgzhen** [servo/servo#11131]
This is a meta-issue, covered by [2016 GSoC project: File Support](https://github.com/izgzhen/gsoc-file-support), and assigned to @izgzhen.

Most of related open issues and PRs will be tracked in the link above (but I will try to mention this meta-issue as long as possible). And more information to be found in the repo above as well.

**Comment by izgzhen** [comment]
What is left undone as I accounted:

+ [ ] ArrayBuffer/ArrayBufferView support
+ [ ] Blob URL fragment identifier implementation
+ [ ] `URL.createFor` implementation

**Comment by nox** [comment]
These are not things specific to the File API, so I think we can close this meta issue.
