### ISSUE TITLE
Build geckolib with a stable Rust compiler

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#11815]
Stylo wants to eventually switch to stable Rust. This is a meta-issue to track tasks needed.

* [x] https://github.com/servo/servo/issues/11806
  * [x] https://github.com/servo/servo/pull/11945
* [x] https://github.com/servo/servo/pull/11816
* [x] <s>https://github.com/rust-lang/rust/issues/24263</s> https://github.com/servo/servo/pull/11884
* [x] https://github.com/servo/servo/pull/11827
* [x] <s>https://github.com/rust-lang/rust/issues/27708</s> https://github.com/servo/servo/pull/11835
* [x] https://github.com/servo/servo/pull/12263

**Comment by SimonSapin** [comment]
@bholley @heycam @emilio With the `style` crate almost there, the nest step is `ports/geckolib/gecko_bindings` which uses:

```
#![feature(const_fn)]
#![feature(concat_idents)]
#![feature(type_macros)]
```

then `ports/geckolib`:

```
#![feature(as_unsafe_cell)]
#![feature(box_syntax)]
#![feature(custom_attribute)]
#![feature(custom_derive)]
#![feature(plugin)]

#![plugin(heapsize_plugin)]
#![plugin(plugins)]
```

**Comment by SimonSapin** [comment]
https://github.com/servo/servo/pull/11816 now brings the above down to `const_fn` and `as_unsafe_cell`. (In addition to `discriminant_value` in the `style` crate.)
