### ISSUE TITLE
Implement JS fetch API

### ISSUE THREAD

**Issue by jdm** [servo/servo#11894]
This issue is tracking the implementation of the [JS fetch API](https://fetch.spec.whatwg.org/#fetch-api) following the [project plan](https://github.com/servo/servo/wiki/Summer-of-Code-2016:-Fetch-API). This is assigned to our RGSoC team, so please talk with me before starting to work on any part of it.

**Comment by fitzgen** [comment]
cc myself

**Comment by jdm** [comment]
Things to be aware of when starting this project:
* I expect the vast majority of code changes to take place in `components/script/dom/` - this is the code that's responsible for implementing the APIs that websites make use of, as well as exposing them to the JS environment
* in particular, each new interface that needs to be implemented (Request, Response, and Headers) will need to follow the steps for [creating a new interface](http://doc.servo.org/script/dom/index.html#adding-a-new-dom-interface)
* there are already tests for the missing interfaces, which can be run via `./mach test-wpt tests/wpt/web-platform-tests/fetch/api/request/` (similarly for `fetch/api/response/` and `fetch/api/headers/`) - you can learn more about the testing infrastructure in [our in-tree documentation](https://github.com/servo/servo/blob/master/tests/wpt/README.md#running-the-tests) and the [testharness documentation](http://testthewebforward.org/docs/testharness-library.html) 
* we will need to modify [include.ini](https://dxr.mozilla.org/servo/source/tests/wpt/include.ini) to start running the tests automatically on our [automated testing machines](http://build.servo.org/waterfall)
* the majority of files in `components/script/dom/` correspond to similarly-named interfaces defined in [WebIDL](http://mcc.id.au/2013/lca-webidl/) files in `components/script/dom/webidls/` - when confused about something, look for examples of other interfaces and how they relate to the Rust implementation in the corresponding source files
* [our documentation](http://doc.servo.org/script/dom/index.html) attempts to explain the complexities of exposing Rust code via JavaScript APIs; it is entirely likely that large parts of those explanations will be confusing as you're starting out, but keep in mind that documentation exists and please make suggestions about ways it could be improved :)

**Comment by jeenalee** [comment]
cc'ing myself

**Comment by jeenalee** [comment]
So far, the Headers and Request APIs have been mostly implemented. Some web platform tests for these APIs fail:
- `fetch/api/headers`: 
    - `FAIL`: 15 subtests
      * [ ] 13 are related to missing OpenEndedDictionary (#13144)  
      * [ ] 2 are blocked by external (#13004)
    - `TIMEOUT`: 1 test
      * [ ] `fetch/api/headers/headers-idl.html`  

- `fetch/api/request`:
    - `FAIL`: 11 subtests
       * [ ] 2 are related to missing OpenEndedDictionary (#13144)
       * [ ] 1 is directly related to Promise (#4282)
       * [ ] 6 are related to missing Body implementation which is blocked by Promise (#4282)
       * [ ] 1 is related to referrer not being properly parsed, i.e. `about:client` becomes `client`. `RequestInfo` (which is used as an input for constructing `Request`) will have a referrer `Client` when `about:client` is given. This results in `Request` with a referrer `client` when it should be `about:client`. Could this be an error in how input for request is created?
       * [ ] 1 is related to referrer and referrer policy not being properly saved in request like above

    - `TIMEOUT`: 4 tests
      * [ ] `fetch/api/request/request-init-003.sub.html`
      * [ ] `fetch/api/request/request-clone.sub.html`
      * [ ] `fetch/api/request/request-idl.html`
      * [ ] `fetch/api/request/request-disturbed.html`

**Comment by jeenalee** [comment]
**Updated summary of failing tests**
- **`fetch/api/basic/`**
  - not summarized yet!

- **`fetch/api/cors/`**
  - currently disabled
  - intermittently fails

- **`fetch/api/credentials/`**
  - authorization should be managed properly
 	- `authentication-basic-worker.html`
	- `authentication-basic.html`
  - cookies should be managed properly
    - `cookies-worker.html`
    - `cookies.html`

- **`fetch/api/headers/`**
  - only `headers-idl.html` isn't passing

- **`fetch/api/policies/`**
  - tests related to csp block
    - `csp-blocked.html`
    - `csp-blocked-worker.html`
  - when fetching request's referrer is empty, it should be noted in fetched response's headers
    - `referrer-no-referrer-worker.html`
    - `referrer-no-referrer.html`
  - fetching request's origin should be noted in fetched response's headers
    - `referrer-origin-when-cross-origin-worker.html`
    - `referrer-origin-when-cross-origin.html`
    - `referrer-origin-worker.html`
    - `referrer-origin.html`
  - Request's referrer should be the full url of current document/worker
    - `referrer-unsafe-url.html`
    - `referrer-unsafe-url-worker.html`

- **`fetch/api/redirect/`**
  - currently disabled
  - intermittently fails

- **`fetch/api/request/`**
  - `clone()` should return a request that is identical to the original request
    - `request-clone.sub.html`
  - `request-cache.html` is disabled (#13458)
  - body mixin methods should be implemented
    - `request-consume-empty.html`
    - `request-consume.html`
  - if a request is disturbed, various things should/should not happen
    - `request-disturbed.html`
  - request header should be created with various objects (JS Object, array, headers) and get information from the body if none is given
    - `request-headers.html`
    - `request-error.html`
  - referrer should be properly parsed, i.e. currently, about:client becomes client. RequestInfo (which is used as an input for constructing Request) will have a referrer Client when about:client is given. This results in Request with a referrer client when it should be about:client. Could this be an error in how input for request is created?
    - `request-init-001.sub.html`
  - request's body should be initialized in various ways
    - `request-init-002.html`
  - request should be initialized correctly
    - `request-init-003.sub.html`

- **`fetch/api/response/`**
  - static method `error()` should return correct response
    - `response-static-error.html`
  - `Stream`/`ReadableStream` should be supported
    - `response-cancel-stream.html`
    - `response-consume-stream.html`
  - after response's body is locked, promise should reject
    - `response-stream-disturbed-*.html`
  - response's body should be initialized in various ways
    - `response-init-002.html`
  - default Body should be given in response
    - `response-init-001.html`
  - body mixin methods should be implemented
    - `response-consume-empty.html`
    - `response-consume.html`
  - `clone()` should return a response that is identical to the original response
    - `response-clone.html`

**Comment by jdm** [comment]
I think filing specific issues for anything that isn't working will be more useful at this point.
