### ISSUE TITLE
Pending work for transitions/animations

### ISSUE THREAD

**Issue by emilio** [servo/servo#11916]
Assuming #11766 lands, this would be the pending work left to do for animations and transitions. I'm planning in doing it, though if someone wants to help that would be appreciated.
Pending work for animations/transitions:
- [x] Support more animated properties: These are marked with a FIXME in
   `style/properties/longhands/`. These are easy, it's just a matter of
   following the transitions spec and implement the interpolation
   appropriately.
- [x] Support the `animation` shorthand. This should be easy.
- [x] Scan for all the animatable properties of all the keyframes, not just the
   first one. This is not specified, but all other browsers seem to do this.
- [ ] Apply all the previous keyframes' declarations when computed the style. We
   only apply the previous keyframe, and interpolate it with the target one.
   We should do all the chain, maybe storing the current animation's computed
   style in the state to be a bit more efficient? We should be able to do that
   while the animation is ticking, but not on style because we don't have
   write access to the hashmap (well, we _could_, but it could become really
   slow).
- [ ] Don't remove animations from the layout hashmap when they get expired. This
   might cause them to get retriggered on the next restyle, which is wrong.
- [ ] Implement animation-fill-mode. This will allow us to test the animation
   code.
- [ ] Fix the parsing of the `steps()` function, which was wrong.
- [x] Figure out how to test all this stuff (https://github.com/servo/servo/issues/12120).
- [x] Split the SharedLayoutContext in two different pieces, one cloneable per
   thread, and one inmutable as it's today. This will allow us to take rid of
   the Mutex in `new_animations_sender`.
- [x] File a spec bug about why Gecko doesn't seem to parse
   `@keyframes "bar" {}`, or fix it in gecko directly.
- [ ] Probably a few more things.

**Comment by emilio** [comment]
cc @SimonSapin

**Comment by emilio** [comment]
@SimonSapin: The string part for the animation name seems to have been added lately, so it's just no-one else has implemented it yet :)

**Comment by mrobinson** [comment]
@emilio Can you confirm whether or not parsing of `steps()` has been fixed? I think if it has, we can close this issue in favor of #26328.

**Comment by emilio** [comment]
Yeah, I believe steps parsing should be fine now. Seems fine to close as a dupe. Thanks!
