### ISSUE TITLE
Android Nightly blockers

### ISSUE THREAD

**Issue by larsbergstrom** [servo/servo#12130]
The below bugs are the ones that are required to at least have a first linked nightly build of Servo on Android. Note that this build would _not_ use browser.html, but would simply provide Open With support.
- [ ] #7211 Font load/enumeration is too slow on Android
- [ ] #12127 No keyboard support
- [x] #12129 Android should unpack `resources` folder on first run

**Comment by mhsjlw** [comment]
Progress on Android? Or is Windows currently on a higher priority?

**Comment by jdm** [comment]
Windows is higher priority.

**Comment by jawz101** [comment]
https://en.m.wikipedia.org/wiki/Usage_share_of_web_browsers#Crossover_to_smartphones_having_majority_share

Let's not be behind the times.  Just sayin'

**Comment by meecoffee** [comment]
any new process?
http://gs.statcounter.com/os-market-share
android now more often than windows
mozilla guys

**Comment by jdm** [comment]
We'll announce when there are significant improvements.

**Comment by surajmandalcell** [comment]
Any updates?

**Comment by jdm** [comment]
See the previous comment.

**Comment by surajmandalcell** [comment]
any updates (*again*)?

**Comment by mhsjlw** [comment]
He already said there will be an announcement, asking every 4 days isn't going to do much

**Comment by acaciosc** [comment]
What about asking every 10 days, then? Ok, really, is there an estimate, like "within 1 year there will be a build available for Android"?

**Comment by VictorBlomberg** [comment]
I think we should just wait. We are all very excited, but I believe we have to respect the decisions made by the very talented and hard working servo developers. When there are updates, I'm sure we will be told. Until then, help where help is needed, but don't be a hindrance.

**Comment by jdm** [comment]
Unfortunately there is no estimate, and the only work being done on the Android port right now is in service of making demos like https://blog.mozvr.com/webvr-daydream-support-lands-in-servo/ work better.

**Comment by meecoffee** [comment]
too long time android version is a joke

**Comment by LifeIsStrange** [comment]
@meecoffee you could Help instead of flaming. They obviously know that android is a priority because nowadays people surf more on the Web with smartphones/tablets than on PC. 
But they have legitimate others priorities, firstly servo isn't ready, it's a pre alpha. 
Secondly they are busy working on stylo and webrender (the new css engine and gpu renderer) which will impact real world people because it will be implemented in Firefox too. 
You will soon be able to use them on firefox nightly and it should make them far more compete with chrome, especially on mutlicore machines.

That said I would like to Emphazise android development, not by spamming but by arguing :
That servo should be usable far sooner on android than on others platform because I believe from my poor Web knowledge, that websites for smartphones because of screenspace, input, power and bandwith limitations, are far simpler.
So I believe that you need less specs support and Debbuging between features interactions on Android websites. 
Sorry for my bad english.

**Comment by yellowfour** [comment]
I'd prefer prioritize Android because there is still no great page rendering engine since Presto has been retired by Opera. I don't get why Gecko and WebKit/Blink still has no clue how to properly auto zoom pages and get the right font sizes. Will Servo on Android be able to offer better, ergonomic, optimal text and page widths?

**Comment by lygstate** [comment]
What's going on with Android support?

**Comment by jdm** [comment]
The Android port is receiving more attention because of Servo's new prioritization of mixed reality content.

**Comment by meecoffee** [comment]
Android nightly APK download link?

**Comment by atouchet** [comment]
Should this be added to the [Android MVP project](https://github.com/servo/servo/projects/3)?

**Comment by paulrouget** [comment]
Related:

- #20855
- #20912

**Comment by LifeIsStrange** [comment]
Now that the situation massively improved @paulrouget could we have a nightly apk ?

Even if not everything is perfect, please !

**Comment by jdm** [comment]
https://download.servo.org/nightly/android/servo-latest.apk is where the nightly builds go. There should be a build that includes #21308 at that link in 4 hours. If nobody reports any showstopper problems, we'll update https://github.com/servo/download.servo.org/blob/master/index.html to include the link.

**Comment by paulrouget** [comment]
It appears to work fine.

**Comment by LifeIsStrange** [comment]
Yes, the browser UI just works !
Servo is incredibly fast, some pages not in cache load instantly !!
But there is a small number of issues that block servo from being casually used.
That is on my oneplus one :

Some <h2> have some letters that are invisible (but spaced), even on the default page.

Websites effectively fit the size of my screen but at least text feels often a little bit too small. 

Clicking on links on duckduckgo sometimes is missed because the police is too small. 
And Clicking on the first links sometimes load the second link even if my finger is clearly on the first link. 

Websites with imgs often flicker quickly on the first load, is fixed when scrolling. 

Finally, scrolling was mostly smooth exept at some rare zones where it teleported my view. 

But else I have to say that the rendering was smooth and the css excellent. 

Crashes :
Stopping a website of loading sometimes crash the browser.


I think that you should not publish the Android apk on your website until those issues are fixed, but I have the naïve feeling that those issues can be fixed in less than a month as exept those corner cases, everything is working !

**Comment by lygstate** [comment]
works， Chinese fonts doesn't show properly

**Comment by paulrouget** [comment]
@LifeIsStrange thank you for testing. Could you file issues for these bugs?

**Comment by LifeIsStrange** [comment]
@paulrouget of course, but I will do it in the upcoming days sorry.

**Comment by atouchet** [comment]
I still have not been able to run the Android version without it crashing: #21317

**Comment by mrobinson** [comment]
We have Android nightlies now so we can close this. The blocker issues are still a problem though.
