### ISSUE TITLE
intermittent solutions meta bug

### ISSUE THREAD

**Issue by metajack** [servo/servo#12424]
@nox wrote a nice [script](https://gist.github.com/nox/d2eadf509a6898c1f43c6f3e1413666f) to count cross references for intermittent bugs which gives us [this data](https://irccloud.mozilla.com/pastebin/7qtCu5cS). Graphing this gives us:

![chrome_2016-07-12_16-55-04](https://cloud.githubusercontent.com/assets/28357/16786363/717cd2fe-4851-11e6-8615-a6683877432b.png)

The inflection point seems to be around 10, so I think we should try and deal with anything that affected more than 10 PRs. Note that some of these tests are currently disabled.

Work should happen on individual bugs, but this list will track the biggest offenders in one place:
- [x] #7791 (reenabled by #18681)
- [ ] #8127 (currently disabled)
- [x] #8311 (reenabled by #12800)
- [x] #8769 (fixed by #10082, reenabled by #12796)
- [x] #8815
- [x] #9012
- [ ] #9033 (currently disabled)
- [ ] #9148 (currently disabled)
- [ ] #9163 (currently disabled)
- [x] #9278 
- [x] #10251
- [x] #10457
- [ ] #10473 (currently disabled)
- [ ] #10760 (currently disabled)
- [ ] #11100 (currently disabled on macOS)
- [ ] #11561 <strike>(fixed by #12543)</strike>
- [ ] #11574 <strike>(fixed by #12543)</strike>
- [x] #11703 (fixed by #12404)

This also seems to imply we should immediately disable these: #9012

**Comment by emilio** [comment]
I closed #10251, since it's appveyor related and we no longer gate on it, thanks for putting this up together! :)

**Comment by nox** [comment]
You marked #8815 as disabled but @Ms2ger closed that ticket so I'm confused.

**Comment by lumiscosity** [comment]
All of these have been fixed now (🎉), and for new tests this has been superseded by #46859.
