### ISSUE TITLE
Keep track of Web Bluetooth efforts

### ISSUE THREAD

**Issue by beaufortfrancois** [servo/servo#12585]
@dati91 Is there an easy way to keep track of all progress you're making to Web Bluetooth in Servo?

**Comment by dati91** [comment]
We made a [website](http://szeged.github.io/servo/), which is the most up-to-date thing right now about our progress.
Maybe i can link all our (current and future) PR-s here, if it helps.
And if you want to i can collect our short- and long-term goals as well.

**Comment by beaufortfrancois** [comment]
That would be awesome!

**Comment by dati91** [comment]
**Goals**
- [ ] Refactor tests (https://github.com/servo/servo/pull/12538)
- [ ] Implement basic Test API
- [ ] Refactor Device and BlurZ crates (too bluez specefic)
- [ ] Add android support
- [ ] Implement Promises in Servo
- [ ] Implement Event Handling in Servo
- [ ] Gatt notifications

**Comment by KiChjang** [comment]
@beaufortfrancois This looks like it's a good tracking issue for all the bluetooth implementation.

**Comment by KiChjang** [comment]
Also see #9392.

**Comment by jdm** [comment]
No need to track this any more.
