### ISSUE TITLE
Update serde to 0.8

### ISSUE THREAD

**Issue by nox** [servo/servo#12659]
* [x] [app_units](https://github.com/servo/app_units/pull/20)
* [x] [azure](https://github.com/servo/rust-azure/pull/240)
* [x] [bincode](https://github.com/TyOverby/bincode/pull/84)
* [x] [cocoa](https://github.com/servo/cocoa-rs/pull/141)
* [x] [content-blocker](https://github.com/servo/content-blocker/pull/8)
* [x] [cookie](https://github.com/alexcrichton/cookie-rs/pull/52)
* [x] [core-graphics](https://github.com/servo/core-graphics-rs/pull/53)
* [x] [core-text](https://github.com/servo/core-text-rs/pull/51)
* [x] [cssparser](https://github.com/servo/rust-cssparser/pull/106)
* [x] [euclid](https://github.com/servo/euclid/pull/150)
* [x] [hyper](https://github.com/hyperium/hyper/pull/878) (also https://github.com/hyperium/hyper/pull/879) *(switching to hyper_serde instead)*
* [x] [io-surface](https://github.com/servo/io-surface-rs/pull/53)
* [x] [ipc-channel](https://github.com/servo/ipc-channel/pull/91)
* [x] [layers](https://github.com/servo/rust-layers/pull/239)
* [x] [mime](https://github.com/hyperium/mime.rs/pull/43)
* [x] [offscreen_gl_context](https://github.com/emilio/rust-offscreen-rendering-context/pull/60)
* [x] [servo-glutin](https://github.com/servo/glutin/pull/103)
* [x] [servo-skia](https://github.com/servo/skia/pull/113)
* [x] [string_cache](https://github.com/servo/string-cache/pull/166)
* [x] [url](https://github.com/servo/rust-url/pull/216)
* [x] [uuid](https://github.com/rust-lang-nursery/uuid/pull/69)
* [ ] [webrender](https://github.com/servo/webrender/pull/342)
* [x] [webrender_traits](https://github.com/servo/webrender_traits/pull/71)
