### ISSUE TITLE
Upgrade regex dependency to 0.2

### ISSUE THREAD

**Issue by upsuper** [servo/servo#14957]
libbindgen recently upgraded its regex dependency to 0.2 in servo/rust-bindgen#385, and there are new features I want to use after that change. But to keep Servo's CI happy, we need to keep only one version of regex among the whole dependency tree, so I'm going to upgrade regex in all the dependencies use it, and then have a single pr to bump in-tree dependencies.

Dependencies which use regex:
- [x] caseless: SimonSapin/rust-caseless#3
- [x] clippy / clippy_lint: Manishearth/rust-clippy#1437
- [x] content-blocker: servo/content-blocker#9
- [x] env_logger: rust-lang-nursery/log#98
- [x] libbindgen: servo/rust-bindgen#385
- [x] webdriver: mozilla/webdriver-rust#61

**Comment by jdm** [comment]
Keep in mind that there is an exclusion list for the duplicate crate error, if you're blocked on this.

**Comment by upsuper** [comment]
I don't think we want to exclude regex, since it's not a small crate. I'm not really blocked on this. It feels to me I will eventually need it, so I try to push it to happen sooner rather than later. But it isn't a blocker at this moment.

**Comment by upsuper** [comment]
Looks like the upgrade is eventually done in #15042. Thanks @Ms2ger.
