### ISSUE TITLE
Implement parsing and serialization of grid properties

### ISSUE THREAD

**Issue by upsuper** [servo/servo#15307]
Spec: https://drafts.csswg.org/css-grid/

Grid properties have relatively complicated syntax, so it might not be a very easy one.

 - [x] servo/servo#15310
 - [x] servo/servo#15311
 - [x] servo/servo#15312
 - [x] servo/servo#15313
 - [x] servo/servo#16079

**Comment by Wafflespeanut** [comment]
Yeah, it's in my queue. I'm supposed to finish those by the start of this year :stuck_out_tongue:

**Comment by Wafflespeanut** [comment]
Making this a tracking bug.

 - [ ] `grid-{row,column}-gap` - #15310
 - [ ] `grid-template-{rows, columns}` - #15311
 - [ ] `grid-auto-{columns, rows}` - #15312
 - [ ] `grid-auto-flow` - #15313

**Comment by Manishearth** [comment]
We seem to handle everything except `grid` and `grid-template`, which are both shorthands.

@wafflespeanut @canaltinova do you have time to fix those? if not I'll just finish them up

**Comment by wafflespeanut** [comment]
I have a patch for `grid-template` (will open a PR today). I'm fine with working on `grid` if @canaltinova has other interesting stuff to work on :)

**Comment by Manishearth** [comment]
okay, thanks. Probably best if you do grid, since it's pretty straightforward once you have grid-template.
