### ISSUE TITLE
Update serde to 0.9

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#15325]
- [x] https://github.com/nox/hyper_serde/pull/7
- [x] https://github.com/rust-lang-nursery/uuid/pull/80
- [x] https://github.com/vvuk/dwrote-rs/pull/7
- [x] https://github.com/servo/app_units/pull/23
- [x] https://github.com/servo/euclid/pull/175
- [x] https://github.com/servo/core-graphics-rs/pull/69
- [x] https://github.com/servo/rust-cssparser/pull/114
- [x] https://github.com/nagisa/target_build_utils.rs/pull/2
- [x] https://github.com/MortimerGoro/rust-webvr/issues/3
- [x] https://github.com/emilio/rust-offscreen-rendering-context/pull/78
- [x] https://github.com/TyOverby/bincode/issues/106
- [x] https://github.com/servo/ipc-channel/pull/136
- [x] https://github.com/servo/string-cache/pull/182
- [x] https://github.com/servo/skia/pull/130
- [x] https://github.com/servo/rust-url/pull/274
- [x] https://github.com/servo/rust-azure/pull/259
- [x] https://github.com/servo/webrender/pull/857
- [x] https://github.com/servo/html5ever/pull/251
- [x] https://github.com/Ygg01/xml5ever/pull/27
- [x] https://github.com/nagisa/rust_libloading/issues/21
- [x] https://github.com/servo/core-text-rs/pull/56
- [x] https://github.com/servo/cocoa-rs/pull/156
- [x] https://github.com/servo/glutin/pull/116
- [ ] https://github.com/servo/servo/pull/15588

**Comment by SimonSapin** [comment]
https://github.com/servo/rust-url/pull/274 adds a new `url_serde` crate which uses 0.9. The `url` crate still has an optional feature that uses serde 0.8. If we make sure that feature is not enabled in a future version of Servo that uses 0.9, serde 0.8 should not be built by Cargo when building Servo, but I think it will still be included in `Cargo.lock` which will make our "no more than one version of the same crate" lint in `test-tidy` fail.

At some point we’ll have other reasons to make breaking changes to rust-url and will remove that optional feature at the same time. But I feel that updating serde alone is not enough of a reason to do that yet, since a breaking `url` version means a breaking version of `hyper` and likely other crates. This will be a pain to deal with, not only for us in Servo but for the Rust ecosystem in general. (The https://crates.io/crates/url/reverse_dependencies count is currently at 381.)

In the short term we can add `serde` to the lint’s exception list. It’d be better to rewrite the lint to be based on what’s actually compiled rather than what’s in `Cargo.lock`, but that likely requires cooperation from Cargo.

**Comment by nox** [comment]
@SimonSapin As long as the serde feature isn't used, AFAIK it shouldn't appear in Cargo.lock at all.

**Comment by SimonSapin** [comment]
For some reason I was convinced of the opposite but I just tried it and you’re right. Edited previous comment.

**Comment by SimonSapin** [comment]
Not including them might be a Cargo bug, depending on how you look at it: https://github.com/rust-lang/cargo/issues/3629

**Comment by nox** [comment]
dwrote has been forked to the Servo organisation, while waiting for a 0.2 version to be published.
