### ISSUE TITLE
Update serde to 1.0.0

### ISSUE THREAD

**Issue by nox** [servo/servo#16556]

**Comment by Eijebong** [comment]
Let's do this !

- [ ] https://github.com/servo/app_units
- [x] https://github.com/TyOverby/bincode/commit/251f77ecd36ba5399a1c281aaea0f94a28b66bdf
- [x] https://github.com/servo/core-graphics-rs/pull/84
- [ ] https://github.com/servo/rust-cssparser
- [ ] https://github.com/vvuk/dwrote-rs
- [ ] https://github.com/servo/euclid
- [ ] https://github.com/nox/hyper_serde
- [ ] https://github.com/servo/ipc-channel
- [ ] https://github.com/emilio/rust-offscreen-rendering-context
- [ ] https://github.com/MortimerGoro/rust-webvr
- [ ] https://github.com/nagisa/target_build_utils.rs (deprecated)
- [ ] https://github.com/servo/rust-url/pull/327
- [x] https://github.com/rust-lang-nursery/uuid/commit/6f3409a0c0c45eeb5bc6294f9fcacb6c77a6cab3
- [ ] https://github.com/servo/rust-azure
- [ ] https://github.com/servo/cocoa-rs
- [ ] https://github.com/servo/core-text-rs
- [ ] https://github.com/servo/webrender/tree/master/webrender_traits
- [ ] https://github.com/servo/webrender/tree/master/webrender
- [ ] https://github.com/servo/glutin
- [ ] https://github.com/nagisa/rust_libloading
- [ ] https://github.com/housleyjk/ws-rs
- [ ] https://github.com/servo/skia

**Comment by nox** [comment]
I don't remember if we properly removed serde from core-graphics and already used that in servo itself...

**Comment by nox** [comment]
[Seems like we did.](https://github.com/servo/servo/pull/16512)

**Comment by Eijebong** [comment]
I don't see serde here https://github.com/servo/core-graphics-rs/blob/master/Cargo.toml so i think you did

**Comment by nox** [comment]
You included bumps in all the PRs, which forbids us to make a PR on Servo to do a try run with `[replace]`s.

**Comment by Eijebong** [comment]
Oh :( I can remove all bumps if you want me to

**Comment by Eijebong** [comment]
I can do that ^^

**Comment by jdm** [comment]
ws-rs does not appear to be using serde: https://github.com/housleyjk/ws-rs/blob/master/Cargo.toml

**Comment by Eijebong** [comment]
I think this can be closed now
