### ISSUE TITLE
Repo permissions audit

### ISSUE THREAD

**Issue by edunham** [servo/servo#17626]
- [ ] obtain list of all repos in the org (api)
- [ ] determine which repos Homu is trying to manage
  - [ ] determine which of those Homu is working correctly on
    - [ ] enable branch protection on those
  - [ ] Tracking issues to fix Homu where it's broken
- [ ] Document which if any repos Homu is not supposed to run on
  - [ ] Identify and remove any abandoned or no longer needed repos

**Comment by edunham** [comment]
The Servo org has [127 repos including those which are forks](https://gist.github.com/a1b54e261b9a3827032730526af91e29), and [86 excluding forks](https://gist.github.com/b2f4c0f25631473cf647c2cf10deea56). 

[52 repos](https://gist.github.com/89ddfb9bc71910aca3e529a4bd61a15a) are configured for Travis operation [in Homu](https://github.com/servo/saltfs/blob/master/homu/files/cfg.toml#L79), and only servo/servo uses Buildbot.

**Comment by edunham** [comment]
Here is my checklist of all repos in the org that Homu should be working on. I will check the boxes as I check each repo's perms and Homu functionality. 

- [ ] angle                                                                     
- [ ] app_units                                                                 
- [ ] cgl-rs                                                                    
- [ ] cocoa-rs                                                                  
- [ ] core-foundation-rs                                                        
- [ ] core-graphics-rs                                                          
- [ ] core-text-rs                                                              
- [ ] devices                                                                   
- [ ] download.servo.org                                                        
- [ ] euclid                                                                    
- [ ] fontsan                                                                   
- [ ] futf                                                                      
- [ ] gaol                                                                      
- [ ] gleam                                                                     
- [ ] glutin                                                                    
- [ ] heapsize                                                                  
- [ ] highfive                                                                  
- [ ] homu                                                                      
- [ ] html5ever                                                                 
- [ ] io-surface-rs                                                             
- [ ] ipc-channel                                                               
- [ ] libexpat                                                                  
- [ ] libfontconfig                                                             
- [ ] libfreetype2                                                              
- [ ] mozjs                                                                     
- [ ] osmesa-src                                                                
- [ ] rust-azure                                                                
- [ ] rust-bindgen                                                              
- [ ] rust-cssparser                                                            
- [ ] rust-fnv                                                                  
- [ ] rust-fontconfig                                                           
- [ ] rust-freetype                                                             
- [ ] rust-glx                                                                  
- [ ] rust-harfbuzz                                                             
- [ ] rust-layers                                                               
- [ ] rust-mozjs                                                                
- [ ] rust-png                                                                  
- [ ] rust-quicksort                                                            
- [ ] rust-selectors                                                            
- [ ] rust-smallvec                                                             
- [ ] rust-stb-image                                                            
- [ ] rust-url                                                                  
- [ ] rust-websocket                                                            
- [ ] saltfs
- [X] servo                                                                    
- [ ] servo-starters                                                            
- [ ] skia                                                                      
- [ ] string-cache                                                              
- [ ] tendril                                                                   
- [ ] unicode-bidi                                                              
- [ ] unicode-script                                                            
- [ ] webrender                                                                 
- [ ] webrender_traits
