### ISSUE TITLE
Add tidy to support crates' CI

### ISSUE THREAD

**Issue by edunham** [servo/servo#17733]
Superseding https://github.com/servo/servo/issues/861

- [ ] set up CI to automatically deploy new tidy versions to pypi when the source is changed
- [ ] Update list of all support crates and add it here
- [ ] check whether tidy is run by their CI and add it if not

**Comment by edunham** [comment]
oops I already had this issue over in https://github.com/servo/servo/issues/10636. Duh.
