### ISSUE TITLE
CJK support

### ISSUE THREAD

**Issue by shinglyu** [servo/servo#18202]
This is a meta bug for CJK support. 

We need to be able to:
- [ ] Correctly handle encoding in HTML parsing (https://github.com/servo/servo/issues/6414)
- [ ] Display Unicode CJK text correctly (fail on MacOS https://github.com/servo/servo/issues/10045) 
- [ ] Display Non-Unicode CJK text correctly (https://github.com/servo/servo/issues/6167, also Big5 encoding text are not rendered correctly)
- [ ] Handle font family fallback for CJK (https://github.com/servo/servo/issues/17267)
- [ ] Handle CJK input methods (status unconfirmed)
- [ ] Handle CJK text editing in input tag/content editable (status unconfirmed)

**Comment by shinglyu** [comment]
@tigercosmos you might be interested in this?

**Comment by shinglyu** [comment]
Might be related: https://github.com/servo/servo/issues/4901

**Comment by tigercosmos** [comment]
@shinglyu Yep. As an Asian user, these issues mean a lot.  :D

**Comment by SimonSapin** [comment]
The rendering pipeline is fundamentally based on Unicode. Big5 and gb2312 are both character encodings that we map to Unicode during parsing, and so they fall under #6414. I assume by "non-Unicode" you mean "non-UTF encodings"?

**Comment by shinglyu** [comment]
@SimonSapin Thanks for the correction. I've update the original description.

**Comment by valerauko** [comment]
I'd be happy to help with any of these issues if someone was kind enough to help me get on board. Is there any work in progress related to these?

**Comment by jdm** [comment]
https://github.com/servo/servo/issues/6414 is the most recent work, so there is actually some prior art you can build off of.

**Comment by tigercosmos** [comment]
@CYBAI Maybe you will be interested in this?

**Comment by CYBAI** [comment]
Hi @tigercosmos 
@shinglyu did mention this issue to me before.
Just like what you said, as Asian user, I'm willing to help to fix some issues.
Maybe I'll focus on the `ServiceWorker` one I took first but we can discuss how and what we can do for this issue.

**Comment by tigercosmos** [comment]
@CYBAI  Great to see your enthusiasm :)
What is `ServiceWorker ` one?

**Comment by CYBAI** [comment]
I add the issue number in my previous comment.
Due to not related to this issue, I don't want to make it have a reference between these two issues :P

**Comment by tigercosmos** [comment]
@jonleighton  Did #20506 cover this?

**Comment by jonleighton** [comment]
@tigercosmos It improved the fallback situation, but I'm sure there are still edge cases and things to do. Still, lots of CJK stuff should now be rendering when it didn't previously.
