### ISSUE TITLE
Automate bidirectional syncing for web-platform-tests

### ISSUE THREAD

**Issue by jdm** [servo/servo#18749]
Syncing changes from upstream web-platform-tests to Servo:
* [x] https://github.com/servo/servo/pull/18726 (script to fetch all changes from upstream and open a PR)
* [x] https://github.com/servo/saltfs/pull/728 (scheduler to run the script every 24 hours)

Syncing changes from Servo to upstream web-platform-tests:
* [ ] review https://github.com/servo-automation/upstream-wpt-sync-webhook (webhook to push local changes upstream as soon as they are merged in servo/servo)
* [x] https://github.com/servo/saltfs/pull/733 (run a flask server as the webhook target)
* [x] https://github.com/tobie/ganesh/pull/10 (skip the upstream review requirement)
* [x] https://github.com/servo-automation/upstream-wpt-sync-webhook/issues/5 (upstream unchanged file moves correctly)
* [ ] https://github.com/servo-automation/upstream-wpt-sync-webhook/issues/6 (try uncommon cases)

**Comment by KiChjang** [comment]
When an open PR receives new changes, does the upstream-wpt-sync-webhook correctly handle force pushes, and do they count as changes?

**Comment by jdm** [comment]
Yes.

**Comment by jdm** [comment]
This has been enabled for more than a year.
