### ISSUE TITLE
Twitter compat issues

### ISSUE THREAD

**Issue by jdm** [servo/servo#18818]
Tracking issues that affect twitter.com in particular:
* [ ] https://github.com/servo/servo/issues/18299
* [ ] https://github.com/servo/servo/issues/18811
* [ ] https://github.com/servo/servo/issues/18812
* [ ] https://github.com/servo/servo/issues/18813
* [ ] https://github.com/servo/servo/issues/18814
* [ ] https://github.com/servo/servo/issues/18815
* [ ] https://github.com/servo/servo/issues/18816
* [ ] https://github.com/servo/servo/issues/18817
