### ISSUE TITLE
Facebook issues

### ISSUE THREAD

**Issue by jdm** [servo/servo#18835]
Tracking issues related to Facebook:
* [ ] https://github.com/servo/servo/issues/18830
* [ ] https://github.com/servo/servo/issues/18831
* [ ] https://github.com/servo/servo/issues/18824
* [ ] https://github.com/servo/servo/issues/18832
* [ ] https://github.com/servo/servo/issues/18833
