### ISSUE TITLE
Move CSS longhands outside of mako

### ISSUE THREAD

**Issue by emilio** [servo/servo#19015]
We use the mako template system to autogenerate code.

Ideally, we'd like to use a manifest and use Rust to generate it instead. For that, we need to move all the remaining CSS properties (most of them have been moved already) outside of Mako. That is the same as saying: We should make all those use `${helpers.predefined_type(..)}`.

This is mostly moving and cleaning up code in the same way as #19002 and #19005, but there are probably bugs along the way that may need fixing (like the calc() bug I added a test for in #19005).

If you want to help out with this, please comment on this issue or reach out on IRC (`#servo` in `irc.mozilla.org`) and we'll find one which is interesting to you.

Or, you can also file an issue and mention this one and I'll get it assigned to you.

Known properties still using mako:

 * In `text.mako.rs`:
   - [x] `text-overflow` (#19044)
   - [x] `text-decoration-line` (#19211)
 * In `inherited_text.mako.rs`:
   - [x] `text-align` (#19576)
   - [x] `-servo-text-decorations-in-effect` (#19757)
   - [x] `text-emphasis-style` (#19940)
   - [x] `text-emphasis-position` (#19961)
 * In `inherited_svg.mako.rs`:
   - [x] `paint-order` (#19736)
   - [x] `-moz-context-properties` (#19742)
 * In `box.mako.rs`:
   - [x] `display` (#19658)
   - [x] `-servo-display-for-hypothetical-box` (#19697)
   - [x] `overflow-y` (#19183)
   - [ ] `transform` (I think @Manishearth was doing stuff with this one)
   - [x] `scroll-snap-type-y` (#19018)
   - [x] `contain` (#19656)
   - [x] `will-change` (#19582)
   - [x] `touch-action` (#19645)
 * In `list.mako.rs`:
   - [x] `list-style-type` (#19629)
   - [x] `list-style-image` (#19557)
   - [x] `quotes` (#19556)
 * In `inherited_box.mako.rs`:
   - [x] `image-orientation` (#19765)
 * In `ui.mako.rs`:
   - [x] `-moz-force-broken-image-icon` (#19279)
 * In `pointing.mako.rs`:
   - [x] `cursor` (#19775)
 * In `outline.mako.rs`:
   - [x] `outline-style` (#19546)
 * In `border.mako.rs`:
   - [x] `-moz-border-*-colors` (#19671)
   - [x] `border-image-repeat` (#19142, presumably a great first bug, should be mostly like #19002)
 * In `position.mako.rs`:
   - [x] `grid-auto-flow` (#19375)
   - [x] `grid-template-areas` (#19409)
 * In `table.mako.rs`:
   - [x] `-x-span` (#19036)
 * In `svg.mako.rs`:
   - [x] `mask-size` (#19467)
 * In `counters.mako.rs`:
   - [x] `content` (#19936)
   - [x] `counter-increment` (#19529)
   - [x] `counter-reset` (#19387)
 * In `font.mako.rs`:
   - [x] `font-family` (#19355)
   - [x] `font-weight` (#19086)
   - [x] `font-size` (#19111)
   - [x] `font-size-adjust` (#19151)
   - [x] `font-synthesis` (#19160)
   - [x] `font-variant-alternates` (#19166)
   - [x] `font-variant-east-asian` (#19216)
   - [x] `font-variant-ligatures` (#19246)
   - [x] `font-variant-numeric` (#19276)
   - [x] `font-feature-settings` (#19290)
   - [x] `font-variation-settings` (#19208)
   - [x] `font-language-override` (#19187)
   - [x] `-x-lang` (#19320)
   - [x] `-moz-script-size-multiplier` (#19333)
   - [x] `-moz-script-level` (#19068)
   - [x] `-moz-script-min-size` (#19034)
   - [x] `-x-text-zoom` (#19020)

### How do I get started? How can I make any sense of the code?

This code lives in `compontents/style/properties/longhands`. Note that some of the code is Firefox-specific (properties marked with `products="gecko"`, so you may need to do `./mach build-geckolib` or `./mach cargo-geckolib check` in order to build and see).

Please ask here, in `#servo`, or open an issue like #19020 and say that you want to work on it.

Ask questions! I (or any of the other Servo members and contributors) are happy to help :)

### What's the general setup?

Each CSS property has two different representations: The "specified" one (the one people write in the stylesheets), and the "computed" one. Sometimes they are the same, sometimes they're different.

So for example if you write `width: 1em` in a CSS style sheet, the "specified" value is `1em`, but the "computed" value could be, for example, `10px`, if the parent font-size is `10px`.

So the way this is organized is roughly as follows: We have two rust modules inside `compontents/style/values`. The `computed` and the `specified` (there are others, but those shouldn't worry you).

The first argument for `predefined_type` is the CSS property name.

The second argument is the name of the type that becomes `computed::$name` or `specified::$name`, depending on the appropriate context. For example, in https://github.com/servo/servo/pull/19018, both are the same (`computed::ScrollSnapType` just re-exports `specified::ScrollSnapType`).

The third argument is the initial computed value of the property. The rest of the arguments are key-value pairs with various meanings, that we should probably preserve intact. If there are any questions about a particular argument feel free to ask though!

### Which ones are easier? Which ones are harder?

In general, the level of difficulty relates with the amount that lies inside the mako section of that property.

For example, `transform` is huge, and is fairly non-trivial, while probably others like `overflow-y` are easy to refactor like #19018.

But again, please ask if you're unsure and we'll try to answer! :)

**Comment by Manishearth** [comment]
Yes!

I'm currently doing transform stuff though I may not do the extra step of predefined typing it.

**Comment by SimonSapin** [comment]
> We use the mako template system to autogenerate code.
> 
> Ideally, we'd like to use a manifest, and use Rust to generate it instead.

Before we go through every property and move code around, maybe we could talk a little bit about what design we want?

For example, maybe instead of the pattern of having modules that are expected to define a few items of certain kinds with certain names, we could rely on the hot new language feature of associated types. That kind of things.

**Comment by SimonSapin** [comment]
After clarifying on IRC, it turns out that the changes I had in mind are mostly orthogonal with what this issue is about. So, carry on :)

**Comment by Manishearth** [comment]
We should also split up gecko.mako.rs into gecko.rs + gecko.mako.rs or something. All the manual impls go in gecko.rs. You can have multiple impl blocks for a type so that's fine.

**Comment by Manishearth** [comment]
Ideally, when debugging code it would be nice to never/rarely have to look at an autogenerated file and map its contents back to the "real" source.

**Comment by chansuke** [comment]
@emilio Hi.I want to try this issue:)

**Comment by emilio** [comment]
Hi @chansuke! This issue spans a few multiple sub-issues, are you interested in any of the list that don't have a PR or issue open already? If you don't want to choose one yourself, just let me know and I can choose one that is easy and assign it to you.

Thanks a lot!

**Comment by chansuke** [comment]
@emilio Thanks!!.I want you to choose & assign the easy one for me.

**Comment by KiChjang** [comment]
I'll take text-decoration-line.

**Comment by DonatJR** [comment]
@emilio Hey, I wanted to help with this issue. Could you point out one or two of the sub-issues which are fairly easy to get started? Thanks :)

**Comment by KiChjang** [comment]
@DonatJR The `content` attribute under `counters.mako.rs` looks quite straightforward, would you like to work on that?

**Comment by DonatJR** [comment]
@KiChjang Yes! I have created an issue for the specific longhand: #19387 
Thank you for helping me get started

**Comment by fenak** [comment]
Hi! I would like to work on the `list-style-image`. :)

**Comment by emilio** [comment]
Hi @fenak! I opened #19557, feel free to ask any question over there! :)

**Comment by jonleighton** [comment]
Hi, I'll try to look at `list-style-type`: https://github.com/servo/servo/issues/19629

**Comment by emilio** [comment]
On 12/22/2017 08:33 PM, Jon Leighton wrote:
> Hi, I'll try to look at |list-style-type|: #19629
> <https://github.com/servo/servo/issues/19629>

Awesome, thank you! :)

**Comment by stevel98** [comment]
@emilio Hi, could you point me to an easy one too?

**Comment by emilio** [comment]
Hi @stevel98, do you think you want to try #19656? I think it shouldn't be hard. I've tentatively assigned it to you. Ask any questions you may have over there :).

Thank you!

**Comment by stevel98** [comment]
@emilio Sure, I'll look into it. :)

**Comment by jonleighton** [comment]
I'll work on `image-orientation`: https://github.com/servo/servo/issues/19765

**Comment by GloverDonovan** [comment]
Hello I'd like to work on `text-emphasis-style`, thanks.

**Comment by jdm** [comment]
@GloverDonovan Go ahead and file an issue for it; you're welcome to work on it!

**Comment by SCpSCp** [comment]
./mach  /x/  /SŞ/  [RSS]  (split)

**Comment by SCpSCp** [comment]
0g
$python  0g
servo/servo;
friend;

**Comment by kleinph** [comment]
I would like to take `float` (and `clear` if the first one is successful). I already created issue #21130 (and a PR) for that.

**Comment by EmmaParker123** [comment]
Nice Article,

**[Digital Photo Recovery](http://www.digitalphoto-recovery.com)** is magnificent software which is able to restore most of the lost images, videos, and music from your device.

**Comment by atouchet** [comment]
@emilio @Manishearth is this done now?

**Comment by jdm** [comment]
I'm going to go ahead and claim it's done. We can file specific issues for anything remaining.
