### ISSUE TITLE
[meta] Implement value sanitizations for different input modes

### ISSUE THREAD

**Issue by KiChjang** [servo/servo#19172]
#18262 laid the groundwork for this, but we're still missing value sanitizations for:

- [x] [Date type inputs](https://html.spec.whatwg.org/multipage/input.html#date-state-(type=date):value-sanitization-algorithm) (#19385)
- [x] [Month type inputs](https://html.spec.whatwg.org/multipage/input.html#month-state-(type=month):value-sanitization-algorithm) (#19385)
- [x] [Week type inputs](https://html.spec.whatwg.org/multipage/input.html#week-state-(type=week):value-sanitization-algorithm) (#19559)
- [x] [Time type inputs](https://html.spec.whatwg.org/multipage/input.html#time-state-(type=time):value-sanitization-algorithm) (#19379)
- [x] [Date-time type inputs](https://html.spec.whatwg.org/multipage/input.html#local-date-and-time-state-(type=datetime-local):value-sanitization-algorithm) (#19602)
- [x] [Number type inputs](https://html.spec.whatwg.org/multipage/input.html#number-state-(type=number):value-sanitization-algorithm) and [range type inputs](https://html.spec.whatwg.org/multipage/input.html#range-state-(type=range):value-sanitization-algorithm) (#19730, #19761)
- [x] [Color type inputs](https://html.spec.whatwg.org/multipage/input.html#color-state-(type=color):value-sanitization-algorithm) (#19330)

All of the missing algorithms above are expected to be implemented in this function: https://github.com/servo/servo/blob/a3f2fae561de26fefb0ac0d569ce2c7a2942eee5/components/script/dom/htmlinputelement.rs#L873-L888

The implementation for these value sanitizations are given by the spec, which I have linked accordingly. When each of these are implemented, some subtests under `tests/wpt/web-platform-tests/html/semantics/forms/the-input-element/type-change-state.html` should be expected to PASS instead. Some other tests under the same directory may also pass as a result of a correct implementation.

If you want to help out with this, please comment on this issue or reach out on IRC (`#servo` in `irc.mozilla.org`), and we'll find one which is interesting to you; or, you can also file an issue and mention this one, and I'll get it assigned to you.

**Comment by tigercosmos** [comment]
@highfive: assign me

**Comment by tigercosmos** [comment]
@KiChjang Can I divide it to several parts and solve them one by one? Maybe two or three?

**Comment by KiChjang** [comment]
@tigercosmos Sure! Just comment and make a list of the ones that you'd like to solve.

**Comment by KiChjang** [comment]
Keeping this open for other potential contributors.

**Comment by tigercosmos** [comment]
I pick the first one `Date type inputs`

**Comment by tigercosmos** [comment]
Seems  `min` `max` `step` attributes have not implemented?
https://github.com/servo/servo/blob/a3f2fae561de26fefb0ac0d569ce2c7a2942eee5/components/script/dom/htmlinputelement.rs#L896-L899

**Comment by KiChjang** [comment]
That is incorrect. I can find them under the `HTMLInputElementMethods` trait implementation.
https://github.com/servo/servo/blob/33fa728d6e5392993c83f630acc1d6e442104dec/components/script/dom/htmlinputelement.rs#L496-L500

**Comment by tigercosmos** [comment]
That just get the value. But we need to do something? e.g. min should be number.

**Comment by KiChjang** [comment]
I assume the reason why you're asking is because the spec mentions `max`, `min` and `step` attributes should be valid date strings? You can safely ignore that part - the spec is written with different target audiences in mind: _HTML authors_ (which is to say programmers who write HTML) and _HTML implementors_ (us). Those requirements are for HTML authors, since they do not mention how _user agents_ (browsers) should act when they are invalid.

The only algorithm you need to implement is [the algorithm that determines whether they are valid date strings](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#valid-date-string), and I think the appropriate place to put that algorithm would be in `components/style/attr.rs`.

**Comment by Eijebong** [comment]
Going to do the color one

**Comment by KiChjang** [comment]
I believe @Eijebong is also working on the number and range type inputs.

**Comment by Eijebong** [comment]
Right, sorry I forgot to put it there.

**Comment by KiChjang** [comment]
@tigercosmos I haven't heard back from you for a while, do you need any help? Any questions?

**Comment by tigercosmos** [comment]
@KiChjang  I am stuck in other issues ... and preparing for midterm exams recently. 
I have deleted my declaration before. I will be back later (If this issue is still not fixed)

**Comment by tigercosmos** [comment]
I am working on "week" one.

**Comment by tigercosmos** [comment]
@KiChjang  Do we have `Date` object implement somewhere?

**Comment by tigercosmos** [comment]
I am back, and working on `Date` one

**Comment by SWW13** [comment]
I'm going to work on the `number` and `range` validation.

**Comment by tigercosmos** [comment]
@SWW13 that one have been picked by @Eijebong

**Comment by SWW13** [comment]
Oh, missed that. Could you update the initial issue and name the selected parts?

**Comment by tigercosmos** [comment]
I believe these are unassigned:
- Month type inputs
- Week type inputs
- Time type inputs
- Date-time type inputs

But some would be related to `Date` one, so I suggest choose those after `Date` done.

**Comment by SWW13** [comment]
Then I'll work on the `time` validation if you don't mind @tigercosmos? That should not be related to the `Date` input.

**Comment by tigercosmos** [comment]
That would be great!
Good luck ：)

**Comment by tigercosmos** [comment]
@KiChjang  this should be updated.

**Comment by KiChjang** [comment]
This is updated to reflect what has been done.

**Comment by tigercosmos** [comment]
@KiChjang  I suggest we move the logic of `color` one to binding?

**Comment by tigercosmos** [comment]
@KiChjang  How do you think about my comment above?

Besides, I will pick the`Week type inputs` one.

**Comment by KiChjang** [comment]
I'd rather not, most of the string parsing/validation logic is located in `str.rs`, I'd rather not move them around unnecessarily.

**Comment by tigercosmos** [comment]
@Eijebong Are you still work on `number` and `range` type inputs?

**Comment by tigercosmos** [comment]
I just found that @SWW13' s time implement is not completed.
both `parse a time string ` and `parse a time component` are not implemented.

**Comment by tigercosmos** [comment]
`Date-time type inputs` has opened a PR #19602

**Comment by tigercosmos** [comment]
I would like to take `Number type inputs and range type inputs`

**Comment by NLincoln** [comment]
I've started working on basic support for `type=number`. I have all of the pre-existing tests passing, just need to update the test manifest (I might be asking about that on IRC tonight actually... there were some errors when I ran it this morning). Once that's done I'll open a PR. 

My code is [here](https://github.com/servo/servo/compare/master...NLincoln:19172-number-input-type-validations). I used the standard f64 parser, just with a few changes where the browser spec is stricter than what rust allows. Is this approach Ok?

**Comment by tigercosmos** [comment]
@NLincoln this issue doesn't need to handle min, max, or step. I think you can open PR and that would be easier to discuss about the code.

**Comment by NLincoln** [comment]
:+1: I just opened one.

**Comment by tigercosmos** [comment]
let me finish the last one `range type inputs`
@highfive: assign me

**Comment by tigercosmos** [comment]
I have opened the last one PR in this issue.
Once #19761 finished, this will closed.

**Comment by CYBAI** [comment]
Is `E-Mail` sanitization missing for this `meta` issue?

Ref: https://html.spec.whatwg.org/multipage/input.html#e-mail-state-(type=email)

**Comment by tigercosmos** [comment]
Yes, let's reopen the issue.
