### ISSUE TITLE
Fix remaining WPT failures for element.innerText

### ISSUE THREAD

**Issue by ferjm** [servo/servo#20060]
There are still several tests failing for the getter of `element.innerText`.

Check: https://github.com/servo/servo/blob/master/tests/wpt/metadata/innerText/getter.html.ini

The table related ones are likely because of missing support [here](https://github.com/servo/servo/blob/master/components/layout/query.rs#L1027). The others require further investigation.

Blockers:
- [ ] Support `visibility: collapse` #20142
- [ ] Properly implement step 3 of the inner text collection steps algorithm #20159
- [ ] Ignore descendants nodes of replace elements during inner text collection steps #20161

**Comment by shanehandley** [comment]
This can be closed as well as associated tickets 👍 it refers to the old layout, and this was implement in the new layout code recently: https://github.com/servo/servo/pull/33312
