### ISSUE TITLE
Tracking issue for syn 0.13 + quote 0.5 in Servo and dependencies

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#20497]
Do avoid increasing the number versions of syn in Servo’s dependency graph, we should coordinate landing this in various repository at around the same time. So far:

* [x] https://github.com/servo/html5ever/pull/341
* [x] https://github.com/servo/rust-cssparser/pull/217
* [x] https://github.com/servo/string-cache/pull/203
* [x] FIXME: add other affected crates

Ideally, before anything is merged we should have a branch of Servo that uses `[patch.crates-io]` in the root `Cargo.toml` to use all of the relevant PR branches, and check that everything builds with minimal duplication (crates with the same name) in `Cargo.lock`.

**Comment by Eijebong** [comment]
- [ ] https://github.com/upsuper/cstr/pull/1
- [ ] https://github.com/rust-lang-nursery/rust-bindgen/pull/1303
- [ ] https://github.com/mystor/synstructure/pull/13

**Comment by hcpl** [comment]
Just briefly traversed the `servo` dependency tree. Steps needed to update following crates:
- [ ] `deny_public_fields`: `synstructure` (https://github.com/mystor/synstructure/pull/13) + PR
- [ ] `domobject_derive`: PR
- [ ] `euclid`: only needs `serde` 1.0.37+ in `servo`\`s `Cargo.lock`
- [ ] `jstraceable_derive`: `synstructure` (https://github.com/mystor/synstructure/pull/13) + PR
- [ ] `malloc_size_of`: `cssparser` (https://github.com/servo/rust-cssparser/pull/217) + PR?
- [ ] `malloc_size_of_derive`: `synstructure` (https://github.com/mystor/synstructure/pull/13) + PR
- [ ] `style`: `html5ever` (https://github.com/servo/html5ever/pull/341) + PR?
- [ ] `style_derive`: `synstructure` (https://github.com/mystor/synstructure/pull/13) + PR

**Comment by Eijebong** [comment]
Yep, we just need all the PRs above to be released. Servo doesn't need any code change, just bumping the versions seemed to be enough :)

**Comment by Eijebong** [comment]
All those PRs can be merged/released
