### ISSUE TITLE
Format all code with rustfmt

### ISSUE THREAD

**Issue by jdm** [servo/servo#21373]
https://github.com/servo/servo/issues/8553#issuecomment-359192605 describes a configuration that respects some style settings that we care about. I think it's worth systematically formatting Servo's code crate by crate (or module by module in the case of particularly large crates) and then integrating the changes in https://github.com/servo/servo/pull/20617 to enforce proper style in our CI.

Components:
- [x] allocator (#21428)
- [x] atoms (#21440)
- [x] bluetooth (#21442)
- [x] bluetooth_traits (#21442)
- [x] canvas (#21538)
- [x] canvas_traits (#21538)
- [x] compositing (#21551)
- [x] config (#21578)
- [x] constellation (#21225)
- [x] debugger (#21567)
- [x] deny_public_fields (#21567)
- [x] devtools (#21582)
- [x] devtools_traits (#21582)
- [x] dom_struct (#21584)
- [x] domobject_derive (#21584)
- [x] embedder_traits (#21584)
- [x] fallible (#21598)
- [x] geometry (#21598)
- [x] gfx (#21610, #21630, #21638)
- [x] gfx_traits (#21648)
- [x] hashglobe (#21648)
- [x] jstraceable_derive (#21655)
- [x] layout (#21509)
- [x] layout_thread (#21613)
- [x] layout_traits (#21614)
- [x] malloc_size_of (#21615)
- [x] malloc_size_of_derive (#21615)
- [x] metrics (#21672)
- [x] msg (#21672)
- [x] net (#22099)
- [x] net_traits (#22099)
- [x] profile (#21651)
- [x] profile_traits (#21657)
- [x] rand (no formatting required)
- [x] range (#21685)
- [x] remutex (#21686)
- [x] script (#21737)
- [x] script_layout_interface (#21687)
- [x] script_plugins (#21694)
- [x] script_traits (#21693)
- [x] selectors (#21679)
- [x] servo (#21664)
- [x] servo_arc (no formatting required)
- [x] size_of_test (#21661)
- [x] style (#21652)
- [x] style_derive (#21635)
- [x] style_traits (#21620)
- [x] url (#21617)
- [x] webdriver_server (#21603)
- [x] webvr (#21597)
- [x] webvr_traits (#21593)

ports:
- [x] libsimpleservo (#21675)
- [x] servo (#21676)

**Comment by jdm** [comment]
We now have a `./mach rustfmt [path]` command that can be used, and you'll want to run `rustup component add rustfmt-preview` to install rustfmt if you don't already have it.

**Comment by kingdido999** [comment]
Hi, I would like to work on this and will probably start from formatting the first component on the top. 

@highfive: assign me

**Comment by kingdido999** [comment]
So I've successfully built the project. But when I run `./mach rustfmt components/allocator/lib.rs`, it says:

```
It looks like you passed an unrecognized argument into mach.

The rustfmt command does not accept the arguments: components/allocator/lib.rs
```

So I look into the [rustfmt command](https://github.com/servo/servo/blob/master/python/servo/devenv_commands.py#L236) defined in `python/servo/devenv_commands.py`, seems we have to pass in a `--directory` argument. Then I do `./mach rustfmt -d components/allocator`, it returns:

```
Error: `/Users/Desmond/repo/servo/components/allocator` is a directory
```

Despite the error, it does run the formatting but for all files in the project, which is not what we want. If I provide a file path instead of a directory path, no error is shown but it formats the entire project again. My best guess is that `--directory` is not a valid command for [rustfmt](https://github.com/rust-lang-nursery/rustfmt), we could produce the same error if we run `rustfmt components/allocator`.

Directly run `rustfmt` against a file works properly:

```bash
rustfmt components/allocator/lib.rs
```

Here are the versions of `rustc` and `rustfmt` on my system:

```bash
$ rustc --version
rustc 1.29.0-nightly (1ecf6929d 2018-07-16)

$ rustfmt --version
rustfmt 0.8.2-nightly (5e599251 2018-07-02)
```

@jdm Please let me know if I'm missing something when I do `./mach rustfmt [path]`, thanks!

**Comment by jdm** [comment]
I've verified that you're not missing anything. `cargo fmt` does not appear to do what we want; it looks like we'll need to modify the `./mach rustfmt` command to recursively find all of the rust source files under the given directory and pass those as arguments to `rustfmt` directly. Would you like to make that change?

**Comment by kingdido999** [comment]
Sure I will work on it.

**Comment by kingdido999** [comment]
I'm trying to get a rough idea on the use cases of `/mach rustfmt [directory]` other than resolving this particular issue (format crate one at a time). It seems to me that we can simply get away with `rustfmt` as a part of future CI build after all crates have been formatted. So if that is true, we don't necessarily need to invent an extra command to format a directory, we could do something like this instead:

```bash
rustfmt ports/servo/**/*.rs
```

**Comment by chansuke** [comment]
Hi.I'd like to work on this too.I will start from the component on the bottom:)

**Comment by CYBAI** [comment]
I'm just curious, when `rustfmt` tasks for all components are done, should we add `rustfmt` to be part of `./mach test-tidy`?

**Comment by jdm** [comment]
Yes. We will replace all of the code style checks in tidy.py with running `rustfmt --check` instead.

**Comment by AnshulMalik** [comment]
`rand` is already formatted.

**Comment by pyfisch** [comment]
Hi, formatting is almost complete. I'd like to suggest that servo adopts a new formatting for `use` statements. Currently use statements are ordered alphabetically and split into multiple lines if they are longer than 100 characters.

I would want to split the imports into 4 groups (std, third-party imports, workspace imports, imports from the same crate) and sort those groups individually. (See rust-lang-nursery/rustfmt#2979)

Additionally I prefer to use `merge_imports` formatting. I can see at a glance which items are imported from a module and how the module hierarchy is structured. ([example file](https://gist.github.com/pyfisch/1e5896bbbba2f3905c8b895bb81aa206))

The grouping can be done with a script. This could either be added to `cargo fmt` or the lines are grouped by a script once.

**Comment by Dmitry-Borodin** [comment]
@jdm I see the last components from the list net and net_traits was formatted in #22099. 
Should this issue now be closed?
It's among the first options in https://starters.servo.org/ -)

**Comment by atouchet** [comment]
#20617 still needs to be finished.

**Comment by CYBAI** [comment]
Fixed in #22126
