### ISSUE TITLE
Magic Leap minimum viable demo

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#22043]
Features that are needed for a demoable Servo on Magic Leap:

- [X] Render web content (#21985)
- [x] Respond to touchpad: hover state plus follow hyperlinks (#22045)
- [x] Respond to navigation fwd/back (#22057)
- [x] Respond to URL changes (#22066)
- [ ] Scrolling

**Comment by blairmacintyre** [comment]
Those seem like a good list.  

Is it worth looking at the current Firefox Reality on GO, and listing the things it does that we can/can't do.

For example, things we don't need (or can't do) for an MVD are

- [ ] webvr/webxr
- [ ] private browsing
- [ ] full 3D ray from controller (we'd need to shift to immersive mode for this, anyway)

In terms of difficulty, I have no idea where things like "interact with interactive elements like sliders" falls?

**Comment by asajeffrey** [comment]
@blairmacintyre good point re interacting with web input components. At the moment mouse clicks should work, but not mouse up/down or anything using the keyboard.
