### ISSUE TITLE
360 video

### ISSUE THREAD

**Issue by ferjm** [servo/servo#22309]
Meta issue to track the work required to play 360 video.

- [ ] [Enable hardware accelerated video playback](https://github.com/servo/servo/issues/22300)
- [ ] [Support HTMLVideoElement as texture image source](https://github.com/servo/servo/issues/21995)
- [ ] [TexSubImage2D obtains the full image pixels then uses a subset](https://github.com/servo/servo/issues/21996)
