### ISSUE TITLE
Enable hardware accelerated video playback

### ISSUE THREAD

**Issue by ferjm** [servo/servo#22300]
This involves several pieces, some of them are already WIP:

- [x] [Add bindings for GStreamerGL](https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/merge_requests/161)
- [x] [Expose the EGLDisplay](https://github.com/tomaka/glutin/issues/1078)
- [x] [Modify player example to use GStreamerGL](https://github.com/servo/media/issues/166)
- [x] [Add a way to share EGLDisplay/X11 Display and GL context with servo-media](https://github.com/servo/servo/issues/22920)
- [x] Modify the existing HTMLMediaElement FrameRenderer to use GStreamerGL

**Comment by ceyusa** [comment]
> This involves several pieces, some of them are already WIP:
> 
> * [X]  [Add bindings for GStreamerGL](https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/merge_requests/161)
> * [X]  [Expose the EGLDisplay](https://github.com/tomaka/glutin/issues/1078)
> * [ ]  [Modify player example to use GStreamerGL](https://github.com/servo/media/issues/166)
> * [ ]  Add a way to share EGLDisplay/X11 Display and GL context with servo-media
> * [ ]  Modify the existing HTMLMediaElement FrameRenderer to use GStreamerGL
