### ISSUE TITLE
Timed text tracks support (subtitles, captions, etc.)

### ISSUE THREAD

**Issue by ferjm** [servo/servo#22314]
Spec: https://html.spec.whatwg.org/multipage/media.html#timed-text-tracks

This is a meta issue to track the work required to add timed text tracks support. More items might be added to the list as we progress with the implementation or a deeper analysis of the spec(s) is made.

- [ ] [Implement the Text track API](https://github.com/servo/servo/issues/22311)
- [ ] [Support for WebVTT format](https://github.com/servo/servo/issues/22312)
- [ ] [Implement the HTMLTrackElement](https://github.com/servo/servo/issues/22313)
