### ISSUE TITLE
Meta: move CI from Buildbot to Taskcluster

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#22325]
## Previously

https://github.com/servo/saltfs/issues/559#issuecomment-409632684

## Done

Docs: [`etc/taskcluster/README.md`](https://github.com/servo/servo/tree/master/etc/taskcluster#readme)

* [x] https://github.com/servo/servo/pull/21776
  - In-tree decision task
  - In-tree `Dockerfile`s, with corresponding images built as needed and cached
  - CI task: tidy + Linux dev build + unit tests
  - CI tasks (implemented but disabled for now): Linux release build + WPT
  - Daily task: Linux dev with Rust Nigthly
* [x] https://github.com/servo/saltfs/pull/888
  - Make Homu also gate PRs on Taskcluster
* [x] https://github.com/servo/servo/pull/21835
  - Android ARMv7 build task
* [x] https://github.com/servo/servo/pull/21863
  - Configure Windows 2016 workers
  - Windows build task
* [x] https://github.com/servo/servo/pull/22046
  - Android x86 build task
  - Configure Packet.net worker
  - Android x86 emulator tests task
* [x] https://github.com/servo/servo/pull/22185
  - Configure Macstadium worker
  - macOS dev build + unit tests task
* [x] https://github.com/servo/servo/pull/22233 Treeherder integration: https://treeherder.mozilla.org/#/jobs?repo=servo-auto
* [ ] https://github.com/mozilla/treeherder/pull/4320 Use the GitHub events API to find the date of a push
* [x] https://github.com/servo/servo/pull/22381 + https://github.com/servo/servo/pull/22436
  - Build docs and upload to doc.servo.org on Taskcluster
  - Support for trychoosers, part 1
* [x] https://github.com/servo/servo/pull/22419 Move "dev" builds and unit tests from Buildbot to Taskcluster
* [x] https://github.com/servo/servo/pull/22424 Documentation on Treeherder
* [x] https://github.com/servo/saltfs/pull/925
  - Trychoosers part 2
  - Disable some Buildbot builders
* [x] https://github.com/mozilla/treeherder/pull/4371 Show all `try-*` branches on https://treeherder.mozilla.org/#/jobs?repo=servo-try
* [x] https://github.com/servo/servo/pull/22459 Move macOS WPT chunk 1 (only) from Buildbot to Taskcluster 
* [x] https://github.com/servo/servo/pull/22464 Build Servo Nigthly for Linux, upload to S3 
* [x] https://github.com/servo/servo/pull/22435 Move Linux WPT from Buildbot to Taskcluster
* [x] https://github.com/servo/servo/pull/23304 Transfer mac/windows/android nightly builds to Taskcluster
* [x] #23356 Move android mac build to taskcluster
* [x] #23355 Increase number of mac taskcluster WPT jobs
* [x] #23396 Update generic-worker for macOS
* [x] https://github.com/servo/servo/pull/23383 Reuse more tasks
* [x] https://github.com/servo/servo/pull/23406 Move all macOS WPT jobs to Taskcluster
* [x] https://github.com/servo/servo/pull/23362 Move magicleap builds to taskcluster
* [x] https://github.com/servo/servo/pull/23633 Remove some jobs from Buildbot
* [x] https://github.com/servo/servo/pull/24785 Move WPT Linux from Buildbot to Taskcluster
* [ ] https://github.com/servo/saltfs/pull/988 Disable gating servo/servo PRs on Buildbot

## To do

Tasks remaining on Buildbot:

* [x] CI: Linux WPT (disabled in https://github.com/servo/servo/pull/22527)
* [x] On PRs, not gating CI: `chaos_monkey_test.py`

When we’re happy with the stability of a given task on Taskcluster:

* [x] Remove the corresponding job/builder from Buildbot configuration (see https://github.com/servo/saltfs/pull/925/commits/7c1033773bd57b9346b168986c272a96a519986a)
* [ ] If any, decommission workers that are now unused
* [ ] Remove unused entry in `buildbot_steps.yml`
