### ISSUE TITLE
Magic Leap minimum viable product

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#22407]
We currently have a "minimum viable demo" of Servo on Magic Leap. Features that would be needed for an MVP:
- [ ] Acceptable performance
- [x] Immersive mode (#22402)
- [x] Media (#22807, #22403)
- [ ] Tracking protection (#22404)
- [ ] Home page (https://github.com/servo/servo.org/issues/70)
- [ ] Web page minimization (#22400)
- [ ] Keyboard activation (#22401)
- [ ] Multiple windows (#22653)

And optionally:
- [ ] Multiprocess
- [ ] Cross-origin wrappers (#2382)
- [ ] Private browsing
- [ ] Firefox accounts (#22405)
- [ ] Password manager

**Comment by asajeffrey** [comment]
Sigh, keyboard activation regressed, c.f. #22983 and #23969,

**Comment by jdm** [comment]
No longer supporting magic leap.
