### ISSUE TITLE
Implement partial Shadow DOM support (for User Agent UI widgets)

### ISSUE THREAD

**Issue by ferjm** [servo/servo#22719]
In order to implement User Agent UI widgets like the media controls, we need to implement partial Shadow DOM support, this is:

- [ ] DOM Isolation, i.e. `document.querySelector()` should not return nodes from the UA widget.
- [ ] Scoped CSS, CSS defined inside the UA widget should be scoped to it and it should not be affected by styles from the outside. @emilio mentioned that we might already have this from the stylo work.
- [ ] Event model, some events need to be re-targeted to look like they've come from the widget host (i.e. `<video>`) rather than from its internal elements.
- [ ] Privileged JS (?) It's not clear to me how this would work or if it is really required.

I don't think we need any of the content facing API or any of the `<slot>` stuff for now.

**Comment by gterzian** [comment]
I think something like that could also be relevant for implementing "contenteditable" following the approach mentioned at https://github.com/servo/servo/issues/12776#issuecomment-430793267
