### ISSUE TITLE
(Some?) nightly uploads newly on Taskcluter are broken

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#23320]
https://github.com/servo/servo/pull/23304 has landed, but unfortunately our PR testing does not exercise at all the CI code that runs for daily tasks, such as Nightly builds upload. There was multiples issues:

* [x] The daily decision task did not have scopes for the new entries in the Secrets API https://github.com/servo/servo/pull/23304#issuecomment-489065873
* [x] These scopes were not forwarded to the new tasks https://github.com/servo/servo/pull/23316
* [x] `taskcluster-proxy` was not installed on macOS workers https://github.com/servo/servo/pull/23319
* [x]  `taskcluster-proxy` was not installed in the AMI for Windows workers https://github.com/servo/servo/pull/23327
* [x] The *macOS x64: Nightly build and upload* goes over its two hours time budget (though after successfully uploading a Nightly) because it also runs WPT tests (to update expectations).
  - Let’s increase the timeout or split it into two tasks https://github.com/servo/servo/pull/23327
* [x] `./mach upload-nightly maven` looks for both ARMv7 and x86 builds, but they are built in separate tasks https://github.com/servo/servo/pull/23327
* [x] The mac build machines are missing `jq` which the WPT sync job uses #23338
* [x] [This line](https://github.com/servo/servo/blob/64c848950c50b1946e5a3f69d66ca5aac5b9ce1a/etc/ci/update-wpt-checkout#L96) should reference SECRET_RESPONSE instead of OPEN_PR_RESPONSE #23338
* [x] WPT job fails to push the git branch, probably due to an incorrect secret #23346
* [ ] Other issues?

After changes land in `master`, they can be tested by clicking the Trigger button on https://tools.taskcluster.net/hooks/project-servo/daily. Testing a different branch is possible by changing the `GIT_REF` env variable. Don’t forget to revert such changes after triggering the test run.

**Comment by SimonSapin** [comment]
Windows Nightly build and upload task https://tools.taskcluster.net/groups/GLEPxdzkRNmILrCbKsk_NQ/tasks/IY-N1eQKR56kuWFLq2HbGA/runs/0 ran into its 60 minutes timeout.

**Comment by jdm** [comment]
All nightly jobs are chugging along now.
