### ISSUE TITLE
[meta] Update to Gstreamer 1.16

### ISSUE THREAD

**Issue by Manishearth** [servo/servo#23390]
Keeping track of the work needed to upgrade to Gstreamer 1.16

 - [x] Generate linux bundle: https://github.com/servo/servo/issues/23391
 - [x] Generate android bundle
 - [ ] Update gstreamer-rs
 - [x] Update AppVeyor with GStreamer 1.16 #23484
 - [x] Update Travis with GStreamer 1.16
 - [x] Update bootstrap with GStreamer 1.16

**Comment by Manishearth** [comment]
cc @ferjm @jdm

**Comment by ford-prefect** [comment]
Anything I can help with here?

**Comment by ferjm** [comment]
I believe this is already done. The only missing piece seems to be updating gstreamer-rs in Servo, but that's already done in servo-media, so it should happen with the next servo-meida update.
