### ISSUE TITLE
Meta: https://servo.org in Layout 2020

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#25041]
* [x] Text https://github.com/servo/servo/pull/24822
* [ ] Text is clipped https://github.com/servo/servo/issues/24930
* [x] `<img>` https://github.com/servo/servo/pull/24928
* [x] `max-width` https://github.com/servo/servo/pull/25031
* [ ] `text-align: center` (used in button-like links)
* [ ] `border-radius` (used in button-like links and command-line instructions) https://github.com/servo/servo/issues/25040
* [ ] Underline (used in hovered links)
* [ ] Floats (at some viewport sizes, for splitting into two columns)

CC @nox

**Comment by SimonSapin** [comment]
Closing in favor of https://github.com/servo/servo/projects/22.
