### ISSUE TITLE
Wikipedia issues

### ISSUE THREAD

**Issue by brson** [servo/servo#2554]
This is an evaluation of problems with http://en.wikipedia.org/wiki/Rust on 2014-06-02.
# General
- [x] Link hovering has no effect
- [x] Background gradient is missing (background-image: linear-gradient)
- [ ] HiDPI versions of images are not used
- [x] Fonts look a lot worse—at least on Mac (kerning?)
- [ ] Not as much Unicode support—⇌ in particular renders as a square at least on Mac (not choosing fallback fonts?)
# Logo
- [x] On www.wikipedia.org: Not visible due to percent height (#2029)
- [x] On www.wikipedia.org: Wrong styles due to incorrect stylesheet ordering (#3346)
- [x] Missing transparency (premultiplied alpha)
## Sidebar menus
- [x] "Navigation" list header is visible in servo, hidden in fx (display: none + media queries)
- [x] "Navigation" menu is indented in servo, not in fx (maybe media query or selector matches)
- [x] horizontal rules look wrong (premultiplied alpha)
- [x] "Edit links" is missing its icon (a:link, a:visited)
- [x] "Edit links" has a line break that fx doesn't (preferred and minimum widths)
- [ ] Languages gear icon missing (linear gradient backgrounds)
- [ ] Gear icon dynamic hover behavior
## Top nav bar
- [x] "Create account / Log in" is squished to the right with too many linebreaks (min/pref widths for floats - maybe floats don't work inside inlines, maybe media queries)
- [x] Servo has a white band running across header
- [x] Menu items are formatted wrong (something with floats)
- [x] Menu item images overflow (image clipping for backgrounds)
- [x] Magnifying glass icon in search box is rendered incorrectly (linear gradient)
- [x] Menu items are shifted too far down
## Main area
- [x] "citation" message box is not wide enough (automatic table layout - maybe using minwidth instead of expanding to fit)
- [x] text does not flow around the infobox - infobox is aligned left, not right (margins and floats)
- [x] main image and its containing box are laid out wrong
- [ ] superscript footnotes are not superscripted (vertical-align: super)
- [x] "[edit]" links are incorrectly preceded by line breaks (inline-block)
- [x] Vertical alignment of all images is wrong (margins + floats)
- [x] Superscripts in equations wrong (vertical-align: super?)
- [x] Lots of alpha channel problems (premultiplied alpha)
- [x] "Structural failures caused by rust" missing images
- [x] "Structural failures caused by rust" two items are stacked vertically instead of inline (inline-block)
- [x] Ditto for 'gallery'
- [ ] "See also" missing bullets (list-style-type: image)
- [ ] "See also" missing columns (css multi-col)
## Citation message box
- [x] Line breaks between "verification" and the subsequent period. Doesn't seem like lines should break on periods. Also seeing breaks before commas.
- [x] Top and bottom borders are 2px instead of 1px (border collapse)
## Infobox
- [x] "v t e" is not capitalized (font variant)
- [x] "v t e" overflows its container (table)
- [x] dark gray headers overflow their container
- [ ] padding around main container is wrong and inconsistent
- [x] Top and bottom borders are 2px instead of 1px (border collapse)
# Contents
- [x] Contents box is too narrow (tables)
- [ ] "[hide]" link doesn't appear (interaction between tables and blocks)
# References
- [ ] Missing list numbers (ordered lists)
# External Links
- [x] Side boxes are left aligned instead of right
- [ ] Margins between boxes are wrong
- [ ] Top and bottom borders of boxes are again 2px instead of 1px (border collapse?)
- [x] Wiktionary image overflowing box
- [ ] Too much interior padding/margin/spacing on left causes the interior cell to overflow box
- [ ] Missing bullets in list
- [x] External link icons in wrong position (`background-position` keyword values (e.g. `right center`)
- [x] An image tag just appears in the page output
# Categories
- [x] Every word line breaked instead of inline (inline-block)
- [x] Too much inline space after each category
# Footer
- [x] Missing "Privacy policy", "About Wikipedia", etc
- [x] Missing wikimedia and mediawiki promotional buttons

**Comment by dralley** [comment]
This can probably be closed due to the age of the analysis.
