### ISSUE TITLE
Improvements to the CSS Transitions and Animations implementation

### ISSUE THREAD

**Issue by mrobinson** [servo/servo#26328]
* [x] Fix animations and transitions processing model. Also see  #13865. 
  * [x] Restyle should apply animations and transitions (#26331)
  * [x] Animation tick should trigger a restyle and properly cascade animated and transitioned values (ie `getComputedStyle()` should return the result of applying animations and transitions) (#26407)
  * [x] Implement proper cascading among !important rules, animations, and transitions (#26806)
* [x] Add support for animations and transitions to Layout 2020 (#26486)
* [x] Better handling of animations
  * [x] Add support for `animation-fill-mode` (#26519)
  * [x] Finish the implementation of fractional iteration counts (#14858)
  * [x] `animationstart` (#26659)
  * [x] `animationend` (#26362)
  * [x] `animationiteration` (#26594)
  * [x] `animationcancel` (#26659)
  * [x] Cascade keyframes with the same keyframe selector when computing animation steps (#26562)
* [x] Better handling of transitions
  * [x] Properly [replace running transitions](https://drafts.csswg.org/css-transitions/#reversing) when style changes (#26540)
  * [x] `transitionrun` (#26308)
  * [x] `transitionstart` (#26659)
  * [x] `transitioncancel` (#26244)
  * [x] Cancel transitions for nodes that have been reparented in the DOM (#26953)
* [x] Support transitions and animations on pseudo content (#26923)
* [ ] Add support for the Web Animations API

**Comment by mrobinson** [comment]
cc @jdm @emilo @SimonSapin

**Comment by mrobinson** [comment]
This is complete apart from the Web Animations API, which is quite a large task. I think it makes sense to close this bug in favor of #26626.

**Comment by jdm** [comment]
Fantastic effort @mrobinson!
