### ISSUE TITLE
Tracking: upgrade to nightly-2020-05-26

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#26661]
Blocked on:

* [x] Installing the `llvm-tools-preview` component https://github.com/servo/servo/issues/26645#issuecomment-633829852, https://github.com/servo/servo/pull/26662
* [x] Handling `syn::Type::Group` in `derive_common::cg::map_type_params` https://github.com/servo/servo/pull/26662
* [x] rustfmt being available https://github.com/rust-lang/rust/issues/72232
* [x] ICE in `gfx-backend-metal` https://github.com/servo/servo/issues/26648, https://github.com/rust-lang/rust/issues/72467
* [x] Upgrade parking-lot to 0.10 https://github.com/servo/servo/issues/26644, https://github.com/servo/servo/pull/26646. Work around: disable its `nightly` feature (which enables hardware lock elision) 
* [x] Exhaustiveness check regression https://github.com/rust-lang/rust/issues/72476. Work around:
  ```diff
  --- ports/glutin/headed_window.rs
  +++ ports/glutin/headed_window.rs
  @@ -543,10 +543,14 @@ impl WindowMethods for Window {
   
           #[cfg(target_os = "linux")]
           return match native_context {
  -            NativeContext::Default(NativeContext::Default(native_context)) =>
  -                PlayerGLContext::Egl(native_context.egl_context as usize),
  -            NativeContext::Default(NativeContext::Alternate(native_context)) =>
  -                PlayerGLContext::Egl(native_context.egl_context as usize),
  +            NativeContext::Default(d) => match d {
  +                NativeContext::Default(native_context) => {
  +                    PlayerGLContext::Egl(native_context.egl_context as usize)
  +                },
  +                NativeContext::Alternate(native_context) => {
  +                    PlayerGLContext::Egl(native_context.egl_context as usize)
  +                },
  +            },
               NativeContext::Alternate(_) => unimplemented!(),
           };
   
  @@ -574,10 +578,10 @@ impl WindowMethods for Window {
   
           #[cfg(target_os = "linux")]
           return match native_connection {
  -            NativeConnection::Default(NativeConnection::Default(conn)) =>
  -                NativeDisplay::Egl(conn.0 as usize),
  -            NativeConnection::Default(NativeConnection::Alternate(conn)) =>
  -                NativeDisplay::X11(conn.x11_display as usize),
  +            NativeConnection::Default(d) => match d {
  +                NativeConnection::Default(conn) => NativeDisplay::Egl(conn.0 as usize),
  +                NativeConnection::Alternate(conn) => NativeDisplay::X11(conn.x11_display as usize),
  +            }
               NativeConnection::Alternate(_) => unimplemented!(),
           };
  ```
* [x] `TokenTree` regression affecting syn https://github.com/rust-lang/rust/issues/72608. Better work around: updating syn to 1.0.26: https://github.com/rust-lang/rust/issues/72608#issuecomment-634204306, https://github.com/dtolnay/syn/pull/832. Work around:
   ```diff
  --- components/canvas_traits/webgl.rs
  +++ components/canvas_traits/webgl.rs
  @@ -932,7 +932,10 @@ macro_rules! gl_enums {
               #[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, MallocSizeOf)]
               #[derive(PartialEq, Serialize)]
               #[repr(u32)]
  -            pub enum $name { $($variant = $mod::$constant,)+ }
  +            pub enum $name { $(
  +                // FIXME https://github.com/rust-lang/rust/issues/72608
  +                $variant = { use $mod::$constant; $constant },
  +            )+ }
  
   ```

**Comment by SimonSapin** [comment]
https://github.com/rust-lang/rust/pull/72671 and https://github.com/rust-lang/rust/pull/72506 landed yesterday, fixing the remaining blockers. https://community-tc.services.mozilla.com/tasks/groups/G-mDKoxPROqJOjPiEkjBgw is green (enough) with today’s Nightly without any code change (beyond https://github.com/servo/servo/pull/26662), so closing.
