### ISSUE TITLE
WebXR Layers features needed to be spec-compliant

### ISSUE THREAD

**Issue by asajeffrey** [servo/servo#27468]
This is a meta-issue to track which features we need to support to be spec-compliant with https://immersive-web.github.io/layers/

- [ ] Update the WebIDLs
- [ ] Projection layers
- [ ] Pref to enable layers
- [ ] Feature for `layers
- [ ] `XRMediaBinding`
- [ ] `XRLayerEvent`
- [ ] Textures generated for WebXR should be `TEXTURE_2D` not `TEXTURE_RECTANGLE` on MacOS
- [ ] Support for `TEXTURE_2D_ARRAY`
- [ ] WebGL textures in WebXR layers being backed by different GL textures
- [ ] Layer layouts `stereo` and `default`
- [ ] Layer attributes:
  - [ ] `blendTextureSourceAlpha`
  - [ ] `chromaticAberrationCorrection`
  - [ ] `fixedFoveation`
  - [ ] `needsRedraw`
  - [ ] ` ignoreDepthValues`

**Comment by asajeffrey** [comment]
This is the minimal list, to provide an implementation of the XR Layers spec which does not support the `layers` feature (so doesn't support quad layers etc.).

**Comment by asajeffrey** [comment]
I filed a separate issue https://github.com/servo/servo/issues/27493 for the `layers` feature descriptor.

**Comment by asajeffrey** [comment]
Samples at https://cabanier.github.io/WebXRLayers-samples/index.html, source at https://github.com/cabanier/WebXRLayers-samples
