### ISSUE TITLE
Rewrite readable stream implementation without spidermonkey builtin object

### ISSUE THREAD

**Issue by jdm** [servo/servo#29088]
The next spidermonkey upgrade will bring in https://bugzilla.mozilla.org/show_bug.cgi?id=1795914, which removes the JS implementation. We will need to port https://bugzilla.mozilla.org/show_bug.cgi?id=1730589 and subsequent changes from https://searchfox.org/mozilla-central/source/dom/streams/ReadableStream.cpp before we can upgrade.

**Comment by jdm** [comment]
Relevant base code in servo is https://github.com/servo/servo/blob/master/components/script/dom/readablestream.rs

**Comment by jdm** [comment]
I'm working on this. It looks like it might be easier than I anticipated, since we aren't actually implementing the full WHATWG Streams API defined in https://streams.spec.whatwg.org/.

**Comment by jdm** [comment]
I've pushed my (very rough) in-progress branch to https://github.com/servo/servo/compare/master...jdm:servo:no-streams?expand=1 . I was using `tests/wpt/web-platform-tests/xhr/overridemimetype-blob.html` as the initial testcase; right now [this subtest](https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/xhr/overridemimetype-blob.html#L31-L34) times out because the promises aren't queued correctly.

**Comment by jdm** [comment]
Note to self: consume_stream in script_runtime.rs will also need to be removed/replaced.

**Comment by jdm** [comment]
The latest commit allows the majority of the tests in XHR to pass. The idlharness tests crash in the JS engine because the memory safety story for readable streams is much less clear than it used to be. My goal once that crash is fixed is to clean up the code and then document the state of the world so it becomes easier to reason about how to make it less complex. It's... difficult to follow at the moment.

**Comment by sagudev** [comment]
I also started working on [prototyping streams](https://github.com/sagudev/servo/commits/readablestream), but I left it due to time constrains at that time and I do not plan to comeback working on it anytime soon. It does not compile, but some initial work has been laid down (mostly webidls, which for some reason need to be splitted over multiple files or else codegen does not work).

**Comment by jdm** [comment]
We will need to decide if we turn off readable streams in mozjs as part of this work. That would definitely make the test results more honest.

**Comment by sagudev** [comment]
There is [`--enable-js-streams`](https://github.com/servo/mozjs/blob/98b678283d1b0c6d263302ca2aff770aece0cb8e/mozjs/makefile.cargo#L13).

**Comment by jdm** [comment]
Yep. I think I'd like to get the tests all passing with his streams enabled, then remove that flag and see what the impact is on the test coverage.

**Comment by sagudev** [comment]
We decided to not block SM upgrade on this and port JS streams to SM ESR 115 in https://github.com/servo/mozjs/pull/408. We should still do this sometimes in the future, preferably before next ESR.

**Comment by wusyong** [comment]
The title of this issue is more straight forward so I'll leave the progress here. So we decided to create another branch, [readablestream-re-implementation](https://github.com/servo/servo/tree/readablestream-re-implementation), to work on this.

Here's a rough overview of the progress. I'll add more details as it proceeds:

- [x] `ReadableStream` WebIDL codegen: #32605
    - [x] `Constructor`: https://github.com/servo/servo/pull/32634
    - [x]  `ReadableStreamMethods` implementation
        - [x] `Locked`
        - [x] `Cancel`
        - [x] `GetReader`
- [x] `ReadableStreamDefaultController` WebIDL codegen
    - [x] `SetUpReadableStreamDefaultControllerFromUnderlyingSource` 
    - [x]  `ReadableStreamDefaultControllerMethods` implementation: [todo](https://github.com/wusyong/servo/blob/readablestream/components/script/dom/readablestreamdefaultcontroller.rs#L197)
         - [x] `GetDesiredSize`
         - [x] `Close`
         - [x] `Enqueue`
         - [x] `Error`
- [x] `ReadableBytesStreamController` WebIDL codegen
    - [x] `SetUpReadableByteStreamControllerFromUnderlyingSource` 
    - [x]  `ReadableBytesStreamControllerMethods` implementation: [todo](https://github.com/wusyong/servo/blob/readablestream/components/script/dom/readablebytestreamcontroller.rs#L137) 
        - [x] `GetByobRequest`
        - [x] `GetDesiredSize` 
        - [x] `Close`
        - [x] `Enqueue`
        - [x] `Error`
- [x] `ReadableStreamDefaultReader` WebIDL codegen: #32605
    - [x] `Constructor`: [todo](https://github.com/wusyong/servo/blob/readablestream/components/script/dom/readablestreamdefaultreader.rs#L34)
    - [x] `ReadableStreamDefaultReaderMethods` implementation: [todo](https://github.com/wusyong/servo/blob/readablestream/components/script/dom/readablestreamdefaultreader.rs#L56)
        - [x] `Read`
        - [x] `ReleaseLock`
        - [x] `Closed`
        - [x] `Cancel` 
- [x] `ReadableStreamBYOBReader` WebIDL codegen: #32605
    - [x] `Constructor`: [todo](https://github.com/wusyong/servo/blob/readablestream/components/script/dom/readablestreambyobreader.rs#L34) 
    - [x] `ReadableStreamBYOBReaderMethods` implementation: [todo](https://github.com/wusyong/servo/blob/readablestream/components/script/dom/readablestreambyobreader.rs#L53C6-L53C37)
        - [x] `Read`
        - [x] `ReleaseLock`
        - [x] `Closed`
        - [x] `Cancel` 
- [x]  `QueuingStrategy`: #32572
- [x]  `UnderlyingSource`: #32572

For anyone who is interested in contributing, here's what you could do:
- For "todo" item, please open PR against [my fork](https://github.com/wusyong/servo/blob/readablestream/), or wait for that interface is available in servo's branch.
- For "draft complete" or items that has a opened PR, please help me review and see if the implementation is correct.

**Comment by gterzian** [comment]
I don't think all the "todo" items can be done separately, I would say let's complete the WebIDL skeleton first, then we will have to look at everything again and come-up with a plan for the implementation.

**Comment by wusyong** [comment]
@gterzian I think you are right. I just opened https://github.com/servo/servo/pull/32602 but I think it will be super difficult to review.

The only missing WebIDL is `ReadableStream` left. I guess it's better to close that draft to fill the skeleton first.
