### ISSUE TITLE
[meta] embedding

### ISSUE THREAD

**Issue by delan** [servo/servo#30593]
* [ ] Adapt [wry](https://crates.io/crates/wry) to Rust libsimpleservo as proof of concept
* [ ] Build a Rust wrapper around C libsimpleservo
* [ ] Migrate from Rust libsimpleservo to the new Rust wrapper

**Comment by fabricedesre** [comment]
What's the benefit of going Rust -> C -> Rust ?

**Comment by mrobinson** [comment]
> What's the benefit of going Rust -> C -> Rust ?

The main benefit of this approach is the ability to ship a shared object.

**Comment by fabricedesre** [comment]
But wry is already pure Rust so it doesn't need that, right?

**Comment by mrobinson** [comment]
> But wry is already pure Rust so it doesn't need that, right?

Since Servo takes so long to build, being able to ship a shared object version of Servo will make it easier for embedders to use it.

**Comment by wusyong** [comment]
We are trying to update our entry method to use [raw window](https://github.com/tauri-apps/rfcs/pull/12) handle recently.
Wry itself doesn't handle other things but wrap around webview instance only. I just need to make sure `Servo` and other related types can work. I'll try the approach similar to `servoshell` first and then explore multiwindow next.

A shared object isn't that urgent IMHO. Defining a C API that is ergonomic enough is another challenge as well. I tried to deal with CEF's C API before, and the experience didn't go that well. What I think is better are shared objects for huge C++ dependencies like `mozangle` and `mozjs`. These are always the first blocker in fresh environment. Maybe we could just download and link to built shared libraries if users only want to compile servo itself. Another benefit is developers can dive into servo codebase and hack it directly. I found I often need to refactor some servo code too.

**Comment by sagudev** [comment]
Here is interesting blog post about dylib: https://robert.kra.hn/posts/2022-09-09-speeding-up-incremental-rust-compilation-with-dylibs/
I think something like that would be the best way for mozjs. mozangle is a bit more complicated on windows as we need it's produced dlls (libEGL.dll & libGLESv2.dll).

**Comment by delan** [comment]
@sagudev interesting! I didn’t realise it was possible to build a lib crate as a dylib unless we used the C ABI. I wonder if it will break monomorphisation or break if [type layout changes between runs](https://nullderef.com/blog/plugin-start/#_abi_unstability_its_much_worse_than_it_seems).

**Comment by sagudev** [comment]
Hm, I'm not entirely sure on stability of dylib, but thinking about it again maybe that's not the best way as we still need rust code generated by bindgen. We could just cache libmozjs static, but we might still need to run configure for bindgen so we cannot really eliminate it's build sys requirements.

**Comment by wusyong** [comment]
@sagudev It's okay to still running bindgen for build script as long as there's a static lib like [deno's v8 wrapper did](https://github.com/denoland/rusty_v8#binary-build) IMHO. People usually have trouble with C++ building setup instead of rust. Does spider monkey published their binary release already?

**Comment by sagudev** [comment]
@wusyong SpiderMonkey does offer prebuilds as artifacts on taskcluster. But we are patching SM in mozjs, so we would need to this for ourself. I have rough idea how this could work via automated CI jobs.

**Comment by wusyong** [comment]
Btw I saw mozangle also has patches but it seems they are trivial. Maybe we can try to pull angle artifact and link it for mozangle's case.

**Comment by wusyong** [comment]
As long as the building process can be easier, I'm happy to see any attempt. I think the main concern for `dylib` is unstable Rust ABI. But right now servo also has to stick to certain nightly version anyway. So maybe this is not a big concern for developing purpose.

**Comment by NetOpWibby** [comment]
BUMP
