### ISSUE TITLE
Unified thread pool and async runtime

### ISSUE THREAD

**Issue by wusyong** [servo/servo#32428]
**Describe the new feature:**
I brought some topics in zulip about there's [too many threads](https://servo.zulipchat.com/#narrow/stream/416779-Performance/topic/Too.20many.20threads) which leads to [high memory usage](https://servo.zulipchat.com/#narrow/stream/416779-Performance/topic/High.20memory.20usage). It seems when there's a parallel work, we spawn another thread or even thread pool. And the usage is still growing. @gterzian [suggested ](https://servo.zulipchat.com/#narrow/stream/416779-Performance/topic/High.20memory.20usage/near/426529900)we could use a component that would manage thread pools and async runtime based on config values. In order to make this happen, here are the steps I think we could do which can also reduce the amount of thread already along the way:

- [ ] Move [CoreResourceThreadPool](https://github.com/servo/servo/blob/main/components/net/resource_thread.rs#L522) into a lazy_static handle like [async_runtime::HANDLE](https://github.com/servo/servo/blob/main/components/net/async_runtime.rs)
- [ ] Refactor [CoreResourceManager](https://github.com/servo/servo/blob/main/components/net/resource_thread.rs#L469) and [ImageCacheImpl](https://github.com/servo/servo/blob/main/components/net/image_cache.rs#L411) to use the same thread pool.
- [ ] Move [async_runtime::HANDLE](https://github.com/servo/servo/blob/main/components/net/async_runtime.rs) and thread pool implementation into an individual crate component.
- [ ] Define the config values in `pref.json` and apply to this new crate.
- [ ] See if `webrender` and `mozjs` can also adopt these config. It seems they also have their own thread pools (`WRWorker` and `JS Helper`).
- [ ] See if other thread spawnings could be refactored to use this thread pool and async runtime instead.

**Comment by Mikopet** [comment]
I'm already looking into this. You could assign it to me.

**Comment by gterzian** [comment]
> Move [CoreResourceThreadPool](https://github.com/servo/servo/blob/main/components/net/resource_thread.rs#L522) into a lazy_static handle like [async_runtime::HANDLE](https://github.com/servo/servo/blob/main/components/net/async_runtime.rs)

I don't think this is a good idea, because the threadpool is already managed by the `CoreResourceManager`, to ensure it is properly [shut down](https://github.com/servo/servo/blob/e74075255bfef3f55acdfb4866fc2e0a9f5a9583/components/net/resource_thread.rs#L632), and it is shared with the file-manager via a `Weak`. This is the right structure already. 

> Refactor [CoreResourceManager](https://github.com/servo/servo/blob/main/components/net/resource_thread.rs#L469) and [ImageCacheImpl](https://github.com/servo/servo/blob/main/components/net/image_cache.rs#L411) to use the same thread pool.

This is not possible, because the image cache is [created in the script process](https://github.com/servo/servo/blob/e74075255bfef3f55acdfb4866fc2e0a9f5a9583/components/constellation/pipeline.rs#L525)(when in multiprocess mode), whereas the `CoreResourceManager` is [created in the "main" process](https://github.com/servo/servo/blob/e74075255bfef3f55acdfb4866fc2e0a9f5a9583/components/servo/lib.rs#L989), alongside the constellation. 

>  See if webrender and mozjs can also adopt these config. It seems they also have their own thread pools (WRWorker and JS Helper).

Very unlikely, to the point of not being worth looking into, in my opinion. 

> See if other thread spawnings could be refactored to use this thread pool and async runtime instead.

Perhaps, and if such an opportunity is discovered, it should first be discussed here before opening a PR. So it looks like this issue is essentially reduced to this item.

**Comment by wusyong** [comment]
> This is not possible, because the image cache is [created in the script process](https://github.com/servo/servo/blob/e74075255bfef3f55acdfb4866fc2e0a9f5a9583/components/constellation/pipeline.rs#L525)(when in multiprocess mode), whereas the `CoreResourceManager` is [created in the "main" process](https://github.com/servo/servo/blob/e74075255bfef3f55acdfb4866fc2e0a9f5a9583/components/servo/lib.rs#L989), alongside the constellation.

yeah I found that it might be included in different process later on. But at the same time, no one is really is using multiprocess mode. And last time time I checked it, it can't really work at all. I guess the next issue we should focus is if we can really work in multiprocess mode, and even run it by default.
