### ISSUE TITLE
ReadableStream: finish default controller and reader impl

### ISSUE THREAD

**Issue by gterzian** [servo/servo#32898]
Follow-up on https://github.com/servo/servo/pull/32730, and needs to target https://github.com/servo/servo/tree/readablestream-re-implementation

TODO: 

- [x] Fix use of `CanGc`. 
- [ ] Use `Dom` in native promise handlers as per https://github.com/servo/servo/issues/33604
- [x] Debug so we can get the same pass rate as now on the WPT tests.

Related to how the stream is used "natively" in Rust:
- [ ] Remove the current use of [`get_js_stream`](https://github.com/servo/servo/pull/32730/files#diff-ea8666cc30b1da7f1a13c2990763c958ef91f1d44209f02bf229d02e09fae7a1R230), which should be replaced by returning the actual `DomRoot<ReadableStream>`. This relates to the "native reading from a stream"  workflow.
- [x] Restructure the "native reading from a stream" [workflow](https://github.com/servo/servo/pull/32730/files#diff-ea8666cc30b1da7f1a13c2990763c958ef91f1d44209f02bf229d02e09fae7a1R306), used by Rust code, so that the code simply uses a `ReadableStreamDefaultReader`. The three methods to restructure are: [`read_a_chunk`](https://github.com/servo/servo/pull/32730/files#diff-ea8666cc30b1da7f1a13c2990763c958ef91f1d44209f02bf229d02e09fae7a1R307), `start_reading`, and `stop_reading`(mostly, or only, used in `components/script/body.rs`).
- [x] Optimize [`get_in_memory_bytes`](https://github.com/servo/servo/pull/32730/files#diff-09888dfa911f121670b8b905131455cf548d1816bf65bdeff76fb00f9e55e743R256)

Related to public JS methods of `ReadableStream`:
- [x] Implement [`Locked`](https://github.com/gterzian/servo/blob/79b7f153332446eba9b9f2b390f3e2f1839bd6eb/components/script/dom/readablestream.rs#L405)
- [x] Implement [`Cancel`](https://github.com/gterzian/servo/blob/79b7f153332446eba9b9f2b390f3e2f1839bd6eb/components/script/dom/readablestream.rs#L411)
- [x] Implement [tee](https://streams.spec.whatwg.org/#readable-stream-tee)
- [x] Fix rooting of composite reason when cancelling ReadableStream::tee https://github.com/servo/servo/issues/34580 fix: https://github.com/servo/servo/pull/34627

Related to `ReadableStreamDefaultController`:
- [x] Check the validity of [using `Dom<ReadableStreamDefaultController>`](https://github.com/servo/servo/pull/32730/files#diff-09888dfa911f121670b8b905131455cf548d1816bf65bdeff76fb00f9e55e743R32) in the `PullAlgorithmFulfillmentHandler `. 
- [x] [Handle fufillment of pull algo promise](https://github.com/servo/servo/pull/32730/files#diff-09888dfa911f121670b8b905131455cf548d1816bf65bdeff76fb00f9e55e743R37)
- [x] Start algorithm. https://github.com/servo/servo/pull/33586/files#diff-09888dfa911f121670b8b905131455cf548d1816bf65bdeff76fb00f9e55e743R199
- [x] [Handle rejection of pull algo promise](https://github.com/servo/servo/pull/32730/files#diff-09888dfa911f121670b8b905131455cf548d1816bf65bdeff76fb00f9e55e743R53)
- [x] Properly implement [`ValueWithSize`](https://github.com/servo/servo/pull/32730/files#diff-09888dfa911f121670b8b905131455cf548d1816bf65bdeff76fb00f9e55e743R61)
- [x] [`should_pull`](https://github.com/servo/servo/pull/32730/files#diff-09888dfa911f121670b8b905131455cf548d1816bf65bdeff76fb00f9e55e743R170)
- [x] [use the strategysizealgorithm](https://github.com/servo/servo/pull/32730/files#diff-09888dfa911f121670b8b905131455cf548d1816bf65bdeff76fb00f9e55e743R208) also [here](https://github.com/servo/servo/pull/32730/files#diff-09888dfa911f121670b8b905131455cf548d1816bf65bdeff76fb00f9e55e743R241).
- [x] [handle close requested](https://github.com/servo/servo/pull/32730/files#diff-09888dfa911f121670b8b905131455cf548d1816bf65bdeff76fb00f9e55e743R211)
- [x] [`close`](https://github.com/servo/servo/pull/32730/files#diff-09888dfa911f121670b8b905131455cf548d1816bf65bdeff76fb00f9e55e743R264)
- [x] [`error`](https://github.com/servo/servo/pull/32730/files#diff-09888dfa911f121670b8b905131455cf548d1816bf65bdeff76fb00f9e55e743R269)
- [x] `GetDesiredSize`
- [x] Implement the [Cancel steps](https://streams.spec.whatwg.org/#rs-default-controller-private-cancel)

Related to `ReadableStreamDefaultReader`:
- [x] Add constructor impl [here](https://github.com/servo/servo/pull/34064/files#diff-8fa92390cccc8be95f32344c311dbb4355203d03ac5ad8221bf52b3cdea90b71R281)
- [x] Make the [stream](https://github.com/servo/servo/pull/32730/files#diff-8fa92390cccc8be95f32344c311dbb4355203d03ac5ad8221bf52b3cdea90b71R92) mutable, and set it to null when apppropriate(and initially?). 
- [x] [`readable-stream-reader-generic-release`](https://github.com/gterzian/servo/blob/79b7f153332446eba9b9f2b390f3e2f1839bd6eb/components/script/dom/readablestreamdefaultreader.rs#L188)
- [x] Proper error types when [releasing](https://github.com/gterzian/servo/blob/79b7f153332446eba9b9f2b390f3e2f1839bd6eb/components/script/dom/readablestreamdefaultreader.rs#L190)
- [x] [`Closed`](https://github.com/gterzian/servo/blob/79b7f153332446eba9b9f2b390f3e2f1839bd6eb/components/script/dom/readablestreamdefaultreader.rs#L198)
- [x] [`Cancel`](https://github.com/gterzian/servo/blob/79b7f153332446eba9b9f2b390f3e2f1839bd6eb/components/script/dom/readablestreamdefaultreader.rs#L204C8-L204C13)

Related to all:
- [x] Check the [spec](https://streams.spec.whatwg.org/) for more things to do. 

I think the various parts could be done in parallel, items within one part are probably best done in one PR, but could perhaps be separated as well.

**Comment by gterzian** [comment]
cc @wusyong @Taym95

**Comment by gterzian** [comment]
> Related to public JS methods of

I am currently working on this part.

**Comment by Taym95** [comment]
> Related to ReadableStreamDefaultReader

I am working on this

**Comment by gterzian** [comment]
> I am working on this

Ok note that I ended-up doing a few things (`close`), in https://github.com/servo/servo/pull/33136

**Comment by gterzian** [comment]
Note: 

the Related to how the stream is used "natively" in Rust part can be done later, as in after we merge this into main, since it is more of a refactoring and optimization.

**Comment by gterzian** [comment]
I;ve just added "Implement [tee](https://streams.spec.whatwg.org/#readable-stream-tee)" above, because I realized we forgot about that. cc @Taym95 @wusyong

**Comment by gterzian** [comment]
I have also added "Implement the [Cancel steps](https://streams.spec.whatwg.org/#rs-default-controller-private-cancel)"

**Comment by gterzian** [comment]
After having had a closer look at `tee`, we should note it uses the cancel algorithm, so we probably should first do the cancel steps; but a partial implementation of tee before that should also be possible.
