### ISSUE TITLE
Tracking: use Rust font libraries (HarfRust, Skrifa/Fontations, etc)

### ISSUE THREAD

**Issue by ebraminio** [servo/servo#33482]
This issue tracks Servo adoption of Rust font processing libraries (and eliminating C font processing libraries).

## Background

One of the most significant sources of C code in Servo are it's font handling dependencies: HarfBuzz, FreeType, fontconfig, woff2, and ots. Many of these projects now have Rust rewrites:

- https://github.com/googlefonts/fontations includes Skrifa port of FreeType to Rust
- https://github.com/harfbuzz/harfrust is a port of HarfBuzz to Rust
- https://github.com/nicoburns/wuff ports woff2 to Rust
- Fontconfig and ots do not yet have a Rust port.

Skrifa and HarfRust are notably Google sponsored projects (Skrifa ships in Chrome, HarfRust in on track to ship in Chrome this year).

## Sub-Projects

- [x] https://github.com/servo/servo/pull/46439
- [ ] https://github.com/servo/servo/pull/38707
- [ ] Add `skrifa` backend to `servo-fonts` crate
- [ ] Add `skrifa` backend to `wr_glyph_rasterizer
   - WIP branch: https://github.com/servo/webrender/compare/fefa95d2c84f359fecab56013fa2c6b1978a72e6...fontations?expand=1

## CoreText / DirectWrite

It is currently not a goal to remove the CoreText or DirectWrite backends from Servo, although it is a goal to make it possible to build Servo with the Rust backend (and those backends disabled) on macOS and Windows. Whether it makes sense to retain the FreeType backend long-term is an open question.

**Comment by mrobinson** [comment]
We can use fontations for some things and this is definitely in the plan, but I don't think we can completely replace FreeType / CoreText / DirectWrite at the moment as our glyph rasterizer uses those dependencies. For the Servo part though, perhaps we can remove our dependencies on system libraries at some point.

I'm curious how the fontations port of Chrome handles font bundles on macOS though. The system font matcher returns postscript names, but not indexes into bundles. This is the main reason we end up having to pass around CoreText fonts more often on macOS.

**Comment by drott** [comment]
> I'm curious how the fontations port of Chrome handles font bundles on macOS though. The system font matcher returns postscript names, but not indexes into bundles. This is the main reason we end up having to pass around CoreText fonts more often on macOS.

Do you mean `.dfont` bundles, or `.ttc`'s? We currently do not have support for `.dfont` bundles in Fontations - and in Chrome we do use CoreText for system fonts. On Mac we plan to use Fontations mainly for formats unsupported by the system, such as COLRv1, CFF2, CBDT/CBLC etc. - which usually arrive as web fonts and are not installed fonts.

**Comment by mrobinson** [comment]
> Do you mean `.dfont` bundles, or `.ttc`'s? We currently do not have support for `.dfont` bundles in Fontations - and in Chrome we do use CoreText for system fonts. On Mac we plan to use Fontations mainly for formats unsupported by the system, such as COLRv1, CFF2, CBDT/CBLC etc. - which usually arrive as web fonts and are not installed fonts.

I was referring to `.ttc` here. Do I understand correctly that `.ttc` bundles on the system are still handled by `CoreText` and Fontations is mainly aimed at web fonts?

**Comment by drott** [comment]
Fontations supports `.ttc` by using file + index, but depending on how font matching is done, with an own database or with CoreText's match functions, if using the latter it might be a bit tricky to get the index out and map that to Fontations, but doable. 

> Do I understand correctly that .ttc bundles on the system are still handled by CoreText and Fontations is mainly aimed at web fonts?

Yes, that's the main focus. We stylle use system renderers opportunistically. But on system where FreeType is the renderer now, we move to Fontations (Linux, Android, ChromeOS).

**Comment by nicoburns** [comment]
>  I don't think we can completely replace FreeType / CoreText / DirectWrite at the moment as our glyph rasterizer uses those dependencies.

FWIW, there's a fork of `wr_glyph_rasterizer` that adds a Swash backend and it's like 300 LOC. I suspect getting webrender using fontations wouldn't be that hard https://github.com/declantsien/webrender/blob/master/wr_glyph_rasterizer/src/backend/swash/font.rs

**Comment by nicoburns** [comment]
> depending on how font matching is done, with an own database or with CoreText's match functions, if using the latter it might be a bit tricky to get the index out and map that to Fontations, but doable.

@drott How does Chrome do font matching? Is it using it's own database or CoreText match functions?

I'm not 100% on this, but I believe that it's possible to get CoreText to load a font from file, and thus that one can use their own font database and matching code and still rasterize using CoreText if so desired.

**Comment by nicoburns** [comment]
> The system font matcher returns postscript names, but not indexes into bundles. This is the main reason we end up having to pass around CoreText fonts more often on macOS.

Looks like webrender's CoreText glyph rasterizer accepts fonts as either a `(name: String, path: String)` or `(raw_bytes: Arc<Vec<u8>>, index: u32)` pair (and then recreates a CoreText/CoreGraphics handle to it itself) anyway:

- https://github.com/servo/webrender/blob/main/wr_glyph_rasterizer/src/platform/macos/font.rs#L255
- https://github.com/servo/webrender/blob/main/wr_glyph_rasterizer/src/platform/macos/font.rs#L269
- https://github.com/servo/webrender/blob/main/webrender_api/src/font.rs#L64

**Comment by drott** [comment]
> @drott How does Chrome do font matching? Is it using it's own database or CoreText match functions?

Chrome matches using CoreText plus some own logic, but does not build an own database.

**Comment by mrobinson** [comment]
> Looks like webrender's CoreText glyph rasterizer accepts fonts as either a `(name: String, path: String)` or `(raw_bytes: Arc<Vec<u8>>, index: u32)` pair (and then recreates a CoreText/CoreGraphics handle to it itself) anyway:
>     * https://github.com/servo/webrender/blob/main/wr_glyph_rasterizer/src/platform/macos/font.rs#L255
>     * https://github.com/servo/webrender/blob/main/wr_glyph_rasterizer/src/platform/macos/font.rs#L269
>     * https://github.com/servo/webrender/blob/main/webrender_api/src/font.rs#L64

Yes, and Servo uses that when possible. The issue is that Servo, like Chrome matches using `CoreText` which will can give you both a font filename and a PostScript name. The PostScript name in some manner maps to an indexed font in the collection, but I'm not sure if there is a reliable method to map from that name to the index in the font. It seems that macOS might do some adjustment to the name internally that makes this mapping difficult. Another option might be to ask CoreText for all table data and piece together a new font blob -- but I worry a bit about performance. I'm curious what Chrome does, if anything to overcome this issue.

**Comment by nicoburns** [comment]
> The PostScript name in some manner maps to an indexed font in the collection, but I'm not sure if there is a reliable method to map from that name to the index in the font.

I believe one approach here would be to open the file and iterate over the fonts in the collection until the one with the matching name is found. This might sound slow, but I believe it is likely to be fast in practice as:

- Fonts are typically memory mapped
- You only have to read the headers of the fonts, so not many memory pages even for large fonts
- Fonts are typically *already* memory mapped by the OS for other processes. And the headers likely sit in the kernel page cache.
- The result could be cached for later lookups.

> It seems that macOS might do some adjustment to the name internally that makes this mapping difficult.

That would definitely be a problem if true, but CoreText appears to have a method that returns the "postscript name" (`CTFontCopyPostScriptName`), and it would be a bit odd if that was altered given it is a well-defined term with a long history.

**Comment by mrobinson** [comment]
I think the issue is that font enumeration on macOS doesn't just return the family name and PostScript name, but some stringified combination of family name, PostScript name, and named instance. We would need to know how CoreText maps that to an actual font instance in a font file or TTC. In addition, I don't think every font provided by the system has a file on all platforms. For instance, in the cases where Gecko needs the font data for a particular system font, it asks DirectWrite for the data and in the case of CoreText produces an entirely new blob of font data by piecing the tables back together. I think this would be too expensive to do when unnecessary. On the other hand, we'll need to figure this out for `vello` integration.

**Comment by nicoburns** [comment]
@mrobinson I've done some investigation into this. Specifically, I've written a [small test script](https://github.com/nicoburns/fontlist-experiment/blob/main/src/main.rs) that:

- Uses some core text font enumeration code I took from servo to iterate over all system fonts (hopefully I got the relevant code).
- This gives me an identifier consisting of a path and a postscript_name for each font.
- For each font identifier, I then:
    - Memory map the file using `memmap2`
    - Use `read_fonts` to read the memory mapped bytes and:
       - Determine whether the file is a single font or a collection
       - In the case of a collection we iterate over each font in the collection, and then each name record in the font, until we find a name record that (is of the POSTSCRIPT_NAME type and) matches the postscript_name we got from core text.
       - Return the index (within the collection) of the font which contained this name record.
       
This works for every font that is returned from the CoreText API on my system.

It takes ~180us (note: micro not milli) for the first font in a collection, and then ~10ms for subsequent fonts in the same collection. The entire script runs in ~150ms (milli this time).

So I think that Servo could keep it's existing font enumeration code. And if it needs to pass a font handle to skrifa or vello then it can look up the index as I have done here (and that result can of course be cached).

**Comment by mrobinson** [comment]
@nicoburns Thanks for the script. I'll try it out on my system when I get a moment. If this works, you are probably right that we could use it to establish a mapping between the `CoreText` font and a blob of data we can send to `vello`. For `skrifa`, I don't think we need to do this mapping. Instead we can probably just implement a platform-specific [TableProvider](https://docs.rs/read-fonts/0.22.3/read_fonts/trait.TableProvider.html) and avoid the overhead of trying to map the PostScript name.

**Comment by nicoburns** [comment]
> @nicoburns For `skrifa`, I don't think we need to do this mapping. Instead we can probably just implement a platform-specific [TableProvider](https://docs.rs/read-fonts/0.22.3/read_fonts/trait.TableProvider.html).

Ah interesting. Vello is using `skrifa` for all it's font-processing needs, so I'm pretty sure it wouldn't be too hard to make it generic over an `impl TableProvider` if that is needed.

**Comment by mrobinson** [comment]
@nicoburns Oh, interesting point. Right now the data passed to Vello is a [Font](https://docs.rs/peniko/0.2.0/peniko/struct.Font.html), but I suppose the interface could change to accept an implementation of a `TableProvider` as you say.

**Comment by satmandu** [comment]
Looks like Chromium is moving to [Skrifa](https://github.com/googlefonts/fontations/tree/main/skrifa) from Freetype: https://developer.chrome.com/blog/memory-safety-fonts

**Comment by nicoburns** [comment]
The initial release of the new HarfRust crate is now available https://crates.io/crates/harfrust. Performance optimization work to catch HarfRust up to HarfBuzz is ongoing.

Details on current status are documented in https://github.com/harfbuzz/harfrust/blob/main/HARFBUZZ.md

**Comment by nicoburns** [comment]
The quality isn't great yet (main issue is glyph getting clipped due to dimensions/offsets not being computed correctly), but this is Servo running on HarfRust (https://github.com/servo/servo/pull/38707) and using Skrifa (via `vello_cpu`) for glyph rasterization (https://github.com/servo/webrender/pull/4872). FreeType is still being used for metrics extraction:

<img width="1899" height="1193" alt="Image" src="https://github.com/user-attachments/assets/a8868251-8022-49b1-9848-6820e939adff" />

**Comment by nicoburns** [comment]
WIP HarfRust/Skrifa PR for resvg https://github.com/linebender/resvg/pull/922

**Comment by nicoburns** [comment]
https://github.com/emilk/egui/pull/7694 implements skrifa + vello_cpu glyph rasterization with what looks like a reasonable method of computing the glyph boundaries that could probably be adapted for WebRender.

**Comment by nicoburns** [comment]
New fontations API (in addition to the existing one) likely coming soon: https://github.com/googlefonts/oxidize/blob/new-font-api/text/2026-05-01-a-new-font-api.md. This is driven in large parts by performance requirements from HarfRust.

**Comment by jschwe** [comment]
@nicoburns Is font sanitizing also provided by fontations, meaning we could drop fontsan at some point?

**Comment by nicoburns** [comment]
Not really. I would be comfortable opening unsanitized fonts with fontations, but that doesn't then cause them to be santized for other libraries.

If we implement fontations-only builds (should be feasible), then we could drop fontations *for those builds*. But I suspect we'll probably want to continue using CoreText on macOS and DirectWrite on windows.

One option would be to only use CoreText/DirectWrite for system fonts and always use fontstions foe web fonts. Perhaps we would then be happy not to sanitize system fonts?

**Comment by mrobinson** [comment]
In order to use only fontations for web fonts we would need to implement a font rasterizer (I guess on top of vello?) and the necessary caching layers. Currently system fonts are not sanitized, so if that allows us to no longer sanitize fonts, then we can remove our dependency on fontsan.

**Comment by nicoburns** [comment]
> In order to use only fontations for web fonts we would need to implement a font rasterizer (I guess on top of vello?) and the necessary caching layers.

I have plans to do this at some point (if nobody else gets to it first). Plan is:

- Combine `skrifa` with `vello_cpu` to rasterize glyphs (and compute bounding boxes)
- Add a backend to `wr_glyph_rasterizer` uses this code (plug into `wr_glyph_rasterizer`'s existing caching logic

Upstream (Mozilla) have said they're happy to accept a patch for this in principle (obviously subject to review of the implementation) so long as it is feature flagged and they can turn it off (for binary size reasons).

https://github.com/servo/webrender/pull/4872 is a prototype of this which does render glyphs, but the quality is poor and the bounding boxes are incorrect (so the glyphs get incorrectly clipped).

I don't think WebRender currently has a way to send web fonts to a different backend to system fonts atm. But upstream *may* be interested in this as I believe that this is the approach that Chrome takes. I'm also not sure how COLR fonts are handled in either Firefox or Servo (does Servo support these at all?) (is Firefox using Skia Raster like it does for SVG?). I believe the current version of `wr_glyph_rasterizer` does not support these, but a fontations backend potentially could if we wanted it to.

**Comment by mrobinson** [comment]
> I'm also not sure how COLR fonts are handled in either Firefox or Servo (does Servo support these at all?) (is Firefox using Skia Raster like it does for SVG?). I believe the current version of `wr_glyph_rasterizer` does not support these, but a fontations backend potentially could if we wanted it to.

COLRv0 fonts can sometimes be handled by the system rasterizer, but COLRv1 fonts are handled outside of WebRender in Gecko. We support COLRv0, but not COLRv1. This is a big missing piece of Servo font rasterization. I think that DirectWrite supports COLRv1, but Freetype does not have builtin support for rasterization.

**Comment by nicoburns** [comment]
As of https://github.com/servo/servo/pull/46439, Servo is now using safe Rust code (https://github.com/nicoburns/wuff) for WOFF decoding.

**Comment by jschwe** [comment]
@nicoburns Do you know what the status is for the other items? Harfrust seems to be working quite well now (ignoring performance) - is the stability good enough that we can consider merging it with a feature and pref?
What about fontations, have their been any developments there?

**Comment by nicoburns** [comment]
> [@nicoburns](https://github.com/nicoburns) Do you know what the status is for the other items? Harfrust seems to be working quite well now (ignoring performance) - is the stability good enough that we can consider merging it with a feature and pref? What about fontations, have their been any developments there?

The HarfRust PR is absolutely ready to go behind a flag. It could probably even be the default if we wanted it to be. There are still some discrepancies compared to HarfBuzz, but they're minor. The main thing to figure out here would be how to we want to setup the feature flags / prefs.

Regarding Fontations/Skrifa replacing FreeType, I think there are two tasks:

1. Write a `fontations` backend for the `servo-fonts` crate as alternative to the `freetype` backend here: https://github.com/servo/servo/tree/main/components/fonts/platform. This should probably be a straight port of the existing `freetype` backend, and may want to share code in places (i.e. there is no Rust replacement for `fontconfig` so the `font_list` code would likely want to be used by the new backend).

    (it would also be possible to incrementally port the freetype backend, but some Servo developers have previously expressed a preference for it being a separate backend, so that's probably the lowest friction way to proceed).
2. Write a `fontations` backend for `wr_glyph_rasterizer` here: https://github.com/servo/webrender/tree/main/wr_glyph_rasterizer. Unlike FreeType, `skrifa` doesn't include a rasterizer (it just does scaling/hinting - which is the hard part), so this would need to be `skrifa`+`vello_cpu`, `skrifa`+`zeno`, `skrifa`+`tiny_skia` or similar. Long-term there is interest in writing a specialized, fast, state-of-the-art glyph rasterizer in Rust, but we shouldn't expect that to available in the short term.

    I have a partially working branch for this here: https://github.com/servo/webrender/tree/fontations (anyone should feel free to take over). There is also this older branch which implements a backend using the `swash` crate: https://github.com/servo/webrender/tree/swash-backend (from the creator of emacs-ng which is/was using WebRender).

(Mozilla maintainers of WebRender have a expressed willingness to accept a Fontations-based rendering backend upstream so long as it's behind a flag)

Neither of these is blocked. 1 is actually probably quite straightforward. 2 is a little more involved but definitely achievable

**Comment by nicoburns** [comment]
Some really significant performance improvements (~30%) coming soon to both HarfBuzz and HarfRust! HarfRust also seems to be roughly at parity with HarfBuzz now (within 10%) when calling directly from Rust (no HarfBuzz C api compatibility layer). [#parley > HarfRust performance tracking @ 💬](https://xi.zulipchat.com/#narrow/channel/205635-parley/topic/HarfRust.20performance.20tracking/near/621585482)
