### ISSUE TITLE
Enable ImageBitmap by default

### ISSUE THREAD

**Issue by jdm** [servo/servo#34112]
The DOM interface is gated behind `dom.imagebitmap.enabled`, which is disabled by default.

Spec: https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#imagebitmap

Known missing APIs:
* [x] close https://github.com/servo/servo/pull/34124
* [x] ImageOrientation default has been renamed from "none" to "from-image" https://github.com/servo/servo/pull/34149
* [ ] the interface should be serializable and transferrable

Test coverage:
* https://github.com/servo/servo/tree/main/tests/wpt/meta/html/canvas/element/manual/imagebitmap

We currently fail all tests because we never migrated the preference from the 2013 layout results.

**Comment by simonwuelker** [comment]
To add to the "known issues":

* `window.createImageBitmap` does not follow the spec. For example, we should [crop to the source rectangle with formatting](https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#cropped-to-the-source-rectangle-with-formatting) 
* [`ImageBitmapSource`](https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#imagebitmapsource) is missing multiple variants because [`CanvasImageSource`](https://html.spec.whatwg.org/multipage/canvas.html#canvasimagesource) is incomplete
* [`ImageBitmapSource`](https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#imagebitmapsource) can be a `CSSStyleValue`, for some reason [`CanvasImageSource`](https://html.spec.whatwg.org/multipage/canvas.html#canvasimagesource) allows this. The spec does not.

I don't think all of these should block enabling the interface by default, but it's worth noting them down anyways

**Comment by sagudev** [comment]
not done yet

**Comment by tharkum** [comment]
@jdm, @sagudev < 

There is requirement to support optional scaling on [image bitmap creation](https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#cropped-to-the-source-rectangle-with-formatting) (Step 7).

I didn't find any scaling function out of box in Servo (did I miss something?).
I am planning to use third-party library for it.
Are there are some restrictions with LICENSE? Smth else?

Candidates:
1. Resize (https://crates.io/crates/resize) - single-threaded, simple
2. Fast Image Resize (https://crates.io/crates/fast_image_resize) - single/multi-threaded, SIMD
3. ????

**Comment by tharkum** [comment]
It's not yet done. NEED to implement the following parts:
1. Crop with formating
2. Bitmap queue
3. Remove from experimental feature
4. Some minor issues...

**Comment by jdm** [comment]
> [@jdm](https://github.com/jdm), [@sagudev](https://github.com/sagudev) <
> 
> There is requirement to support optional scaling on [image bitmap creation](https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#cropped-to-the-source-rectangle-with-formatting) (Step 7).
> 
> I didn't find any scaling function out of box in Servo (did I miss something?). I am planning to use third-party library for it. Are there are some restrictions with LICENSE? Smth else?
> 
> Candidates:
> 
>     1. Resize (https://crates.io/crates/resize) - single-threaded, simple
> 
>     2. Fast Image Resize (https://crates.io/crates/fast_image_resize) - single/multi-threaded, SIMD
> 
>     3. ????

Licensing is the only restriction. If it passes test-tidy's license check them it works.

**Comment by sagudev** [comment]
Maybe it's worth checking that library support all [resizequality](https://html.spec.whatwg.org/multipage/imagebitmap-and-animations.html#resizequality) options.

**Comment by tharkum** [comment]
FYI < I looked at three packages (image/resize/fast_image_resize) and decided to implement the ImageBitmap resize functionality based on the "image" package (already in dependencies), even if the "fast_image_resize" package would have better performance on large images (multi-threading/SIMD).

Porting from "image" to "fast_image_resize" could be done as a separate task (needs to test on different platforms and confirm performance improvements).

**Comment by tharkum** [comment]
I propose to remove `ImageBitmap` from experimental feature list (`dom.imagebitmap.enabled`)
because at current moment almost all major tests are passed except specific CanvasImageSource tests
(vector `HTMImageElement`, bitmap/vector `SVGImageElement`) and EXIF image orientation.

WDYT?

**Comment by jdm** [comment]
You mean remove it from the experimental list and enable it by default? I agree!

**Comment by mrobinson** [comment]
Sounds good to me. I would also remove the preference entirely.
