### ISSUE TITLE
Support Web Components

### ISSUE THREAD

**Issue by gterzian** [servo/servo#34319]
As per [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Web_components), Web Components is "is a suite of different technologies allowing you to create reusable custom elements". This issue is a place to track our support for these technologies. 

- [x] [`[CustomElementRegistry](https://html.spec.whatwg.org/multipage/custom-elements.html#customelementregistry)`](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-api). We have [the interface](https://github.com/servo/servo/blob/527e2d426d1101b281e5b30b870859d44425465a/components/script/dom/customelementregistry.rs#L335), the status of its capabilities is unknown. 
- [x] Shadow DOM: tracked at https://github.com/servo/servo/issues/34318 (and includes some of the below)
- [ ] [HTML templates elements](https://html.spec.whatwg.org/multipage/scripting.html#the-template-element): we have the [interface](https://github.com/servo/servo/blob/527e2d426d1101b281e5b30b870859d44425465a/components/script/dom/htmltemplateelement.rs#L22), the status of its capabilities is unknown.
- [x] [`HTMLSlotElement`](https://html.spec.whatwg.org/multipage/scripting.html#the-slot-element): doesn't seem to be supported yet. 
- [ ] [Custom elements](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements#types_of_custom_element): I don't know.

**Comment by jdm** [comment]
We implemented custom elements and the registry as a gaoc project. Lots of tests are passing but there's still room for improvement: https://wpt.fyi/results/custom-elements?label=master&label=experimental&product=chrome&product=firefox&product=servo&aligned

**Comment by jdm** [comment]
I think we can close this in favour of issues filed about any remaining specific bugs.
