### ISSUE TITLE
Tracking issue: CSS Grid

### ISSUE THREAD

**Issue by nicoburns** [servo/servo#34479]
**This issue tracks progress in implementing CSS Grid:**

- https://www.w3.org/TR/css-grid-1/
- https://www.w3.org/TR/css-grid-2/

## Features

- [x] WPT testing (https://github.com/servo/servo/pull/34052)
- [x] Initial support (https://github.com/servo/servo/pull/32619)
- [ ] https://github.com/DioxusLabs/taffy/issues/750 (used by wikipedia)
- [ ] https://github.com/DioxusLabs/taffy/issues/550
- [ ] https://github.com/DioxusLabs/taffy/issues/751
- [ ] https://github.com/DioxusLabs/taffy/issues/752
- [ ] https://github.com/DioxusLabs/taffy/issues/213
- [ ] https://github.com/DioxusLabs/taffy/issues/225

## Bugs

- [ ] CSS Grid algorithm sometimes panics with `auto-fit` repetition is used
- [ ] Some absolute position WPT tests are failing

## Performance

- [ ] https://github.com/servo/servo/pull/34352

**Comment by mars-json** [comment]
Hello, I was doing CSS+HTML code sniplets for my work, testing new layout for web pages.
Sniplets are working fine in Chromium and Firefox.
But CSS Grid-related part is failing in Servo.
What is the best way to provide feedback on those bugs?
I am ready to provide minimized sniplets.

**Comment by jdm** [comment]
@mars-json First make sure you enable experimental feature mode (https://servo.org/download/#:~:text=Enable%20experimental), then you can file issues with minimized snippets for anything that still doesn't look right!

**Comment by mars-json** [comment]
I launched Servo via CLI, as
`./servoshell --enable-experimental-web-platform-features 
 `
And grid testcase which I was testing looks ok.
Why Grid support is not enabled by default in Servo 0.1.0?

**Comment by jdm** [comment]
> I launched Servo via CLI, as `./servoshell --enable-experimental-web-platform-features ` And grid testcase which I was testing looks ok. Why Grid support is not enabled by default in Servo 0.1.0?

Because the feature is incomplete still.

**Comment by SpeeQz1** [comment]
@jdm Any progress on this issue? When enabling the experimental features (`./servoshell --enable-experimental-web-platform-features`) it seems to crash when opening the website https://mintguide.miraheze.org/wiki/Linux_Mint (related to issue https://github.com/servo/servo/issues/41357).

**Comment by nicoburns** [comment]
@SpeeQz1 I believe https://github.com/servo/servo/issues/41207 is the remaining blocker for enabling CSS Grid by default, and is the issue tracking the crash on https://mintguide.miraheze.org/wiki/Linux_Mint (with experimental features enabled).

**Comment by nicoburns** [comment]
An update on WPT progress:

The raw numbers for Flexbox and CSS Grid from https://servo.org/wpt are as follows:

| Area | Tests | Subtests|
| --- | --- | --- |
| css/css-flexbox  | 78.5% |	(3,548/5,688) 62.3% |
| css/css-grid       | 37.2% |	(7,287/15,933) 45.7% |

However, that includes the Subgrid and Grid Lanes tests (which isn't very fair seeing as those are separate specs that we're not even attempting to support yet). If you exclude those tests (there are 312 subgrid + 3256 grid-lanes = 3568 tests according to https://wpt.fyi/results/css/css-grid?product=chrome%5Bexperimental%5D&product=firefox%5Bexperimental%5D&product=safari%5Bexperimental%5D&product=servo&product=ladybird) then you get 7,287 / (15,933 - 3,568) = 12,365. And 7,287/12,365 comes out at 58.9%.

All of which is to say that, going by WPT pass percentages, our implementation of the base CSS Grid specification ([css-grid-1](https://www.w3.org/TR/css-grid-1)) is almost as good as our implementation of Flexbox these days (58.9% vs 62.3% for Flexbox).

**Comment by soerenmeier** [comment]
Thanks for improving grid support this much, i tried 0.1 and for grid it seem like all alot of stuff didn't work yet. but I just build the main branch (with --enable-experimental-web-platform-features) and almost everything works nicely now. What I notice is that some cells like to take to much space, like the listing on this page: https://berncity.ch/unsere-mitglieder (on the member list). Is there an open issue or something for tracking this.
If there are issues specific to grid that are good for a servo beginner (I'm not familiar with taffy or this codebase), I would like to contribute.

Ps. Sorry if this comment is off topic or in the wrong place.

**Comment by jdm** [comment]
https://github.com/servo/servo/issues?q=state%3Aopen%20label%3A%22A-layout%2Fgrid%22 is this list of known grid layout issues. It would be really helpful to minimize the page layout from https://berncity.ch/unsere-mitglieder into the smallest html and css that can show the problem. That would help identify if it's a unique issue that we should track!

**Comment by nicoburns** [comment]
>  What I notice is that some cells like to take to much space, like the listing on this page: https://berncity.ch/unsere-mitglieder (on the member list). Is there an open issue or something for tracking this.

This looks like it might be an instance of https://github.com/servo/servo/issues/41422. The grid items on that page have `width: 100%` which should resolve against the grid column width (which would be ~33% in this case as there are  3 columns all of size `1fr`), but due to a bug in Taffy (upstream issue: https://github.com/DioxusLabs/taffy/issues/920) percentages for grid items currently resolve against the grid container width instead.

**Comment by soerenmeier** [comment]
Thanks, yeah the issue is `width: 100%`. Will gladly open issues when I find ones with a good reproducer. Cool work!
