### ISSUE TITLE
Tracking issues:  embedding API

### ISSUE THREAD

**Issue by wusyong** [servo/servo#34522]
**This issue tracks progress in implementing ergonomic embedding API**

**Status:**

- Servoshell could already serve as certain kind of webview library.
- UI element is built by Egui currently.
- prior art of embedding https://github.com/servo/servo/issues/30593
- https://github.com/servo/servo/pull/34371 as an experiment draft to see how could such API be.

## Winit support

- [x] API to create Servo instance from winit context(see winit minimal example)
- [x] API to handle [ApplicationHandler](https://docs.rs/winit/latest/winit/application/trait.ApplicationHandler.html) #34638
- [x] Minimal winit example #35119

## Rendering Context 

- [x] Turn rendering context into a trait #34888 #35052
  - [x] clarifies Compositor usage
  - [x] clarifies WebGL usage
  - [x] clarifies WebXR usage https://github.com/servo/servo/pull/34813
  - [x] clarifies media usage (only requires display handle)
- [ ] Simplify trait methods #35251 

## Internal structure

- [x] Decouple window and rendering context #34780
- [ ] Cleanup compositor usage
- [x] Cleanup/simplify opt/pref setup #34966 #34994

## WebView types

- [x] WebView handle #35119
- [ ] WebView delegate #35196

## GTK support

- [ ] Implement `RenderingContext` trait to `GLArea`
- [ ] Make sure Servo event cycles work with GTK's event loop
- [ ] Define ServoGTK/ServoGLArea with `glib::wrapper` macro

## Additional features

- [ ] `<web-view>` element support
- [ ] Custom WebView type
    - [ ] chrome/UI element
    - [ ] context menu
    - [ ] dialog

**Comment by wusyong** [comment]
@gterzian I create the meta issue regarding external/emebdded use of Servo. We can discuss this in next Monday triage and see how can we refactor current servoshell to achieve these. Or perhaps seeking another port.

**Comment by wusyong** [comment]
@nicoburns I create the item `Create rendering context from existing surface` that might suit your need. Current `servoshell` can create webview inside `egui` window, but it forces `egui` to accept `surfman`'s context. If we want users to use our embedding APIs, I assume it's servo needs to accept their context which is usually `glutin`.

But before we look into creating from surface, I think we should start with winit first since it's the main tool for majority of the rust ecosystem. Once I finished first two items in winit support. Perhaps we will have better idea on how to support custom surface.

**Comment by wusyong** [comment]
Note to self about some rendering context usgage in media and wegl. So I don't need to check again everytime I look into them.

For media, we can simply provide display handle like webxr. But some platforms need egl_context handle as well.

For WebGL, it also creates its own surfman context in WebGL thread as well. The only problem is webgl's webrender image handler is created in main thread which use existing rendering context to create surface textures. Perhaps it could route the channel like media handler does, and lock/unlock surface textures in WebGL thread actually?

**Comment by delan** [comment]
Thanks for creating this issue. There is also #30593, so perhaps it would be good to migrate the remaining tasks here, or at least link to it from this issue so we can consult the prior art?

@mrobinson and I think libservo is the best place to develop a more ergonomic embedding API. We expect app developers to consume libservo, like servoshell does, rather than consuming it indirectly via servoshell. Our research into competing webview libraries like WebKitGTK showed us that our “minimal” example can be made far more ergonomic:

- servoshell’s App::handle_events logic should be done in libservo as an impl detail
- embedders should control Servo with methods, not crafting EmbedderEvent values
- embedders should respond to Servo with a delegate trait, not handling EmbedderMsg values

I wonder if we can use [Cargo examples](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#examples) as a way to iterate on the embedding API, since servoshell is so complex now. I’m working on a minimal winit-based example in #35118.

**Comment by wusyong** [comment]
@delan Thanks for the response! I've added the prior art issue to the top.
I also have a PR that tries to make the [winit handling](https://github.com/servo/servo/pull/34371/files#diff-dbfb356108c9d0804992e8b3a893f51b729c5e8fa1fa8075310831c8e2e37d98R18) more ergonomic. However, it took another approach to pack everything together.

I basically agree with the goals you list. I know servo shell is so complex nowadays, and I struggle to update it, which causes slow progress. However, adding examples will still make it complicated to iterate, I believe. Every time I would like to update the interface, we have to make sure all targets can be built. If we add winit minimal, that means we have 4 targets that need to take care (servo shell, winit_minimal, simple_servo, OHOS). I wonder what the best way to iterate API could be.

Right now, I'm focussing on making rendering context generic https://github.com/servo/servo/issues/34888. And next will be the `Webview` trait which I belive is very close to he delegate trait you list. @mrobinson has [a topic in Zulip](https://servo.zulipchat.com/#narrow/channel/437943-embedding/topic/Starting.20work.20on.20the.20.60WebView.60.20interface) as well. I think before we actually add it, we should also clean up several traits like `WindowMethods` and `EmbedderCallbacks`

**Comment by delan** [comment]
> Every time I would like to update the interface, we have to make sure all targets can be built. If we add winit minimal, that means we have 4 targets that need to take care (servo shell, winit_minimal, simple_servo, OHOS). I wonder what the best way to iterate API could be.

That’s true. I’m not sure if that can be solved completely, but I suspect keeping the targets up to date will get easier over time, as our API improves. I’m also hoping the minimal example will be worth the additional effort, since it gives us a clearer idea of how ergonomic our API is.

**Comment by wusyong** [comment]
> That’s true. I’m not sure if that can be solved completely, but I suspect keeping the targets up to date will get easier over time, as our API improves. I’m also hoping the minimal example will be worth the additional effort, since it gives us a clearer idea of how ergonomic our API is.

Hmm let's see how it goes then. Perhaps it won't be a problem if we are active developing it. Or maybe we let example less restricted. ie if they break, they break. We just fix it in follow up commits.

**Comment by mrobinson** [comment]
> 

> Hmm let's see how it goes then. Perhaps it won't be a problem if we are active developing it. Or maybe we let example less restricted. ie if they break, they break. We just fix it in follow up commits.

I'm okay with this. Once the API is a bit more stable we can start building examples on CI.

**Comment by wusyong** [comment]
Updated a few items to reflect what we are doing. The major update is we are now working on WebView types for better ergonomic usages.

I also listed some GTK items which I feel like is a great starter to test our `RenderingContext` trait. I'll update my demo once I can create it through GLArea's context.

**Comment by emmyoh** [comment]
If support for embedding Servo in GTK apps arrives, I'd be interested in porting [Oku](https://okubrowser.github.io) to Servo.

**Comment by tvanderstad** [comment]
Not sure if you're looking for "me too"s but, when the embedding API is available, I'm interested in using Servo to render inline html in Lockbook, a markdown notes app similar to Bear and Obsidian.

**Comment by tvanderstad** [comment]
@jdm Thanks for linking!

It looks like there are issues with multiple webviews if I'm understanding correctly. I saw an unchecked task item on the "prior art of embedding" [issue](https://github.com/servo/servo/issues/30593) for "Multiple webviews in one window". In particular this unchecked subtask gives the impression it's not ready:
> if too many webviews are shown at once, the compositor can get stuck in a laggy state with pending epoch warnings (to reproduce, try https://github.com/servo/servo/pull/31545 with [4.html](https://bucket.daz.cat/work/igalia/servo/4.html) and click “_blank” six or seven times)

Users of my app will expect to be able to put more than six or seven html blocks in their markdown documents, so that's the dealbreaker for me. I also see unchecked tasks around webviews in multiple windows for instance but our app doesn't support multiple windows so it's just the performance thing that concerns me.

Let me know if I got it wrong and the API's ready for my use case! If so I'll get hands-on with it and let you know how it goes.

**Comment by wusyong** [comment]
Close this issue because some major features I need have landed and @mrobinson is the main one to work on WebView API change now. We have some great news from [Tauri](https://tauri.app/blog/tauri-verso-integration/), but I also need to worry about coordinating with multiple communities to ensure delivery. I'll shift my focus a bit to some script features needed later on.
