### ISSUE TITLE
Add CanGC argument to functions that can gc. 

### ISSUE THREAD

**Issue by gterzian** [servo/servo#34573]
As part of https://github.com/servo/servo/issues/33140, I propose we use this as a meta issue to track functions that still need to be updated to take a `can_gc` argument, and adding those seem to me like good tasks for new contributors. I'm starting here with only one.

For an example, see https://github.com/servo/servo/pull/33960

List of function or methods that need a `can_gc: CanGC` argument:

- [x] ~~`enter_realm`~~
- [x] Promise::resolve (JS::ResolvePromise)
- [x] Promise::reject (JS::RejectPromise) 
- [x] Promise::resolve_native
- [x] Promise::reject_native
- [x] Promise::reject_error
- [x] Promise::new_resolved
- [x] Promise::new_rejected
- [x] WindowProxy::set_window (JS_TransplantObject)
- [x] SubtleCrypto::generate_key_aes (JS_NewObject)
- [x] SubtleCrypto::generate_key_hmac
- [x] SubtleCrypto::import_key_aes
- [x] SubtleCrypto::import_key_hkdf
- [x] SubtleCrypto::import_key_hmac
- [x] SubtleCrypto::import_key_pbkdf2
- [x] create_buffer_source (TypedArray::create)
- [x] create_buffer_source_with_length
- [x] DataBlock::view (NewExternalArrayBuffer)
- [x] exception_to_promise
- [x] extract_size_algorithm
- [x] CountQueueingStrategy::GetSize
- [x] ByteLengthQueueingStrategy::GetSize

**Comment by jdm** [comment]
I don't believe that the act of entering a realm can trigger a GC. What makes it a good candidate?

**Comment by gterzian** [comment]
> What makes it a good candidate?

I assume any calls to `js::jsapi::JS_` function can trigger a GC, or could in the future?

**Comment by jdm** [comment]
I'd prefer to be more precise than that, since there are lots of JS API calls that can't trigger a GC. JS::EnterRealm is one of them.

**Comment by jdm** [comment]
I've added a bunch of Rust callsites that invoke JS API functions that are known to trigger GCs. I recommend that anyone working on addressing these should file a new issue and list the methods that they're going to work on!

**Comment by jdm** [comment]
We're going to be looking for changes like https://github.com/servo/servo/blob/a17b2e0cb247e2e6e8d0a66479148d531f33e578/components/script/script_module.rs#L453-L464 in the methods themselves; the point is to make all of the callers pass a CanGc value as an argument (and all of the callers of those callers, etc).

**Comment by yerke** [comment]
@augustebaum @Gae24 It seems we have managed to do duplicate work due to the lack of proper coordination. :(

**Comment by yerke** [comment]
`Promise::resolve` is handled in https://github.com/servo/servo/pull/35616

**Comment by yerke** [comment]
@jdm With https://github.com/servo/servo/pull/35646 and https://github.com/servo/servo/pull/35647, all of the functions/methods in the original list have been covered.

**Comment by jdm** [comment]
I'm going to go ahead and close this, since we've accomplished all of the identified issues.

**Comment by sagudev** [comment]
> I'd prefer to be more precise than that, since there are lots of JS API calls that can't trigger a GC. JS::EnterRealm is one of them.

Generally all SM functions that take JSContext can GC, except if they take https://doc.servo.org/mozjs/jsapi/struct.AutoRequireNoGC.html. Tho it does look like EnterRealm also does not GC (it's argument is raw object and not handle, so there is that). Anyway we will get this more precise in the future work of https://github.com/servo/mozjs/pull/638.
