### ISSUE TITLE
Implement fetchParams

### ISSUE THREAD

**Issue by arthmis** [servo/servo#34741]
`fetchParams`, [spec here](https://fetch.spec.whatwg.org/#fetch-params), is used as an input to several http fetch functions, specifically
- https://fetch.spec.whatwg.org/#main-fetch ([implementation](https://github.com/servo/servo/blob/2ab66ce67870acfff7bf18087421013475411380/components/net/fetch/methods.rs#L209))
- https://fetch.spec.whatwg.org/#scheme-fetch ([implementation](https://github.com/servo/servo/blob/2ab66ce67870acfff7bf18087421013475411380/components/net/fetch/methods.rs#L683))
- https://fetch.spec.whatwg.org/#http-fetch ([implementation](https://github.com/servo/servo/blob/2ab66ce67870acfff7bf18087421013475411380/components/net/http_loader.rs#L732))
- https://fetch.spec.whatwg.org/#http-redirect-fetch ([implementation](https://github.com/servo/servo/blob/2ab66ce67870acfff7bf18087421013475411380/components/net/http_loader.rs#L929))
- https://fetch.spec.whatwg.org/#http-network-or-cache-fetch ([implementation](https://github.com/servo/servo/blob/2ab66ce67870acfff7bf18087421013475411380/components/net/http_loader.rs#L1109))
- https://fetch.spec.whatwg.org/#http-network-fetch ([implementation](https://github.com/servo/servo/blob/2ab66ce67870acfff7bf18087421013475411380/components/net/http_loader.rs#L1741))

Those functions take a plain `request` as input, but it would be good to replace that with a minimal implementation of `fetchParams` only because, the full implementation is a bit more complex. The minimal implementation could look like

```rust
struct FetchParams {
    pub request: Request
    // Todo: implement rest of FetchParams with a link to the spec and link to this issue
}
```

This would help with getting #33616 completed and would bring the fetch implementations a little more in line with the spec.

### Spec

- [x] change `request` argument to `fetch_params` in `main-fetch`, `scheme-fetch`, `http-fetch`, `http-redirect fetch`, `http-network-or-cache fetch`, and `http-network fetch` implementations
- [x] implement request
- [ ] controller (default a new [fetch controller](https://fetch.spec.whatwg.org/#fetch-controller)) A [fetch controller](https://fetch.spec.whatwg.org/#fetch-controller). 
- [ ] process request body chunk length (default null)
- [ ] process request end-of-body (default null)
- [ ] process early hints response (default null)
- [ ] process response (default null)
- [ ] process response end-of-body (default null)
- [ ] process response consume body (default null) Null or an algorithm. 
- [ ] task destination (default null) Null, a [global object](https://html.spec.whatwg.org/multipage/webappapis.html#global-object), or a [parallel queue](https://html.spec.whatwg.org/multipage/infrastructure.html#parallel-queue). 
- [ ] cross-origin isolated capability (default false) A boolean. 
- [ ] timing info A [fetch timing info](https://fetch.spec.whatwg.org/#fetch-timing-info). 
- [ ] preloaded response candidate (default null) Null, "pending", or a [response](https://fetch.spec.whatwg.org/#concept-response).

**Comment by arthmis** [comment]
@jdm could you reopen this issue? There are still more parts of `FetchController` to implement before it's complete. Thank you

**Comment by Gae24** [comment]
`PreloadResponseCandidate` was added in #40059

**Comment by Gae24** [comment]
fetch timing info seems similar to `ResourceFetchTiming`.
