### ISSUE TITLE
Upgrade SpiderMonkey

### ISSUE THREAD

**Issue by jdm** [servo/servo#4338]
The current attempt is sitting in #3527.

Blockers:
* [x] `Vec<Rooted<T>>` replacement (#4334)
* [ ] `Vec<Temporary<T>>` replacement (#4335)
* [x] Equivalent of MutNullableJS for primitives (#4337)
* [ ] Lints to ban further uses of all of the above (#4336)
* [ ] Replace the assertion during tracing DOM objects with an actual rootable object pointer
* [ ] Rebase
* [ ] Ensure review comments in https://critic.hoppipolla.co.uk/r/2730 are addressed.
* [ ] Redesign `Temporary<T>` and `Root<T>` integration by duplicating SM's side tables, rather than storing pointers to Rust objects in them.
* [ ] Add an FFI indirection layer (similar to jsglue.cpp) that calls the non-extern "C" methods in jsapi.h, avoiding the need to modify the header.

Nice to have:
* [x] Extract https://github.com/jdm/servo/commit/c824acd71ef98177f2b878d62c7111aede502f77 into a separate PR
* [ ] Figure out why NSPR hacks are needed (https://github.com/servo/mozjs/commit/5869198ea31f911da76993c47f6a9de04ddf5fb7, https://github.com/servo/rust-mozjs/commit/6e91b33f7749bcacb4fa4cae8d8304e4a3cbf0b6, https://github.com/jdm/servo/commit/9bf03511947a31d91d8c274b5f1d6e297a1da492#diff-eeefd668773bcf179c9bdcf09d495b27R347)
