### ISSUE TITLE
browser.html metabug

### ISSUE THREAD

**Issue by glennw** [servo/servo#5394]
Based on a list from Paul (the author of browser.html)
- [x] mozbrowser APIs.
- [ ] react.js support (#5398).
- [x] Update SpiderMonkey
- [ ] scrollgrab support (https://bugzilla.mozilla.org/show_bug.cgi?id=912666)
- [ ] snap points (https://bugzilla.mozilla.org/show_bug.cgi?id=945584)
- [ ] IndexedDB (per http://logs.glob.uno/?c=mozilla%23servo&s=3+Aug+2015&e=3+Aug+2015&h=browser.html#c250489)

**Comment by paulrouget** [comment]
I've started working on porting browser.html to Servo. See https://github.com/mozilla/browser.html/issues/562

**Comment by paulrouget** [comment]
To make Browser.html an actual app based on Servo, 3 tasks are needed:

1. make sure Servo can properly render Browser.html: https://github.com/mozilla/browser.html/issues/562
2. implement the Browser API or whatever we decide to use to build tabs: https://github.com/mozilla/browser.html/issues/639
3. build a servo runtime: https://github.com/servo/servo/issues/7379

**Comment by gordonbrander** [comment]
We'll also need to implement the minimum footprint for getting [signed code](https://wiki.mozilla.org/FirefoxOS/New_security_model#Signing_-_bug_1153420) working.

**Comment by paulrouget** [comment]
We shipped the first alpha of browserhtml we are planning to move away from the Browser API. Closing.
