### ISSUE TITLE
CI improvement meta bug

### ISSUE THREAD

**Issue by metajack** [servo/servo#7080]
- [x] try incremental builds
- [ ] run wpt with a single servo process
- [ ] make wpt tests not time out
- [ ] get try builders working ( https://github.com/servo/homu/issues/23 ) ( https://github.com/servo/saltfs/issues/179 )
- [ ] run tests in both debug and release modes ( https://github.com/servo/servo/issues/8859 ) ( https://github.com/servo/servo/issues/3450 ) 
- [x] add rust-style highfive support to our highfive (for r? auto-assign, etc)
- [ ] run tidy on dependencies that servo owns (https://github.com/servo/servo/issues/861)

**Comment by edunham** [comment]
@metajack I've edited your comment to include links to the issues which I think correspond to each point. 

To clarify, "try incremental builds" means "experiment with making all builds incremental", not "make the try/auto builds incremental", right? 
 
Are we still experiencing the wpt issues that made the tests time out and motivated running the tests in a single process?

**Comment by edunham** [comment]
> 195 11:47:16 <@jack> edunham: I meant build without cleaning the build dir
> 195 11:47:37 <@jack> Not rust incremental builds but cargo ones
> 195 11:47:48 <@jack> I thought we had done that though

**Comment by mrobinson** [comment]
I think we can close this for now. Apart from improving license checks, which is something we should be able to do with https://docs.rs/cargo-deny/latest/cargo_deny/, I think many of these things aren't really relevant any longer.
