### ISSUE TITLE
servo demos for mid-august 2015

### ISSUE THREAD

**Issue by metajack** [servo/servo#7134]
- [x] [physics demo](https://github.com/gordonbrander/servo-demos/tree/master/physics)
  - [x] publish demo
  - [x] physics demo perf on android https://github.com/servo/servo/issues/7135
- [x] [bad ad demo](https://github.com/gordonbrander/servo-demos/tree/master/physics)
  - [x] publish demo
  - [x] fix sizing isuses on android
  - [x] doesn't animate in chrome
  - [x] position: fixed issues in servo
- [ ] [enyo.js sampler](http://enyojs.com/sampler/latest/) https://github.com/servo/servo/issues/6643
  - [x] create branch for cssText so that master + branch will work
  - [x] fix overflow scroll ~~https://github.com/servo/servo/pull/7090~~
  - [x] fix scrolling clipping ~~https://github.com/servo/rust-layers/pull/199~~ ~~https://github.com/servo/servo/pull/7141~~
  - [x] fix scrolling absolute positioning ~~https://github.com/servo/servo/pull/7147~~
  - [x] rounded corner rendering incorrect (minor) https://github.com/servo/servo/pull/7186
  - [x] test on android
  - [x] display list optimization bug on scrolled layers - see issue ~~https://github.com/servo/servo/issues/7153~~ - ~~https://github.com/servo/servo/pull/7183~~
  - [x] scrollable child layers aren't removed in the compositor when they are removed from the dom - ~~https://github.com/servo/servo/pull/7182~~
  - [x] fix navigation regression introduced by https://github.com/servo/servo/pull/7161 - reverted on demo branch.
  - [x] clicking on menu items works on the first page, but not subsequent pages
  - [ ] rough transition between menus
  - [ ] content pane doesn't render on android
- [ ] [photo gallery](https://github.com/pcwalton/servo-demos/tree/master/photo-gallery)
  - [x] publish demo
  - [x] test on android
  - [x] switch cats for nicer photos
  - [x] make scrubber bigger
  - [x] servo crashes sometimes
  - [ ] scrubbing doesn't work
- [x] [leaflet maps](https://github.com/pcwalton/Leaflet)
  - [x] publish demo
  - [x] test on android
- [ ] [amazon movies](https://github.com/pcwalton/servo-demos/tree/master/amazon-movies)
  - [x] privately publish demo since it contains API keys
  - [x] test on android
  - [ ] not working on android; just blank
- [ ] android issues
  - [ ] scrolling busted https://github.com/servo/servo/issues/7036
  - [ ] underlines are too far down https://github.com/servo/servo/issues/7210
  - [ ] page load times are bad https://github.com/servo/servo/issues/7211
  - [ ] toolbar is hiding content area https://github.com/servo/servo/issues/7212

**Comment by metajack** [comment]
cc @gordonbrander @glennw @pcwalton @larsbergstrom

**Comment by gordonbrander** [comment]
@metajack Chrome animation issue fixed https://github.com/gordonbrander/servo-demos/issues/1

**Comment by glennw** [comment]
@metajack cssText branch is https://github.com/glennw/servo/tree/csstext

**Comment by gordonbrander** [comment]
@metajack do you know the screen resolution of the tablets we'll be demoing on?

**Comment by metajack** [comment]
@gordonbrander The LG G-Pad 8.3" is 1920 x 1200 pixels, 273 ppi. The Samsung Galaxy Tab S 8.4" is 1600 x 2560 Pixel, 359ppi.

**Comment by gordonbrander** [comment]
@metajack I think I may have fixed the sizing issues on Android https://gordonbrander.github.io/servo-demos/evilad/, but it's difficult for me to know, since I can't verify on-device.

**Comment by gordonbrander** [comment]
@metajack there are also issues with position fixed on the ad iframe in Servo. I need to come up with some other approach for this.

**Comment by metajack** [comment]
@pcwalton can you look into this?

**Comment by pcwalton** [comment]
OK, just need to finish up the layout bug I'm working on now.

**Comment by metajack** [comment]
Public demos are published here: http://www.servoexperiments.com/demos.html

**Comment by metajack** [comment]
@pcwalton Can you look at why the servo movies demo is busted on Android?

**Comment by nox** [comment]
I think mid-August 2015 is pretty far back in the past now.
