### ISSUE TITLE
Move web sites to HTTPS

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#7262]
We should HTTPS all the things.

* [x] [servo.org](https://github.com/servo/servo.org) is currently just a redirect to blog.servo.org. We may have more interesting stuff to put there in the future.
* [x] [blog.servo.org](https://github.com/servo/blog.servo.org) is a Jekyll blog generated and hosted by GitHub Pages
* [x] [doc.servo.org](https://github.com/servo/doc.servo.org) is a set of rustdoc documentation generated with `./mach doc` by buildbot and hosted by GitHub Pages
* [x] [servoexperiments.com](https://github.com/servo/servoexperiments.com) (I don’t know how this is hosted, please fill in.)

I don’t know how servo.org DNS is managed these days. Change requests used to go to Bugzilla under "mozilla.org" / "Server Operations" like https://bugzilla.mozilla.org/show_bug.cgi?id=1049897 , but this has been renamed "mozilla.org Graveyard". Maybe "Infrastructure & Operations" / "Infrastructure: DNS"?

@edunham What is the setup for rust-lang.org and subdomains? Does it make sense to do the same here?

**Comment by edunham** [comment]
GitHub currently [does not support HTTPS for custom domains](https://github.com/isaacs/github/issues/156). The way we [dealt with this for rust-lang.org](https://github.com/rust-lang/rust-www/issues/148#issue-89388168) was to switch the blog over to AWS S3 + CloudFront as a CDN. 

I agree that servo.org, blog.servo.org, and doc.servo.org need HTTPS. servoexperiments.com appears to just be a doge head in a Rust logo at the moment -- is it ours? What's it for?

**Comment by frewsxcv** [comment]
> GitHub currently does not support HTTPS for custom domains.

FWIW, [my website](https://rwell.org) is [hosted on GitHub pages](https://github.com/frewsxcv/rwell.org/) and has HTTPS enabled via [CloudFlare](https://www.cloudflare.com/). I just had to update by domain DNS settings to point to CloudFlare's DNS servers. I followed a tutorial [similar to this one](https://www.benburwell.com/posts/configuring-cloudflare-universal-ssl/).

**Comment by frewsxcv** [comment]
To clarify: that comment wasn't meant to show-off my setup nor undermine the previous work done to get HTTPS available on rust-lang.org. I just wanted to share another option that's available. Thanks for all the great work @edunham

**Comment by edunham** [comment]
@frewsxcv Thanks for the feedback! CloudFlare definitely meets the stated requirements for this issue, but managing permissions (at least myself, @metajack, and @larsbergstrom need access to Servo's infrastructure) looks like a bit of a mess. 

[Multi-user organizations](https://support.cloudflare.com/hc/en-us/articles/205065067-How-to-set-up-Multi-User-organizations-on-CloudFlare) are only available for [Enterprise tier accounts](https://www.cloudflare.com/enterprise), which are overpowered for our needs and presumably priced accordingly. I don't regard having several administrators share a single account as a viable option.

**Comment by jdm** [comment]
servoexperiments.com is hosted on nearlyfreespeech.net. From their FAQ, it looks like it's possible to obtain a Comodo Positive SSL DV certificate for ~$20/year with minimal hassle.

**Comment by nodakai** [comment]
http://rust-lang.org/ and http://www.rust-lang.org/ are redirected to https://www.rust-lang.org/ but https://rust-lang.org/ is inaccessible.

**Comment by jdm** [comment]
@nodakai Wrong repository?

**Comment by edunham** [comment]
https://github.com/servo/blog.servo.org/issues/45 is blocking end-to-end SSL on the blog. 

@jdm could you either set up the servoexperiments.com SSL or add the nearlyfreespeech.net login creds to the secrets doc so I can set it up?

**Comment by jdm** [comment]
https://www.servoexperiments.com now works. I'm not certain how to force HTTPS traffic for http://www.servoexperiments.com yet.

**Comment by jdm** [comment]
Fixed that issue. All traffic to servoexperiments.com now goes to HTTPS.

**Comment by frewsxcv** [comment]
Getting an infinite redirect loop for https://doc.servo.org/ right now

**Comment by frewsxcv** [comment]
Works for me now. Disregard my previous comment

**Comment by edunham** [comment]
HTTPS redirects are now working for servo.org, doc, blog, and servoexperiments.com (thanks @jdm!)

We now manage our own DNS through cloudflare (no more Bugzilla service tickets!) and the credentials are in the doc with all the other secrets.

**Comment by LifeIsStrange** [comment]
But cloudfront is probably a spyware :(

**Comment by metajack** [comment]
If it is, we have bigger problems.

Even if it is, having encrypted connections to Cloudflare still prevents local network attacks like session hijacking.

**Comment by edunham** [comment]
@LifeIsStrange We've allowed users to encrypt their connections via CloudFlare to defend them against attacks which could otherwise inject malicious content on servo.org pages. It's true that CloudFlare can see the contents of any request to servo.org, but those requests will currently never contain a user's secrets. If a user needs to hide the very fact that they visited a servo.org domain, they should take additional precautions such as using Tor to access the internet. 

Could you elaborate on the ways in which you're concerned that CloudFlare (I assume you mean the CDN we're using on the Servo sites, not the Amazon product CloudFront) might harm users of servo.org?

**Comment by LifeIsStrange** [comment]
Concretely, there is no problem because this servo sites have not precious data. It's Just an ideological problem. Their business model is based on spying the World. 
Also they block by default the user-agent of Python/urllib (I am not concerned by this problem) and they force the Tor users to accept cookies and to sign a Captcha. 
That's all from what I know so cloudflare is not a big problem for servo related sites. 

Also cloudflare is full free for sites of general interest.  Mozilla is already on this free mode named galileo.  So I think that you could use this :)  https://www.cloudflare.com/galileo/
