### ISSUE TITLE
Tracking bug for style system optimization parity with Gecko

### ISSUE THREAD

**Issue by bholley** [servo/servo#8436]
This issue tracks all of the known style system optimizations present in Gecko and not in Servo.

Currently incomplete, please add any issues you're aware of.
- [x] #6942 basic restyle hints
- [ ] #8437 advanced restyle hints (RESTYLE_SOME_DESCENDANTS)
- [ ] #8438 Stop making RESTYLE_SELF imply RESTYLE_DESCENDANTS
- https://bugzilla.mozilla.org/show_bug.cgi?id=1248509

**Comment by bholley** [comment]
CC @heycam @pcwalton @larsbergstrom @metajack @jdm @Manishearth @SimonSapin

**Comment by LifeIsStrange** [comment]
And why not tracks also all of the known style system optimisations present in blink and not in servo ? :)

**Comment by bholley** [comment]
> And why not tracks also all of the known style system optimisations present in blink and not in servo ? :)

I certainly wouldn't object to somebody filing issues for them and noting them here. Realistically, Servo has high-bandwidth communication with Gecko layout developers (see https://github.com/servo/servo/issues/6942#issuecomment-127445408 ), and so it's much more realistic that we will be able to build a full understanding of the parity issues with Gecko than is the case for Blink.

But again, if layout hackers from other engines are interesting in helping Servo get fast, please file issues about the things that Servo is missing!

**Comment by LifeIsStrange** [comment]
Yes I know this and I doubt very much that Google developers are helping their biggest threat (servo)
But I was thinking that you servo devs can inspect the the most innovative parts of Blink

For exemple for servo webrender  I have added this wiki page "ressources for developers"  which as currently a link of the blink implementation like webrender (sorry for my bad english) see here : https://github.com/glennw/webrender/wiki/Resources-for-developers
We all win to inspire the work of Blink instead of reinventing the wheel or missing good ideas, after all it's not steal, it's free software ! I think that Google will use servo on the future because they will can't compete. 
And now that I thinking, their is Samsung developers on servo, or there are a lot of Samsung developers already on blink ( see : http://mo.github.io/2015/11/04/browser-engines-active-developers-and-commit-rates.html ) so the Samsung servo devs should ask to the Samsung blink devs which already good know the blink code to selection the better innovations/ideas of Blink and implement it on servo =)

**Comment by bholley** [comment]
Again, I'd love it if somebody wants to go dig into style system optimizations in Blink. I just have my hands full right now, which is why I'm not doing it. In particular, I'm investigating what it would take to plug Servo's style system into Gecko, and so gecko parity is more interesting to me at present.

If somebody wants to make a parity-blink meta-issue, and make that issue and this parity-gecko issue block a more-general parity issue, that would be appreciated (though it would only really be useful if that person is also willing to do some cursory digging into Blink's style system to populate the bug).

Also, FWIW @pcwalton has looked at WebKit/Blink's style and layout engines extensively, and so he may have implemented a lot of their good ideas  already.

**Comment by nox** [comment]
Given Stylo is now a thing, I'm *pretty* sure this can be closed.
