### ISSUE TITLE
Update libc to 0.2

### ISSUE THREAD

**Issue by SimonSapin** [servo/servo#8608]
<s>This</s> Some of this blocks the rust upgrade #8446. See https://github.com/rust-lang/rust/issues/29867.

When possible, use `std::os::raw` instead.

Dependencies likely need to be updated as well:

* [x] angle (Should switch from `*` deps) https://github.com/ecoal95/angle
* [x] azure https://github.com/servo/rust-azure https://github.com/servo/rust-azure/pull/206
* [x] block https://github.com/SSheldon/rust-block/commit/45b644f9d40fc8f96f9d1dfc893b3115b19de4f4
* [x] cgl https://github.com/servo/cgl-rs#14
* [x] clipboard (Should switch from `*` deps) aweinstock314/rust-clipboard#18 aweinstock314/rust-clipboard#19
* [x] clipboard-win (Should switch from `*` deps) https://github.com/DoumanAsh/clipboard-win https://github.com/DoumanAsh/clipboard-win/issues/4
* [x] clock_ticks Says: "Deprecated: Use the [`time`](https://crates.io/crates/time) crate instead." https://github.com/tomaka/clock_ticks 
* [x] cocoa https://github.com/servo/cocoa-rs/pull/105
* [x] core-foundation https://github.com/servo/core-foundation-rs/pull/71
* [x] core-graphics https://github.com/servo/core-graphics-rs/pull/45
* [x] core-text (Should switch from `*` deps) https://github.com/servo/core-text-rs 
* [x] dlib https://github.com/vberger/dlib/commit/4281e02cc9220bc3eab022810e5614ede02ad378
* [x] dylib Kintaro/rust-dylib#3
* [x] egl servo/rust-egl#17
* [x] energymon / energymon-default-sys / energymon-syshttps://github.com/energymon/energymon-sys/issues/6
* [x] flate2 https://github.com/alexcrichton/flate2-rs/commit/af3c4b906b89fa5321e45b50ea49bb0772f55d98
* [x] fontconfig https://github.com/servo/rust-fontconfig
* [x] freetype https://github.com/servo/rust-freetype
* [x] gl_common (Where’s the source repo? Possibly https://github.com/bjz/gl-rs/ ?) https://crates.io/crates/gl_common
* [x] gleam https://github.com/servo/gleam
* [x] glutin (Done upstream. Is our fork still diverging?) https://github.com/servo/glutin
* [x] glx (should switch from `*` deps) https://github.com/servo/rust-glx
* [x] harfbuzz-sys https://github.com/servo/rust-harfbuzz
* [x] hbs-common-sys / hbs-pow / hbs-pow-sys https://github.com/libheartbeats/heartbeats-simple-sys/issues/6
* [x] heapsize https://github.com/servo/heapsize/issues/18
* [x] io-surface https://github.com/servo/io-surface-rs
* [x] ipc-channel (should switch from `*` deps) https://github.com/pcwalton/ipc-channel
* [x] js https://github.com/servo/rust-mozjs
* [x] layers https://github.com/servo/rust-layers/pull/215
* [x] libz-sys https://github.com/alexcrichton/libz-sys/commit/2c14f33e42ecdcc161537f4f2dfa395d1a3b1534
* [x] log rust-lang/log@9b56330f20b8ffe2bde5c6a82a191679c35a84bd
* [x] malloc_buf https://github.com/SSheldon/malloc_buf/commit/047e44f6fde58937b1c2574229b4dfdbe8adbf14
* [x] memchr https://github.com/BurntSushi/rust-memchr/commit/4b952004a6764d6b5d32310dec604d32feaecd67
* [x] miniz-sys https://github.com/alexcrichton/flate2-rs/commit/af3c4b906b89fa5321e45b50ea49bb0772f55d98
* [x] mmap https://github.com/rbranson/rust-mmap/issues/6
* [x] mozjs_sys https://github.com/servo/mozjs
* [x] num_cpus seanmonstar/num_cpus#14
* [x] objc https://github.com/SSheldon/rust-objc/commit/fbb62f89e77266500b08e7cc331926a67a7784d9
* [x] objc-foundation https://github.com/SSheldon/rust-objc-foundation/commit/67561e824de7c5c8cd144628e0044633910f8ac4
* [x] offscreen_gl_context https://github.com/ecoal95/rust-offscreen-rendering-context/pull/37
* [x] openssl / openssl-sys https://github.com/sfackler/rust-openssl/commit/309b6d9f46c3ae97dfe0e0594e1a098149f0b950
* [x] osmesa-sys https://github.com/Daggerbot/osmesa-rs/commit/601b7ceabda25686db1bbedd71431ddcbc207b28
* [x] png https://github.com/PistonDevelopers/image-png/pull/6
* [x] rand https://github.com/rust-lang-nursery/rand/commit/f32aa2c2594d3f5135e32bae9b1e69541dc17ed2
* [x] shared_library https://github.com/tomaka/shared_library#1
* [x] skia https://github.com/servo/skia
* [x] stb_image servo/rust-stb-image#82
* [x] tempfile https://github.com/Stebalien/tempfile/pull/16
* [x] time https://github.com/rust-lang-deprecated/time/commit/51c00197e5af83c44cc568c00ce9627a35a037b1
* [x] wayland-client https://github.com/vberger/wayland-client-rs/pull/25
* [x] waland-kbd https://github.com/vberger/wayland-kbd/pull/4
* [x] x11 / x11-dl https://github.com/Daggerbot/x11-rs/pull/32

**Comment by SimonSapin** [comment]
CC @larsbergstrom @mbrubeck @Manishearth

**Comment by frewsxcv** [comment]
> shared_library (Where’s the source repo?)

https://crates.io/crates/shared_library/reverse_dependencies

**Comment by frewsxcv** [comment]
https://github.com/tomaka/shared_library

**Comment by frewsxcv** [comment]
One more after https://github.com/servo/servo/issues/9364, objc-foundation. Just waiting for an answer for https://github.com/rust-lang/cargo/issues/2293

**Comment by frewsxcv** [comment]
Just need a cargo-up (to pick up https://github.com/rust-lang/cargo/pull/2296#issuecomment-173340274), then we can upgrade the last dependency

**Comment by larsbergstrom** [comment]
@frewsxcv You might just be able to yolo-edit the Cargo.lock files.

I've been working on various cargo updates (see #9314 for the most recent) for quite a while now, and there's no end in sight and @alexcrichton also doesn't have any ideas what's going on, so I wouldn't bank on an imminent cargoup.

**Comment by frewsxcv** [comment]
If anyone ever does `mach cargo-update` though, I think it will revert to the older version though?

**Comment by larsbergstrom** [comment]
Hrm, that's possible! After I get win32 support landed in master, the carogup is next on my list, so hopefully I can find a way to fix whatever's going wrong there soon-ish.

**Comment by Ms2ger** [comment]
Fixed in 74b6d8b70debfee90a788d03eef5e6e66792bd1d. Only took three months!
