### ISSUE TITLE
Implement all webdriver commands.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8623]

**Comment by Ms2ger** [comment]
- [x] `AcceptAlert`
- [x] `AddCookie(AddCookieParameters)`
- [x] `Close`
- [x] `DeleteCookies` #23006
- [x] `DeleteCookie(String)`
- [x] `DeleteSession`
- [x] `DismissAlert`
- [x] `ElementClear(WebElement)`
- [x] `ElementClick(WebElement)`
- [ ] `ElementTap(WebElement)`
- [x] `FindElementElements(WebElement, LocatorParameters)`
- [x] `FindElementElement(WebElement, LocatorParameters)`
- [x] `GetAlertText`
- [x] `GetCookies`
- [x] `GetCookie(String)`
- [x] `GetCSSValue(WebElement, String)`
- [x] `GetElementRect(WebElement)`
- [x] <del>`GetWindowSize`</del> #8661
- [x] <del>`IsDisplayed(WebElement)`</del>
- [x] <del>`IsEnabled(WebElement)`</del> #8661
- [x] <del>`IsSelected(WebElement)`</del> #8661
- [ ] `MaximizeWindow`
- [x] `SendAlertText(SendAlertTextParameters)`
- [x] `SetWindowSize(WindowSizeParameters)` #11179
- [x] `SwitchToWindow(SwitchToWindowParameters)`

**Comment by craftytrickster** [comment]
Is it safe to say that `servo/components/webdriver_traits/lib.rs` should be deleted since it seems to be a duplicate of `servo/components/msg/webdriver_msg.rs` and I do not see any usages of it?

**Comment by jdm** [comment]
Yep!

**Comment by craftytrickster** [comment]
I would like to try the following four:
```
GetWindowSize
IsDisplayed(WebElement)
IsEnabled(WebElement)
IsSelected(WebElement) 
```
However, if possible, I do have a few questions:
Getting a reference to the web element seems easy enough, I can copy what is being done in `webdriver_handlers.rs`, for example in the `handle_get_name` function. However, once I have it, do I have to check `get_enabled_state` for isEnabled and `get_focus_state` for isSelected? What would the check for isDisplayed?

Also, I created a branch with a commit to implement the GetWindowSize, but I am not sure how to correctly convert the WindowSizeData to a correct WebDriverResponse. Does anyone have a suggestion?
https://github.com/craftytrickster/servo/commit/5c2e3e3994ee003ef54155315aba5d1414d9de91#diff-a1d91ab451658c0134bb24f8f406dccbR360

I'd appreciate the help, thank you.

**Comment by jdm** [comment]
https://w3c.github.io/webdriver/webdriver-spec.html#h-element-displayedness seems relevant for the first question.

**Comment by jdm** [comment]
As for selected, https://w3c.github.io/webdriver/webdriver-spec.html#is-element-selected .

**Comment by jdm** [comment]
And the window size response should be constructed according to https://w3c.github.io/webdriver/webdriver-spec.html#dfn-get-window-size .

**Comment by craftytrickster** [comment]
@jdm thanks!

**Comment by jgraham** [comment]
Yeah, don't implement IsDisplayed. There isn't a correct way to do that at the moment (or possibly ever), and so we are pushing the application-specific approximation into the client for now.

**Comment by craftytrickster** [comment]
Do the alert items such as GetAlertText only deal with alerts or do they also deal confirm/prompt alerts as well? I ask because I only see (Alert)[https://servo.github.io/doc.servo.org/script/dom/bindings/codegen/Bindings/WindowBinding/trait.WindowMethods.html#tymethod.Alert] on the window methods, I do not see any mention of confirm/prompt. Should confirm/prompt be ignored for now?

**Comment by Ms2ger** [comment]
`confirm`/`prompt` aren't implemented, and probably won't be for quite a while, so do ignore them.

**Comment by danlrobertson** [comment]
I'd like to take a crack at this! If it is okay with everyone, I have an idea as to where to start with `GetElementRect`, so I'd like to start with it.

Let me know at `dlr` on `#servo` if you have any tips or if you have an aversion to me trying this (I'm 100% okay with doing something different if so). If not, I'll probably have my first attempt at a PR sometime this evening.

**Comment by jdm** [comment]
Please do! You can test this by running servo with `--webdriver [port_number]` and playing with the python webdriver client in `tests/wpt/harness/wptrunner/executors/webdriver.py`.

**Comment by asajeffrey** [comment]
#11179 implements GetWindowSize.

**Comment by asajeffrey** [comment]
A couple of related issues: #11254 (support webdriver actions) and #11253 (support webdriver sessions).

**Comment by danlrobertson** [comment]
#10826 implements `AddCookie`, `GetCookie`, and `GetCookies` and has been rebased.

**Comment by lumiscosity** [comment]
Bullet points that are newly resolved now:
- [AcceptAlert](https://github.com/servo/servo/blob/213b532712b0348063e493e6530ac7f6e50e62c3/components/webdriver_server/user_prompt.rs#L203)
- [AddCookie(AddCookieParameters)](https://github.com/servo/servo/blob/213b532712b0348063e493e6530ac7f6e50e62c3/components/webdriver_server/lib.rs#L1701)
- [Close](https://github.com/servo/servo/blob/213b532712b0348063e493e6530ac7f6e50e62c3/components/webdriver_server/lib.rs#L1040)
- [DeleteCookie(String)](https://github.com/servo/servo/blob/213b532712b0348063e493e6530ac7f6e50e62c3/components/webdriver_server/lib.rs#L1748)
- [DeleteSession](https://github.com/servo/servo/blob/213b532712b0348063e493e6530ac7f6e50e62c3/components/webdriver_server/lib.rs#L601)
- [DismissAlert](https://github.com/servo/servo/blob/213b532712b0348063e493e6530ac7f6e50e62c3/components/webdriver_server/user_prompt.rs#L178)
- [ElementClear(WebElement)](https://github.com/servo/servo/blob/213b532712b0348063e493e6530ac7f6e50e62c3/components/webdriver_server/lib.rs#L2059)
- [ElementClick(WebElement)](https://github.com/servo/servo/blob/213b532712b0348063e493e6530ac7f6e50e62c3/components/webdriver_server/lib.rs#L2079)
- [FindElementElement(WebElement, LocatorParameters)](https://github.com/servo/servo/blob/213b532712b0348063e493e6530ac7f6e50e62c3/components/webdriver_server/lib.rs#L1286)
- [FindElementElement(WebElement, LocatorParameters)](https://github.com/servo/servo/blob/213b532712b0348063e493e6530ac7f6e50e62c3/components/webdriver_server/lib.rs#L1299)
- [GetAlertText](https://github.com/servo/servo/blob/213b532712b0348063e493e6530ac7f6e50e62c3/components/webdriver_server/user_prompt.rs#L228)
- [GetCookies](https://github.com/servo/servo/blob/213b532712b0348063e493e6530ac7f6e50e62c3/components/webdriver_server/lib.rs#L1656)
- [GetCookie(String)](https://github.com/servo/servo/blob/213b532712b0348063e493e6530ac7f6e50e62c3/components/webdriver_server/lib.rs#L1677)
- [GetCSSValue(WebElement, String)](https://github.com/servo/servo/blob/213b532712b0348063e493e6530ac7f6e50e62c3/components/webdriver_server/lib.rs#L1633)
- [GetElementRect(WebElement)](https://github.com/servo/servo/blob/213b532712b0348063e493e6530ac7f6e50e62c3/components/webdriver_server/lib.rs#L1474)
- [SendAlertText(SendAlertTextParameters)](https://github.com/servo/servo/blob/213b532712b0348063e493e6530ac7f6e50e62c3/components/webdriver_server/user_prompt.rs#L260)
- [SwitchToWindow(SwitchToWindowParameters)](https://github.com/servo/servo/blob/213b532712b0348063e493e6530ac7f6e50e62c3/components/webdriver_server/lib.rs#L1176)

Partially implemented:
- [MaximizeWindow](https://github.com/servo/servo/blob/213b532712b0348063e493e6530ac7f6e50e62c3/components/webdriver_server/lib.rs#L856) (missing fullscreen handling)
- [SetWindowSize(WindowSizeParameters)](https://github.com/servo/servo/blob/213b532712b0348063e493e6530ac7f6e50e62c3/components/webdriver_server/lib.rs#L791) (I think? webdriver docs say it's embedded in SetWindowSize. See also #11179) (missing fullscreen handling)

Unimplemented:
- ElementTap(WebElement)
