### ISSUE TITLE
Re-enable disabled tests.

### ISSUE THREAD

**Issue by Ms2ger** [servo/servo#8646]
- [ ] `tests/wpt/metadata-css/css21_dev/html4/absolute-replaced-height-007.htm.ini:  disabled: unstable`
- [ ] `tests/wpt/metadata-css/css21_dev/html4/absolute-replaced-height-014.htm.ini:  disabled: Issue 6342`
- [ ] `tests/wpt/metadata-css/css21_dev/html4/absolute-replaced-height-021.htm.ini:  disabled: unstable`
- [ ] `tests/wpt/metadata-css/css21_dev/html4/absolute-replaced-height-028.htm.ini:  disabled: unstable`
- [ ] `tests/wpt/metadata-css/css21_dev/html4/absolute-replaced-height-035.htm.ini:  disabled: unstable`
- [x] #8647 `tests/wpt/metadata-css/css21_dev/html4/background-root-102.htm.ini:  disabled: unstable`
- [x] #8647 `tests/wpt/metadata-css/css21_dev/html4/background-root-103.htm.ini:  disabled: unstable`
- [ ] `tests/wpt/metadata-css/css21_dev/html4/block-in-inline-001.htm.ini:  disabled: seems to assume ascent and block size above baseline are equal`
- [ ] `tests/wpt/metadata-css/css21_dev/html4/block-in-inline-002.htm.ini:  disabled: seems to assume ascent and block size above baseline are equal`
- [ ] `tests/wpt/metadata-css/css21_dev/html4/line-height-125.htm.ini:  disabled: unstable`
- [ ] `tests/wpt/metadata/2dcontext/building-paths/canvas_complexshapes_arcto_001.htm.ini:  disabled: https://github.com/servo/servo/issues/6780`
- [ ] `tests/wpt/metadata/2dcontext/building-paths/canvas_complexshapes_beziercurveto_001.htm.ini:  disabled: https://github.com/servo/servo/issues/6748`
- [ ] `tests/wpt/metadata/2dcontext/compositing/canvas_compositing_globalcompositeoperation_001.htm.ini:  disabled: intermittent pass (issue 5803)`
- [ ] `tests/wpt/metadata/2dcontext/drawing-images-to-the-canvas/drawimage_html_image_1.html.ini:  disabled: see _mozilla`
- [ ] `tests/wpt/metadata/2dcontext/drawing-images-to-the-canvas/drawimage_html_image_10.html.ini:  disabled: see _mozilla`
- [ ] `tests/wpt/metadata/2dcontext/drawing-images-to-the-canvas/drawimage_html_image_11.html.ini:  disabled: see _mozilla`
- [ ] `tests/wpt/metadata/2dcontext/drawing-images-to-the-canvas/drawimage_html_image_12.html.ini:  disabled: see _mozilla`
- [ ] `tests/wpt/metadata/2dcontext/drawing-images-to-the-canvas/drawimage_html_image_13.html.ini:  disabled: see _mozilla`
- [ ] `tests/wpt/metadata/2dcontext/drawing-images-to-the-canvas/drawimage_html_image_2.html.ini:  disabled: see _mozilla`
- [ ] `tests/wpt/metadata/2dcontext/drawing-images-to-the-canvas/drawimage_html_image_3.html.ini:  disabled: see _mozilla`
- [ ] `tests/wpt/metadata/2dcontext/drawing-images-to-the-canvas/drawimage_html_image_4.html.ini:  disabled: see _mozilla`
- [ ] `tests/wpt/metadata/2dcontext/drawing-images-to-the-canvas/drawimage_html_image_5.html.ini:  disabled: see _mozilla`
- [ ] `tests/wpt/metadata/2dcontext/drawing-images-to-the-canvas/drawimage_html_image_6.html.ini:  disabled: see _mozilla`
- [ ] `tests/wpt/metadata/2dcontext/drawing-images-to-the-canvas/drawimage_html_image_7.html.ini:  disabled: see _mozilla`
- [ ] `tests/wpt/metadata/2dcontext/drawing-images-to-the-canvas/drawimage_html_image_8.html.ini:  disabled: see _mozilla`
- [ ] `tests/wpt/metadata/2dcontext/drawing-images-to-the-canvas/drawimage_html_image_9.html.ini:  disabled: see _mozilla`
- [ ] `tests/wpt/metadata/2dcontext/line-styles/canvas_linestyles_linecap_001.htm.ini:  disabled: intermittently passing (issue 5714)`
- [ ] `tests/wpt/metadata/2dcontext/shadows/canvas_shadows_002.htm.ini:  disabled: intermittent failure (issue 5207)`
- [ ] `tests/wpt/metadata/2dcontext/the-canvas-state/canvas_state_restore_001.htm.ini:  disabled: intermittent pass (issue 5764)`
- [ ] `tests/wpt/metadata/2dcontext/transformations/canvas_transformations_scale_001.htm.ini:  disabled: flaky`
- [ ] `tests/wpt/metadata/XMLHttpRequest/responsetext-decoding.htm.ini:  disabled: flaky`
- [ ] `tests/wpt/metadata/XMLHttpRequest/send-entity-body-document.htm.ini:  disabled:`
- [ ] `tests/wpt/metadata/XMLHttpRequest/xmlhttprequest-timeout-worker-overrides.html.ini:  disabled: flaky - https://github.com/w3c/web-platform-tests/issues/1362`
- [ ] `tests/wpt/metadata/XMLHttpRequest/xmlhttprequest-timeout-worker-overridesexpires.html.ini:  disabled: racy test`
- [ ] `tests/wpt/metadata/XMLHttpRequest/xmlhttprequest-timeout-worker-twice.html.ini:  disabled: flaky`
- [ ] `tests/wpt/metadata/dom/nodes/Document-characterSet-normalization.html.ini:  disabled: fails intermittently`
- [ ] `tests/wpt/metadata/dom/nodes/Document-createElement-namespace.html.ini:  disabled: extremely frequent intermittent crash #8614`
- [ ] `tests/wpt/metadata/dom/nodes/Document-createProcessingInstruction.xhtml.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Document-getElementsByTagName.xhtml.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Element-childElement-null.svg.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Element-childElement-null.xhtml.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Element-childElementCount-dynamic-add.svg.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Element-childElementCount-dynamic-add.xhtml.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Element-childElementCount-dynamic-remove.svg.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Element-childElementCount-dynamic-remove.xhtml.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Element-childElementCount-nochild.svg.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Element-childElementCount-nochild.xhtml.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Element-childElementCount.svg.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Element-childElementCount.xhtml.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Element-firstElementChild-entity.svg.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Element-firstElementChild-entity.xhtml.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Element-firstElementChild-namespace.svg.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Element-firstElementChild-namespace.xhtml.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Element-firstElementChild.svg.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Element-firstElementChild.xhtml.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Element-lastElementChild.svg.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Element-lastElementChild.xhtml.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Element-nextElementSibling.svg.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Element-nextElementSibling.xhtml.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Element-previousElementSibling.svg.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Element-previousElementSibling.xhtml.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Element-siblingElement-null.svg.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/dom/nodes/Element-siblingElement-null.xhtml.ini:  disabled: xml`
- [ ] `tests/wpt/metadata/encoding/single-byte-decoder.html.ini:  disabled: iframe thread issue 5247`
- [ ] `tests/wpt/metadata/html/browsers/browsing-the-web/unloading-documents/__dir__.ini:disabled: for now`
- [ ] `tests/wpt/metadata/html/browsers/history/the-history-interface/__dir__.ini:disabled: for now`
- [ ] `tests/wpt/metadata/html/browsers/offline/__dir__.ini:disabled: for now`
- [ ] `tests/wpt/metadata/html/browsers/the-window-object/accessing-other-browsing-contexts/indexed-browsing-contexts-01.html.ini:  disabled: flaky`
- [ ] `tests/wpt/metadata/html/dom/documents/resource-metadata-management/document-lastModified-01.html.ini:  disabled: https://github.com/servo/servo/issues/3228`
- [ ] `tests/wpt/metadata/html/dom/dynamic-markup-insertion/__dir__.ini:disabled: for now`
- [ ] `tests/wpt/metadata/html/dom/elements/global-attributes/dir_auto-contained-script-L.html.ini:  disabled: flaky`
- [ ] `tests/wpt/metadata/html/dom/elements/global-attributes/dir_auto-contained-script-R.html.ini:  disabled: flaky`
- [ ] `tests/wpt/metadata/html/dom/elements/global-attributes/dir_auto-input-script-EN-L.html.ini:  disabled: flaky`
- [ ] `tests/wpt/metadata/html/dom/elements/global-attributes/dir_auto-input-script-EN-R.html.ini:  disabled: flaky`
- [ ] `tests/wpt/metadata/html/dom/elements/global-attributes/dir_auto-input-script-L.html.ini:  disabled: flaky`
- [ ] `tests/wpt/metadata/html/dom/elements/global-attributes/dir_auto-input-script-N-EN-L.html.ini:  disabled: flaky`
- [ ] `tests/wpt/metadata/html/dom/elements/global-attributes/dir_auto-input-script-N-EN-R.html.ini:  disabled: flaky`
- [ ] `tests/wpt/metadata/html/dom/elements/global-attributes/dir_auto-input-script-N-EN.html.ini:  disabled: flaky`
- [ ] `tests/wpt/metadata/html/dom/elements/global-attributes/dir_auto-input-script-N-L.html.ini:  disabled: flaky`
- [ ] `tests/wpt/metadata/html/dom/elements/global-attributes/dir_auto-input-script-N-R.html.ini:  disabled: flaky`
- [ ] `tests/wpt/metadata/html/dom/elements/global-attributes/dir_auto-input-script-R.html.ini:  disabled: flaky`
- [ ] `tests/wpt/metadata/html/dom/elements/global-attributes/dir_auto-textarea-script-N-EN.html.ini:  disabled: flaky`
- [ ] `tests/wpt/metadata/html/dom/elements/global-attributes/dir_auto-textarea-script-N-between-Rs.html.ini:  disabled: flaky`
- [ ] `tests/wpt/metadata/html/dom/elements/global-attributes/dir_auto-textarea-script-mixed.html.ini:  disabled: flaky`
- [ ] `tests/wpt/metadata/html/editing/__dir__.ini:disabled: for now`
- [ ] `tests/wpt/metadata/html/infrastructure/urls/resolving-urls/query-encoding/__dir__.ini:disabled: for now`
- [ ] `tests/wpt/metadata/html/semantics/document-metadata/the-meta-element/pragma-directives/attr-meta-http-equiv-refresh/parsing.html.ini` (#8749)
- [ ] `tests/wpt/metadata/html/semantics/embedded-content/media-elements/__dir__.ini:disabled: for now`
- [ ] `tests/wpt/metadata/html/semantics/embedded-content/the-audio-element/__dir__.ini:disabled: for now`
- [ ] `tests/wpt/metadata/html/semantics/embedded-content/the-img-element/relevant-mutations.html.ini:  disabled: unstable failures and timeouts in release builds`
- [x] `tests/wpt/metadata/html/semantics/embedded-content/the-li-element/grouping-li/__dir__.ini:disabled: for now`
- [x] `tests/wpt/metadata/html/semantics/embedded-content/the-ol-element/grouping-ol/__dir__.ini:disabled: for now`
- [ ] `tests/wpt/metadata/html/semantics/embedded-content/the-video-element/__dir__.ini:disabled: for now`
- [ ] `tests/wpt/metadata/html/semantics/forms/the-input-element/type-change-state.html.ini:  disabled: intermittent failures`
- [ ] `tests/wpt/metadata/html/semantics/scripting-1/the-template-element/additions-to-parsing-xhtml-documents/__dir__.ini:disabled: XHTML`
- [ ] `tests/wpt/metadata/html/semantics/scripting-1/the-template-element/additions-to-serializing-xhtml-documents/__dir__.ini:disabled: XHTML`
- [ ] `tests/wpt/metadata/html/syntax/parsing-html-fragments/__dir__.ini:disabled: for now`
- [ ] `tests/wpt/metadata/html/syntax/parsing/__dir__.ini:disabled: for now`
- [ ] `tests/wpt/metadata/html/webappapis/system-state-and-capabilities/__dir__.ini:disabled: for now`
- [ ] `tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/030.html.ini:  disabled: flaky`
- [ ] `tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/080.html.ini:  disabled: flaky`
- [ ] `tests/wpt/metadata/old-tests/submission/Opera/script_scheduling/099.html.ini:  disabled: flaky`
- [ ] `tests/wpt/metadata/webgl/bufferSubData.html.ini:  disabled: https://github.com/servo/servo/issues/8462`
- [ ] `tests/wpt/metadata/webgl/compressedTexImage2D.html.ini:  disabled: https://github.com/servo/servo/issues/8462`
- [ ] `tests/wpt/metadata/webgl/compressedTexSubImage2D.html.ini:  disabled: https://github.com/servo/servo/issues/8462`
- [ ] `tests/wpt/metadata/webgl/uniformMatrixNfv.html.ini:  disabled: https://github.com/servo/servo/issues/8462`
- [ ] `tests/wpt/metadata/workers/Worker_terminate_event_queue.htm.ini:  disabled: too much output`
- [ ] `tests/wpt/metadata/workers/constructors/SharedWorker/__dir__.ini:disabled: SharedWorker`
- [ ] `tests/wpt/metadata/workers/constructors/Worker/same-origin.html.ini:  disabled: intermittent failures`
- [x] `tests/wpt/metadata/workers/interfaces/WorkerUtils/importScripts/004.html.ini:  disabled: flaky crash detection`
- [x] `tests/wpt/metadata/workers/interfaces/WorkerUtils/importScripts/005.html.ini:  disabled: flaky crash detection`
- [x] `tests/wpt/metadata/workers/interfaces/WorkerUtils/importScripts/006.html.ini:  disabled: flaky crash detection`
- [ ] `tests/wpt/metadata/workers/semantics/reporting-errors/__dir__.ini:disabled: SharedWorker`
- [ ] `tests/wpt/metadata/workers/semantics/structured-clone/__dir__.ini:disabled: Broken somehow`
- [ ] `tests/wpt/mozilla/meta/mozilla/webgl/clearcolor.html.ini:  disabled:`
- [ ] `tests/wpt/mozilla/meta/mozilla/webgl/draw_arrays_simple.html.ini:  disabled:`
- [ ] `tests/wpt/mozilla/meta/mozilla/webgl/tex_image_2d_canvas.html.ini:  disabled:`
- [ ] `tests/wpt/mozilla/meta/mozilla/webgl/tex_image_2d_canvas2d.html.ini:  disabled:`
- [ ] `tests/wpt/mozilla/meta/mozilla/webgl/tex_image_2d_canvas_no_context.html.ini:  disabled:`
- [ ] `tests/wpt/mozilla/meta/mozilla/webgl/tex_image_2d_simple.html.ini:  disabled:`
