### ISSUE TITLE
Support dynamic style/link elements

### ISSUE THREAD

**Issue by jdm** [servo/servo#976]
Things to support:
- [x] adding link elements to the document (#3346)
- [x] removing link elements from the document (#14886)
- [x] adding style elements to the document (#1984)
- [x] removing style elements from the document (#14886)
- [x] modifying the content of a style element (#14886)
- [x] modifying the href attribute of a link element (#3361)
