### ISSUE TITLE
DuckDuckGo bugs

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9915]
We want to properly support duckduckgo.com. It needs to behave and be rendered properly (homepage and search result page).

See https://github.com/servo/servo/wiki/WebCompatBug

---
- [x] https://github.com/servo/servo/issues/7635
- [x] https://github.com/servo/servo/issues/10309
- [x] https://github.com/servo/servo/issues/11150
- [x] https://github.com/servo/servo/issues/11151
- [x] https://github.com/servo/servo/issues/11489
- [x] https://github.com/servo/servo/issues/11928
- [ ] https://github.com/servo/servo/issues/12097
- [x] https://github.com/servo/servo/issues/17637
- [x] https://github.com/servo/servo/issues/17725
- [x] https://github.com/servo/servo/issues/17941 
- [x] https://github.com/servo/servo/issues/17942
- [x] https://github.com/servo/servo/issues/18039
- [x] https://github.com/servo/servo/issues/18258
- [x] https://github.com/servo/servo/issues/18333
- [x] https://github.com/servo/servo/issues/18647
- [x] https://github.com/servo/servo/issues/18769
- [x] https://github.com/servo/servo/issues/18978
- [x] https://github.com/servo/servo/issues/19052
- [x] https://github.com/servo/servo/issues/19121
- [x] https://github.com/servo/servo/issues/19122
- [x] https://github.com/servo/servo/issues/19348
- [x] https://github.com/servo/servo/issues/19869
- [x] https://github.com/servo/servo/issues/21165
- [x] https://github.com/servo/servo/issues/22090

**Comment by metajack** [comment]
Added #11928

**Comment by asajeffrey** [comment]
At the moment, the search results page renders, but http://duckduckgo.com/ does not. Should we just replace the link from our front page to, e.g. https://duckduckgo.com/?q=servo

**Comment by asajeffrey** [comment]
https://github.com/browserhtml/browserhtml/pull/1113 moves over to http://duckduckgo.com/html, which papers over this crack.

**Comment by atouchet** [comment]
#12097 could be added to this as well.

**Comment by atouchet** [comment]
#11928 can be marked as fixed.

**Comment by atouchet** [comment]
#17637 and #17725 are DuckDuckGo issues. #11489 can be marked as fixed.

**Comment by atouchet** [comment]
I believe #17725 is now fixed.

**Comment by atouchet** [comment]
#17941 is a DuckDuckGo issue.

**Comment by metajack** [comment]
Updated

**Comment by metajack** [comment]
@atouchet I have invited you to the Developers group which will give you access to edit and label bugs. We cannot separate editing a bug from committing to the repo, so please don't do that :)

**Comment by atouchet** [comment]
@metajack Alright, sounds good.
