### ISSUE TITLE
Hacker News bugs

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#9916]
We want to properly support https://news.ycombinator.com. It needs to behave and be rendered properly (frontpage, comments, login).

See https://github.com/servo/servo/wiki/WebCompatBug

---
- [x] https://github.com/servo/servo/issues/10022
- [x] https://github.com/servo/servo/issues/10233
- [x] https://github.com/servo/servo/issues/10234
- [x] https://github.com/servo/servo/issues/11821
- [ ] https://github.com/servo/servo/issues/17512
- [x] https://github.com/servo/servo/issues/22132

**Comment by atouchet** [comment]
#10233 can be marked as fixed.

**Comment by atouchet** [comment]
#17512 and #17513 are Hacker News issues.

**Comment by MichaelMcDonnell** [comment]
I use right-click to open new tabs when I read Hacker News in Firefox but it hasn't been implemented in Servo #38062

**Comment by MichaelMcDonnell** [comment]
Scrolling also feels too slow in Servo compared to Firefox which makes reading articles less nice. See #38072
